<?php
    $form       = $this->form;
    $csrf       = $form->get('secret');
    $title      = $form->get('name-title');
    $firstname  = $form->get('name-first');
    $lastname   = $form->get('name-last');
    $address1   = $form->get('address-address1');
    $address2   = $form->get('address-address2');
    $address3   = $form->get('address-address3');
    $postcode   = $form->get('address-postcode');
    
    $title->setOptions( ['label' => 'Title'] );
    $firstname->setOptions( ['label' => 'First names'] );
    $lastname->setOptions( ['label' => 'Last names'] );
    $address1->setOptions( ['label' => 'Address line 1'] );
    $address2->setOptions( ['label' => 'Address line 2'] );
    $address3->setOptions( ['label' => 'Address line 3'] );
    $postcode->setOptions( ['label' => 'Postcode'] );
    
    $submit     = $form->get('submit');
    $submit->setAttributes(['value'=>'Save and continue']);
    
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>


<?= $this->form()->openTag($form); ?>

<div class="<?= $this->elementGroupClass($csrf) ?>">
    <?= $this->formElement($csrf) ?>
    <?= $this->formElementErrors($csrf) ?>
</div>

<div class="form_element">

    <?= $formLabel->openTag() . $title->getOption('label'); ?>
    
    <?= $this->formElement($title) ?>
    <?= $this->formElementErrors($title) ?>
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $firstname->getOption('label'); ?>
    
    <?= $this->formElement($firstname) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($firstname) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $lastname->getOption('label'); ?>
    
    <?= $this->formElement($lastname) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($lastname) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address1->getOption('label'); ?>
    
    <?= $this->formElement($address1) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address1) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address2->getOption('label'); ?>
    
    <?= $this->formElement($address2) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address2) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address3->getOption('label'); ?>
    
    <?= $this->formElement($address3) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address3) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $postcode->getOption('label'); ?>
    
    <?= $this->formElement($postcode) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($postcode) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $this->formElement($submit) ?>

</div>

<?= $this->form()->closeTag(); ?>