<!DOCTYPE html>
<!--[if lt IE 9]><html class="lte-ie8" lang="en"><![endif]-->
<!--[if gt IE 8]><!-->

<html lang="en">
<!--<![endif]-->

  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta http-equiv="refresh" content="2">
    
    <title>Generating your document | GOV.UK</title>

	<style type="text/css">
		h2 {
			text-align: center;
			padding-top: 10%;
		}
	</style>

</head>
<body>
	
	<h2>Please wait while we generate your document. It will appear here in a few seconds.</h2>

</body>
</html>
