<?php echo $this->partial('partials/document/document-top.phtml'); ?>

<header class="page-header group">
<hgroup>
<h1><?php echo $this->pageTitle(); ?></h1>
</hgroup>
</header>

<?php echo $this->partial('partials/document/body/opg/opg-content-top.phtml'); ?>

<?php if(isset($this->contentHeader)): ?>

    <?= $this->partial('layout/partials/main-content-headers/'.$this->contentHeader) ?>
    
<?php endif; ?>

<?= $this->accordionTop() ?>
<?= $this->content ?>
<?= $this->accordionBottom() ?>

<?php echo $this->partial('partials/document/document-bottom.phtml'); ?>
