<?php echo $this->partial('partials/document/document-top.phtml'); ?>

<header class="page-header group">
<hgroup>
<h1><?php echo $this->pageTitle(); ?></h1>
</hgroup>
</header>

<?php echo $this->partial('partials/document/body/opg/opg-content-top.phtml'); ?>

<?= $this->layoutPartial(); ?>

<?php echo $this->layout()->content; ?>

<?php echo $this->partial('partials/document/document-bottom.phtml'); ?>
