<!DOCTYPE html>

<style>
.form input[type="radio"] {
  margin-right: 0.25em;
  vertical-align: 2px; }
  </style>
<!--[if lt IE 9]>
<html class="lte-ie8" lang="en">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <html lang="en">
        <!--<![endif]-->
        <head>
            <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
            <title>Make a lasting power of attorney | GOV.UK</title>
            <script type="text/javascript">
                (function(){if(navigator.userAgent.match(/IEMobile\/10\.0/)){var d=document,c="appendChild",a=d.createElement("style");a[c](d.createTextNode("@-ms-viewport{width:auto!important}"));d.getElementsByTagName("head")[0][c](a);}})();
            </script>
            <!--[if gt IE 8]><!--><link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/application-a82ba1f455ff45927664ef45062f9cf7.css" media="screen" rel="stylesheet" type="text/css" /><!--<![endif]-->
            <!--[if IE 6]><link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/application-ie6-4026ead82285bf16a3e06874a252876e.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
            <!--[if IE 7]><link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/application-ie7-8b614a81fdb6afed53f5b2acc5351a9c.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
            <!--[if IE 8]><link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/application-ie8-4bdfe7c675d5196a0236095948106fd6.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
            <link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/print-a250641f33ac06dba78975b0c65f8ac9.css" media="print" rel="stylesheet" type="text/css" />
            <!--[if IE 8]>
            <script type="text/javascript">
                (function(){if(window.opera){return;}
                setTimeout(function(){var a=document,g,b={families:(g=
                ["nta"]),urls:["/assets/v1/assets-digital-cabinet-office-gov-uk-static/fonts-ie8-beb10cbc00c9b7dcdbdee824962bc5f6.css"]},
                c="/assets/v1/assets-digital-cabinet-office-gov-uk-static/libs/goog/webfont-debug-96870cf9f159ed811fd43c39bdf4656b.js",d="script",
                e=a.createElement(d),f=a.getElementsByTagName(d)[0],h=g.length;WebFontConfig
                ={custom:b},e.src=c,f.parentNode.insertBefore(e,f);for(;h=h-1;a.documentElement
                .className+=' wf-'+g[h].replace(/\s/g,'').toLowerCase()+'-n4-loading');},0)
                })()
            </script>
            <![endif]-->
            <!--[if gte IE 9]><!--><link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/fonts-0fb6b917e34e45c93a44eec72dcc21de.css" media="all" rel="stylesheet" type="text/css" /><!--<![endif]-->
            <!--[if lt IE 9]><script src="/assets/v1/assets-digital-cabinet-office-gov-uk-static/ie-27ccded64045ab36dbfb67c2f47c362b.js" type="text/javascript"></script><![endif]-->
            <link rel="shortcut icon" href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/favicon-447e4ac1ab790342660eacfe3dcce264.ico" type="image/x-icon" />
            <!-- For third-generation iPad with high-resolution Retina display: -->
            <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/apple-touch-icon-144x144-4e306e01c31e237722b82b7aa7130082.png">
            <!-- For iPhone with high-resolution Retina display: -->
            <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/apple-touch-icon-114x114-f1d7ccdc7b86d923386b373a9ba5e3db.png">
            <!-- For first- and second-generation iPad: -->
            <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/apple-touch-icon-72x72-2ddbe540853e3ba0d30fbad2a95eab3c.png">
            <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
            <link rel="apple-touch-icon-precomposed" href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/apple-touch-icon-57x57-37527434942ed8407b091aae5feff3f3.png">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta name="og:image" content="/assets/v1/assets-digital-cabinet-office-gov-uk-static/opengraph-image-4e469785ca4cc8f8dd18d0627bc43d19.png">
            <meta name="description" content="Make a lasting power of attorney">
            <meta content="Family" name="x-section-name">
            <meta content="/browse/family" name="x-section-link">
            <meta content="local_transaction" name="x-section-format">
            <?php  echo $this->headMeta()?>
            <!--[if gt IE 8]><!--><link href="<?= $this->staticAssetPath('/assets/v1/css/styles.css') ?>" media="screen" rel="stylesheet" type="text/css" /><!--<![endif]-->
            <!--[if IE 6]><link href="<?= $this->staticAssetPath('/assets/v1/css/ie6.css') ?>" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
            <!--[if IE 7]><link href="<?= $this->staticAssetPath('/assets/v1/css/ie7.css') ?>" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
            <!--[if IE 8]><link href="<?= $this->staticAssetPath('/assets/v1/css/ie8.css') ?>" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
            <!-- LPA Print styles -->
            <link href="<?= $this->staticAssetPath('/assets/v1/css/print.css') ?>" media="print" rel="stylesheet" type="text/css" />
            <?php echo $this->headLink()?>
        </head>
        <body class="mainstream full-width beta"
            data-journey="stageprompt.lpa:page:<?= htmlspecialchars(substr($_SERVER['REQUEST_URI'],1)) ?>">
            <script type="text/javascript">document.body.className = document.body.className + ' js-enabled';</script>
            <a href="#content" class="visuallyhidden">Skip to main content</a>
            <header role="banner" id="global-header"
                class="global-header with-proposition">
                <div class="header-wrapper">
                    <div class="header-global">
                        <div class="header-logo">
                            <a href="https://www.gov.uk/" title="Go to the GOV.UK homepage"
                                id="logo" class="content"> <img
                                src="<?= $this->staticAssetPath('/assets/v1/images/gov.uk_logotype_crown.png') ?>"
                                width="35" height="31" alt=""> GOV.UK
                            </a>
                        </div>
                    </div>
                    <?php if ($this->routeName() != 'home') : ?>
                    <div class="header-proposition">
                        <div class="content">
                            <nav id="proposition-menu">
                                <span class="home"><a href="<?= $this->url( 'home', [] ) ?>" id="proposition-name">Make a lasting power of attorney</a></span>
                            </nav>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>
            </header>
            <div id="wrapper">
            
                <section id="content" role="main" class="group">
                    <?= $this->accountInfo(); ?>
                    <?php echo $this->systemMessage(); ?>
                    <?= $this->pageHeaders(); ?>
                                
                                <?php if(isset($this->contentHeader)): ?>
                                <?= $this->partial('layout/partials/main-content-headers/'.$this->contentHeader)?>
                                
                                <div id="accordion" class="accordion-form">
                                <?php endif; ?>

                                <?php
                                    echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
                                    echo $this->flashMessenger()->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
                                    echo $this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
                                    echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success'));
                                    echo $this->flashMessenger()->render('warning', array('alert', 'alert-dismissible', 'alert-warning'));
                                ?>
                                
                                <?php
                                
                                    $accordionTop = $this->accordionTop($this->lpa);
                                    if(is_array($accordionTop)) {
                                        echo $this->partialloop('layout/partials/accordion/accordion.phtml', $accordionTop);
                                    }
                                ?>
                                
                                <?= $this->content; ?>
                                
                                <?php
                                    $accordionBottom = $this->accordionBottom($this->lpa);
                                    if(is_array($accordionBottom)) {
                                        echo $this->partialloop('layout/partials/accordion/accordion.phtml', $accordionBottom);
                                    }
                                ?>
                                
                                <?php if(isset($this->contentHeader)): ?>
                                </div> <!-- Close accordion --> 
                                <?php endif; ?>
                            
                            </div> <!-- article-container group -->
                            </article> <!-- These tags opened either in pageHeaders() or in $this->contentHeader -->
                    </div>
                    <div class="lpa-footer inner">
                        <hr>
                        <p>
                            Your <a href="/send-feedback">feedback</a> will help us to improve <span style="float: right"><a target="_blank" href="/terms-and-conditions">Terms and conditions</a></span>
                        </p>
                    </div>
                </section>
            </div>
            <footer class="group" id="footer" role="contentinfo">
                <div class="footer-wrapper">
                    <div class="footer-meta">
                        <div class="footer-meta-inner">
                            <h2 class="visuallyhidden">Support links</h2>
                            <ul>
                                <li>Built by <a target="_blank" href="https://www.gov.uk/government/organisations/office-of-the-public-guardian">OPG Digital</a></li>
                            </ul>
                            <div class="open-government-licence">
                                <h2>
                                    <a target="_blank" href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2">Open Government Licence</a>
                                </h2>
                                <p>
                                    All content is available under the <a target="_blank" href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2">Open Government Licence v2.0</a>, except where otherwise stated
                                </p>
                            </div>
                        </div>
                        <div class="copyright">
                            <a target="_blank" href="http://www.nationalarchives.gov.uk/information-management/our-services/crown-copyright.htm">© Crown copyright</a>
                        </div>
                    </div>
                </div>
            </footer>
            <script src="<?= $this->staticAssetPath('/assets/v1/js/jquery-ui-1.10.3.custom/js/jquery-1.9.1.min.js'); ?>"></script>
            <script src="<?= $this->staticAssetPath('/assets/v1/js/application.js') ?>"></script>
            <?php echo $this->headScript()?>
            <?php if (false /* @todo $this->environment() == 'production'*/) : ?>
            <script>
                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
                
                ga('create', 'UA-33184303-1', { 'allowLinker': true });
                
                var type = document.getElementById('lpa-type');
                
                if (type && type.className.match(/complete/i)) {
                    type = type.innerHTML.match(/(health|welfare)/i) ? 'health and welfare' : 'property and financial';
                    ga('set', 'dimension1', type);
                }
                
                ga('send', 'pageview');
                GOVUK.performance.stageprompt.setupForGoogleAnalytics();
            </script>
            <?php endif;?>
        </body>
    </html>