            <header class="page-header group">
            	<hgroup>
            	<nav role="navigation" class="progress-indicator group static" style="width: 1004px;">
            		<ol class="group">
            			<li>About you</li>
            			<li>Create the LPA</li>
            			<li>Sign the LPA</li>
            			<li class="active">Register the LPA</li>
            			<li>Done</li>
            		</ol>
            	</nav>
            		<h1>Register a lasting power of attorney</h1>
            	</hgroup>
        	</header>        
