FROM nginx:stable-alpine
COPY /service-gateway-mock/nginx.conf.template /nginx.conf.template
CMD envsubst "$${OPG_LPA_STATUS_ENDPOINT}" < /nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"
