FROM nginx:stable-alpine
COPY /service-gateway-mock/gateway-nginx.conf.template /nginx.conf.template

CMD envsubst '${OPG_LPA_STATUS_ENDPOINT} ${OPG_LPA_MOCK_SIRIUS_ADDRESS}' < /nginx.conf.template > /etc/nginx/conf.d/default.conf && printenv && nginx -g "daemon off;"
