FROM nginx:stable-alpine
COPY /service-gateway-mock/nginx.conf.template /nginx.conf.template

CMD envsubst '${OPG_LPA_STATUS_ENDPOINT}, ${OPG_LPA_MOCK_SIRIUS_ADDRESS}' < /gateway-nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g "daemon on;"
