FROM stoplight/prism:4

RUN apk add python3 py3-pip

COPY scripts swagger-examples.yaml run.sh /app/

# get the Sirius API gateway swagger file, add examples, make run script executable;
# this removes the invalid ${allowed_roles} from lpa-openapi.yml which prevents
# it being parsed as YAML
RUN cd /app/ && \
    wget https://raw.githubusercontent.com/ministryofjustice/opg-data-lpa/master/lambda_functions/v1/openapi/lpa-openapi.yml && \
    sed -i -e 's|${allowed_roles}||' lpa-openapi.yml && \
    pip3 install --upgrade pip && \
    pip3 install -r requirements.txt && \
    python3 merge_yaml.py lpa-openapi.yml swagger-examples.yaml > swagger.yaml && \
    chmod +x run.sh

# starts the mock server on port 5011
ENTRYPOINT ["/app/run.sh"]
