FROM nginx:stable-alpine
COPY gateway-nginx.conf.template /nginx.conf.template

CMD envsubst '${OPG_LPA_STATUS_ENDPOINT} ${OPG_LPA_MOCK_SIRIUS_ADDRESS} ${OPG_LPA_API_FQDN}' < /nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"
