        <div class="person-summary group">
            <div class="person">
                <h3><?= $this->notifiedPerson['name'] ?></h3>
                <p><?= $this->notifiedPerson['address'] ?></p>
            </div>
            
            <ul class="actions">
                <li><a href="<?= $this->editRoute ?>" class="js-form-popup">View/edit details</a></li>
                <li><a href="<?= $this->deleteRoute ?>" class="js-confirm" data-confirm-question="Do you want to remove this person?">Delete</a></li>
            </ul>
        </div>
