<div class="account-activated">
    
    <div class="opg-padded">

        <h1>Account activated</h1>


        <? /* Show the same error for both situations. */ ?>
        <? if (isset($this->error)) { ?>

            <p>We couldn't activate your account. This is probably for one of two reasons:
            <ol>
                <li>You've already activated your account, in which case you can <a href="<?= $this->url('login') ?>">sign in here</a></li>
                <li>You didn't activate your account within 24 hours, in which case you can <a href="<?= $this->url('register') ?>">re-register here</a></li>
            </ol>
            </p>

            <p>If this doesn't work and you need further assistance, send an email to <a
                    href="mailto:customerservices@PublicGuardian.gsi.gov.uk">customerservices@PublicGuardian.gsi.gov.uk</a>
                or call 0300 456 0300.</p>

        <? } else { ?>

            <p>Thank you. Your account has now been activated.</p>

            <p>Please <a href="<?= $this->url('login') ?>">sign in</a></p>

        <? } ?>

    </div>

</div>
