
<article class="group" role="article">
    <div class="inner">
        <h2>Please check your email.</h2>

        <p>We've sent you a link to <strong><?= $this->escapehtml( $this->email ) ?></strong> that you need to click to verify your email address and activate your account.</p>

        <p>You'll need to use this link within 24 hours, or enter your details again.</p>

        <p>If you haven't received the email within a few minutes, please check your spam, bulk or junk email folder &ndash; it may have been mistakenly blocked by your email system.</p>

        <p>If you've already activated your account, you can <a href="<?= $this->url('login') ?>">sign in now</a>.</p>

    </div>
</article>
