<?php

    $form = $this->formErrorTextExchange($this->form, []);
    $form->setAttribute('class', 'form');

    $email              = $form->get('email');
    $email_confirm      = $form->get('email_confirm');
    $password           = $form->get('password');
    $password_confirm   = $form->get('password_confirm');
    $terms              = $form->get('terms');

    $terms->setOptions( ['label' => 'I agree to the <a href="'  . $this->url("terms") . '" target="_blank">Terms and conditions and privacy policy</a>'] );
    
    $email->setAttributes([
        'id' => 'email',
        'autocomplete' => 'off'
    ]);

    $email_confirm->setAttributes([
        'id' => 'email_confirm',
        'autocomplete' => 'off'
    ])->setOptions( ['label' => 'Re-enter your email address'] );

    $password->setAttributes([
        'id' => 'password',
        'autocomplete' => 'off'
    ]);

    $password_confirm->setAttributes([
        'id' => 'password_confirm',
        'autocomplete' => 'off'
    ]);

    $terms->setAttributes([
        'id' => 'terms',
    ])->setOptions( ['label' => 'I agree to the Terms and conditions and privacy policy'] );;

    $form->prepare();

    //---

    $formLabel = $this->plugin('formLabel');

?>

<?= $this->form()->openTag( $form->setAttribute( 'class', 'account form' ) ); ?>

    <div class="<?= $this->elementGroupClass($form->get('secret')) ?>">
        <?= $this->formElement($form->get('secret')) ?>
    </div>

    <? if (isset($this->error) || count($form->getMessages()) > 0) { ?>
        <div class="validation-summary group" role="alert" aria-labelledby="error-heading" tabindex="-1">
            <h1 id="error-heading">There was a problem creating your account</h1>
            <? if (isset($this->error) ) {
                switch($this->error){
                    case 'address-already-registered':
                        ?><p>This email address has already been registered. Please <a href="<?= $this->url('login'); ?>">sign in</a> or <a href="<?= $this->url('forgot-password'); ?>">reset your password</a>.</p><?
                        break;
                    default:
                        ?><p><?= $this->escapeHtml($this->error) ?></p><?
                }
            } elseif ( count($form->getMessages()) > 0 ) { ?>
                <p>Because of the following problems:</p>
                <ol>
                    <?php $this->formLinkedErrorList($form); ?>
                </ol>
            <? } ?>
        </div>
    <? } ?>

    <p>You need to give your email address and create a password. This is so you can make, save and retrieve LPAs.</p>
    <p>You can create an account in your name to help someone else make an LPA. But they must make all the decisions about the LPA themselves.</p>
    <p>If you already have an account please <a href="<?= $this->url('login') ?>">sign in</a>.</p>

    <fieldset>
        <legend>Email address</legend>

        <div class="group">
            <?= $formLabel->openTag() ?>Enter your email address<?= $formLabel->closeTag(); ?>
            <?= $this->formElement($email) ?>
            <?= $this->formElementErrors($email) ?>
        </div>
        
        
        <div class="group">
            <?= $formLabel->openTag() ?>Re-enter your email address<?= $formLabel->closeTag(); ?>
            <?= $this->formElement($email_confirm) ?>
            <?= $this->formElementErrors($email_confirm) ?>
        </div>
        
    </fieldset>

    <fieldset>
        <legend>Password</legend>
        <p>Your password has to be at least 8 characters long and must contain at least 1 lower-case letter, 1 capital letter and 1 number. Never share your password with anyone.</p>

        <div class="group">
            <?= $formLabel->openTag() ?>Password<?= $formLabel->closeTag(); ?>
            <?= $this->formElement($password) ?>
            <?= $this->formElementErrors($password) ?>
        </div>

        <div class="group">
            <?= $formLabel->openTag() ?>Confirm Password<?= $formLabel->closeTag(); ?>
            <?= $this->formElement($password_confirm) ?>
            <?= $this->formElementErrors($password_confirm) ?>
        </div>

    </fieldset>

    <hr>
    <fieldset>
        <p>LPAs are governed by the laws of England and Wales and can only be made by people with mental capacity aged 18 or older.</p>
      
        <div class="option group">
            <?= $formLabel->openTag() ?>
            <?= $this->formElement($terms) ?>
            <?= $terms->getOption('label') . $formLabel->closeTag(); ?>
            <?= $this->formElementErrors($terms) ?>
        </div>

    </fieldset>

    <p class="action group">
        <input type="submit" name="submit" id="signin-form-submit" value="Sign up" class="button">
    </p>

<?= $this->form()->closeTag(); ?>
