<form action="<?= $this->url('register'); ?>" method="POST" class="account form">

  <p>You need to give your email address and create a password. This is so you can make, save and retrieve LPAs.</p>
  <p>You can create an account in your name to help someone else make an LPA. But they must make all the decisions about the LPA themselves.</p>
  <p>If you already have an account please <a href="/user/login">sign in</a>.</p>

  <fieldset>
    <legend>Email address</legend>
        <div class="group ">
            <label class="required">Email address</label>
            <input type="email" autocomplete="off">
        </div>
        
        <div class="group ">
            <label class="required">Confirm Email address</label>
            <input type="email" autocomplete="off">
        </div>

  </fieldset>

  <fieldset>
    <legend>Password</legend>
    <p>Your password has to be at least 8 characters long and must contain at least 1 lower-case letter, 1 capital letter and 1 number. Never share your password with anyone.</p>
    
         <div class="group">
            <label class="required">Password</label>
            <input type="password" autocomplete="off">
        </div>
        
        <div class="group ">
            <label class="required">Confirm Password</label>
            <input type="password" autocomplete="off">
        </div>
  </fieldset>

  <hr>
  <fieldset>
    <p>LPAs are governed by the laws of England and Wales and can only be made by people with mental capacity aged 18 or older.</p>
    <div class="group ">
      <label for="confirmUnderstanding" id="confirmUnderstanding-label" class="required checkbox"><input type="checkbox" name="confirmUnderstanding" id="confirmUnderstanding" value="1">I agree to the <a href="/terms-and-conditions/" target="_blank">Terms and conditions and privacy policy</a></label>
    </div>
  </fieldset>
      


      	<p class="action group">
    	  <p class="action group">
             <input type="submit" name="submit" id="signin-form-submit" value="Sign up" class="button">
          </p>
        </p>

</form>