<?php $this->layout('layout::default', ['title' => 'Incomplete account details']) ?>

<h1>Oops!</h1>
<h2>This is awkward.</h2>
<p>You need to complete your LPA account details first!</p>
<p>
    You must fill in your account details on the LPA online service before accessing the Admin service.
</p>
<p> Click <a href="https://www.lastingpowerofattorney.service.gov.uk/login">here</a> to sign into your LPA account and complete your details.</p>