#!/bin/bash

AUTO_CREATE="${OPG_LPA_COMMON_S3_ENDPOINT}"

if [ $AUTO_CREATE != "" ]
then
    echo "Auto creating local S3 bucket"
    aws s3api create-bucket --endpoint=${OPG_LPA_COMMON_S3_ENDPOINT} --bucket=${OPG_LPA_COMMON_PDF_CACHE_S3_BUCKET}
fi
exit 0
