services:
  front-app-test:
    volumes:
      - ./service-front:/app
      - ./shared:/shared

  api-app-test:
    volumes:
      - ./service-api:/app
      - ./shared:/shared

  admin-app-test:
    volumes:
      - ./service-admin:/app
      - ./shared:/shared

  pdf-app-test:
    volumes:
      - ./service-pdf:/app
      - ./shared:/shared

  shared-test:
    volumes:
      - ./shared/module:/shared/module
      - ./shared/src:/shared/src
      - ./shared/phpunit.xml:/shared/phpunit.xml
      - ./shared/psalm.xml:/shared/psalm.xml
