<header class="page-header group">
	<hgroup>
	<nav role="navigation" class="progress-indicator group static">
		<ol class="group">
			<li>About you</li>
			<li>Create the LPA</li>
			<li>Sign the LPA</li>
			<li>Register the LPA</li>
			<li class="active">Done</li>
		</ol>
	</nav>
		<h1>Now complete your registration</h1>
	</hgroup>
	</header>
	
		
	<div class="article-container group">
                            <article role="article" class="group">
                            <div class="inner">