        <header class="page-header group" style="margin-left:-2em">
        	<hgroup>
        	<nav role="navigation" class="progress-indicator group static" style="width: 1004px;">
        		<ol class="group" style="display:list-item">
        			<li>About you</li>
        			<li class="active">Create the LPA</li>
        			<li>Sign the LPA</li>
        			<li>Register the LPA</li>
        			<li>Done</li>
        		</ol>
        	</nav>
        		<h1>Create a lasting power of attorney</h1>
        	</hgroup>
        </header>
        	
    	<p>We'll use your answers to the questions that follow to create an LPA that you can save and print, sign and then apply to register. We'll save your LPA as you progress so you don't need to do it all in one go.</p>
	    
        	