<header class="page-header group" style="margin-left:-2em">
	<hgroup>
	<nav role="navigation" class="progress-indicator group static" style="width: 1004px;">
		<ol class="group" style="display:list-item">
			<li>About you</li>
			<li>Create the LPA</li>
			<li class="active">Sign the LPA</li>
			<li>Register the LPA</li>
			<li>Done</li>
		</ol>
	</nav>
		<h1>Next steps</h1>
	</hgroup>
	</header>