<header class="page-header group">
	<hgroup>
	<nav role="navigation" class="progress-indicator group static">
		<ol class="group">
			<li>About you</li>
			<li>Create the LPA</li>
			<li class="active">Registration section</li>
			<li>Sign and post</li>
		</ol>
	</nav>
		<h1>Next steps</h1>
	</hgroup>
	</header>
	
	<div class="article-container group">
                            <article role="article" class="group">
                            <div class="inner">
