<header class="page-header group">
	<hgroup>
	<nav role="navigation" class="progress-indicator group static">
		<ol class="group">
			<li>About you</li>
			<li>Create the LPA</li>
			<li class="active">Sign the LPA</li>
			<li>Register the LPA</li>
			<li>Done</li>
		</ol>
	</nav>
		<h1>Next steps</h1>
	</hgroup>
	</header>
	
	<div class="article-container group">
                            <article role="article" class="group">
                            <div class="inner">
    <p>Need to make changes to your LPA? <a href='<?= $this->url('lpa/instructions',['lpa-id'=>$this->lpa->id]) ?>'>Edit</a> your LPA here</p>
    <br>