<?php
    $form = $this->formErrorTextExchange($this->form, []);
    $form->setAttribute('class', 'form');
    $csrf           = $form->get($form->csrfName());
    
    $when  = $form->get('when');
    $whenValueOptions = $when->getOptions()['value_options'];
    
    $whenValueOptions['now']['label'] = "as soon as it's registered (with my consent)";
    $whenValueOptions['no-capacity']['label'] = "only if I don't have mental capacity";
    
    $whenValueOptions['now'] += [
            'label_attributes' => [
                    'for' => 'now'
            ],
            'attributes' => [
                    'id' => 'now'
            ],
    ];
    $whenValueOptions['no-capacity'] += [
            'label_attributes' => [
                    'for' => 'no-capacity'
            ],
            'attributes' => [
                    'id' => 'no-capacity'
            ],
    ];
    
    $when->setOptions( [ 'value_options' => $whenValueOptions ] );
    
    $submit         = $form->get('submit');
    $submit->setAttributes(['class'=>'button gotonextpart', 'value'=>'Save and continue']);
    
    $formLabel      = $this->plugin('formLabel');
    $form->prepare();
?>

<section id="when-lpa-starts-section" class="section current">
	
	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. When can your LPA be used?</h2>
	
    <div class="accordion-content">
    
		<div class="section-intro">
			<p>If you want help straight away with certain decisions about your property and financial affairs you can say that your LPA can be used as soon as it's registered.</p>
			<p>As long as you have mental capacity your registered LPA can only be used with your consent. You decide how and when it is used. Your attorneys will also be able to use your LPA fully if you don’t have mental capacity in the future.</p>
			<p>Alternatively, you can say that your LPA can only be used if you don’t have mental capacity.</p>
			<p><a href="/help/#topic-when-an-lpa-can-be-used" class="js-guidance" data-journey-click="stageprompt.lpa:help:when-an-lpa-can-be-used">Find out more about your options</a></p>

		</div>
		
		<h3>My LPA can be used:</h3>
		
        <?= $this->form()->openTag($form); ?>
        
        <div class="<?= $this->elementGroupClass($csrf) ?>">
            <?= $this->formElement($csrf) ?>
            <?= $this->formElementErrors($csrf) ?>
        </div>
        
        <div class="emphasised option group">
        
            <?= $this->formRadio($when) ?>
            
            <?= $this->formElementErrors($when) ?>
            
        </div>
        
        
        <div class="accordion-actions">
        <p>
            <?= $this->formElement($submit) ?>
        </p>
        </div>
        
        <?= $this->form()->closeTag(); ?>
        
    </div>
    
</section>