<?php
    $form = $this->formErrorTextExchange($this->form, [
        'type' => [
            "Value is required and can't be empty" => 'Please choose a type of LPA',
         ],
    ]);
    
    $form->setAttribute('class', 'form');
    $csrf        = $form->get($form->csrfName());

    $type        = $form->get('type');
    $typeValueOptions = $type->getOptions()['value_options'];
    $typeValueOptions['property-and-financial']['label'] = 'Property and financial affairs';
    $typeValueOptions['health-and-welfare']['label'] = 'Health and welfare';
    
    $typeValueOptions['property-and-financial'] += [
            'label_attributes' => [
                    'for' => 'property-and-financial',
            ],
            'attributes' => [
                    'id' => 'property-and-financial',
            ],
    ];
    $typeValueOptions['health-and-welfare'] += [
            'label_attributes' => [
                    'for' => 'health-and-welfare',
            ],
            'attributes' => [
                    'id' => 'health-and-welfare',
            ],
    ];
    
    $type->setOptions( ['value_options' => $typeValueOptions] );
    
    $isChangeAllowed = true;
    if(($this->lpa->document instanceof Opg\Lpa\DataModel\Lpa\Document\Document) && (
            $this->lpa->document->donor instanceof Opg\Lpa\DataModel\Lpa\Document\Donor)) {
        $type->setAttributes(['disabled'=>'disabled']);
        $isChangeAllowed = false;
    }
    
    $submit      = $form->get('submit');
    $submit->setAttributes(['class'=>'button gotonextpart', 'value'=>'Save and continue']);
    
    $formLabel   = $this->plugin('formLabel');
    $form->prepare();
?>

<section id="lpa-type-section" class="section current">
	
	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. What type of LPA do you want to create?</h2>
	
    <div class="accordion-content">
    	<div class="section-intro">
    		<p>You can make an LPA to cover either your property and financial affairs, or your health and welfare.</p>
    		<p><a class="js-guidance" href="/guidance/#topic-the-2-types-of-lpa" data-journey-click="stageprompt.lpa:help:the-2-types-of-lpa">Find out about the 2 types of LPA</a></p>
    	</div>
    		    
    	
        <?= $this->form()->openTag($form); ?>
    
            <?= $this->formElement($csrf) ?>
            
            <?= $this->formErrorList(); ?>
            
            <div class="emphasised option group">
                <?= $this->formElement($type)?>
                
                <p class='form-element-errors'>
                    <?= $this->formElementErrors($type) ?>
                </p>
                <?php if($isChangeAllowed == false): ?>
                <p>You cannot change the type of your lasting power of attorney at this stage. If you want to make a <?= ($this->lpa->document->type == Opg\Lpa\DataModel\Lpa\Document\Document::LPA_TYPE_HW)?'Property  and financial affairs':'Health and welfare' ?> LPA based on the current one, click <a href="<?= $this->cloneUrl ?>">here</a>.</p>
                <?php endif;?>
            </div>
    
    		<details>
    			<summary data-journey-click="stageprompt.lpa:help.inline:create/lpa-type:what-if-i-want-to-make-more-than-one-lpa" role="button" aria-expanded="false">What if I want to make more than one LPA?</summary>
    			<p>You'll need to go through this form for each LPA you create.</p>
    			<p>We'll remember names and addresses you add so you don't have to enter them each time.</p>
    			<p>Remember, there’s an application fee for each LPA you register.</p>
    		</details>
    
            <div class="accordion-actions">
				<p>
				<?php if($isChangeAllowed == true): ?>
                    <input type="submit" name="save" value="Save and continue" class="button gotonextpart">
                <?php else:?>
                    <a href='<?=$this->nextUrl ?>' class="button gotonextpart">Continue</a>
                <?php endif;?>
                </p>
            </div>
        
        <?= $this->form()->closeTag(); ?>
    	
    </div>
    
</section>
