<?php
    $csrf       = $form->get('secret');
    $title      = 'LPA Type';
    $this->headTitle($title);
    $form       = $this->form;

    $type       = $form->get('type');

    $submit     = $form->get('submit');
    
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>

<section id="lpa-type" class="section current">
	
	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. What type of LPA do you want to create?</h2>
	
    <div class="accordion-content">
    	<div class="section-intro">
    		<p>You can make an LPA to cover either your property and financial affairs, or your health and welfare.</p>
    		<p><a class="js-guidance" href="/guidance/#topic-the-2-types-of-lpa" data-journey-click="stageprompt.lpa:help:the-2-types-of-lpa">Find out about the 2 types of LPA</a></p>
    	</div>
    		    
    	
        <?= $this->form()->openTag($form); ?>
    
        <div class="<?= $this->elementGroupClass($csrf) ?>">
            <?= $this->formElement($csrf) ?>
            <?= $this->formElementErrors($csrf) ?>
        </div>

            <div class="emphasised option group">
                <?php foreach ($type->getOptions()['value_options'] as $key => $value) : ?>
                    <label for="<?= $key ?>">
                        <input type="radio" name="<?= $type->getName() ?>" id="<?= $key ?>" value="<?= $key ?>" <?= $type->getValue() == $key ? 'checked="checked"' : '' ?>>
                        <?= $value ?>
                    </label>
                <?php endforeach; ?>
            </div>
    
    		<details>
    			<summary data-journey-click="stageprompt.lpa:help.inline:create/lpa-type:what-if-i-want-to-make-more-than-one-lpa" role="button" aria-expanded="false">What if I want to make more than one LPA?</summary>
    			<p>You'll need to go through this form for each LPA you create.</p>
    			<p>We'll remember names and addresses you add so you don't have to enter them each time.</p>
    			<p>Remember, there’s an application fee for each LPA you register.</p>
    		</details>
    
            <div class="accordion-actions">
				<p>
                    <input type="submit" name="save" value="Save and continue" class="button gotonextpart">
                </p>
            </div>
        
        <?= $this->form()->closeTag(); ?>
    	
    </div>
    
</section>