<?php
    $form       = $this->form;
    $csrf       = $form->get('secret');
    $title      = $form->get('name-title');
    $firstname  = $form->get('name-first');
    $lastname   = $form->get('name-last');
    $dob        = $form->get('dob-date');
    $email      = $form->get('email-address');
    $address1   = $form->get('address-address1');
    $address2   = $form->get('address-address2');
    $address3   = $form->get('address-address3');
    $postcode   = $form->get('address-postcode');

    $form->setAttribute('class', 'form js-PersonForm js-PostcodeLookup');
    
    $title->setOptions( ['label' => 'Title'] );
    $firstname->setOptions( ['label' => 'First names'] );
    $lastname->setOptions( ['label' => 'Last names'] );
    $dob->setOptions( ['label' => 'Date of birth'] );
    $email->setOptions( ['label' => 'Email address'] );
    $address1->setOptions( ['label' => 'Address line 1'] );
    $address2->setOptions( ['label' => 'Address line 2'] );
    $address3->setOptions( ['label' => 'Address line 3'] );
    $postcode->setOptions( ['label' => 'Postcode'] );
    
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>

<?php if(isset($this->addTrustCorporationRoute )): ?>
<p>
    <a href="<?= $this->addTrustCorporationRoute ?>">Using a trust corporation?</a>
</p>
<?php endif;?>

<h2 class="header">Edit attorney details</h2>
<?= $this->form()->openTag($form); ?>

<div class="<?= $this->elementGroupClass($csrf) ?>">
    <?= $this->formElement($csrf) ?>
    <?= $this->formElementErrors($csrf) ?>
</div>

<?= $this->formErrorList(); ?>

<fieldset>

<div class="form_element">
    <?= $formLabel->openTag() . $title->getOption('label') . $formLabel->closeTag(); ?>
    <?= $this->formInput($title) ?>
    <?= $this->formElementErrors($title) ?>
</div>

<div class="form_element">
    <?= $formLabel->openTag() . $firstname->getOption('label') . $formLabel->closeTag(); ?>
    <?= $this->formInput($firstname) ?>
    <?= $this->formElementErrors($firstname) ?>
</div>

<div class="form_element">
    <?= $formLabel->openTag() . $lastname->getOption('label') . $formLabel->closeTag(); ?>
    <?= $this->formInput($lastname) ?>
    <?= $this->formElementErrors($lastname) ?>
</div>

<div class="form_element">
    <?= $formLabel->openTag() . $dob->getOption('label') . $formLabel->closeTag(); ?>
    <?= $this->formDate($dob) ?>
    <?= $this->formElementErrors($dob) ?>
</div>


<div class="form_element">
    <?= $formLabel->openTag() . $email->getOption('label') . $formLabel->closeTag(); ?>
    <?= $this->formInput($email) ?>
    <?= $this->formElementErrors($email) ?>
</div>

<div class="form_element">
    <?= $formLabel->openTag() . $address1->getOption('label') . $formLabel->closeTag(); ?>
    <?= $this->formInput($address1) ?>
    <?= $this->formElementErrors($address1) ?>
</div>

<div class="form_element">
    <?= $formLabel->openTag() . $address2->getOption('label') . $formLabel->closeTag(); ?>
    <?= $this->formInput($address2) ?>
    <?= $this->formElementErrors($address2) ?>
</div>

<div class="form_element">
    <?= $formLabel->openTag() . $address3->getOption('label') . $formLabel->closeTag(); ?>
    <?= $this->formInput($address3) ?>
    <?= $this->formElementErrors($address3) ?>
</div>

<div class="form_element">
    <?= $formLabel->openTag() . $postcode->getOption('label') . $formLabel->closeTag(); ?>
    <?= $this->formInput($postcode) ?>
    <?= $this->formElementErrors($postcode) ?>
</div>

</fieldset>

<p class="action group">
<input type="submit" name="submit" id="form-save" value="Save details" class="button"> 
<button name="cancel" id="form-cancel" type="button" class="button-secondary">Cancel</button>
</p>

<?= $this->form()->closeTag(); ?>