<?php
    /**
     * Picker form
     */
    if(isset($this->seedDetailsPickerForm)) {
        $pickerForm   = $this->seedDetailsPickerForm;
        $pickerForm->setAttribute('class', 'form');
        $pickerCsrf   = $pickerForm->get('secret');
        
        $picker = $pickerForm->get('pick-details');
        $picker->setAttributes(['id'=>'pick-details', 'class'=>'js-reusable']);
        $picker->setOptions([
            'label' => 'Use these details',
            'empty_option' => 'Select the trust',
        ]);
        
        $pickerSubmit     = $pickerForm->get('submit');
        $pickerSubmit->setAttributes(['value'=>'Use details', 'class'=>'button']);
        $pickerFormLabel  = $this->plugin('formLabel');
        $pickerForm->prepare();
    }
    
    /**
     * trust corp form
     */
    $form = $this->formErrorTextExchange($this->form, []);
    $csrf       = $form->get('secret');
    $name       = $form->get('name');
    $companyNumber   = $form->get('number');
    $email      = $form->get('email-address');
    $address1   = $form->get('address-address1');
    $address2   = $form->get('address-address2');
    $address3   = $form->get('address-address3');
    $postcode   = $form->get('address-postcode');

    $form->setAttribute('class', 'form js-PersonForm js-PostcodeLookup');
    
    $name->setOptions( ['label' => 'Company name'] );
    $companyNumber->setOptions( ['label' => 'Registration No.'] );
    $email->setOptions( ['label' => 'Email address'] );
    $address1->setOptions( ['label' => 'Address line 1'] );
    $address2->setOptions( ['label' => 'Address line 2'] );
    $address3->setOptions( ['label' => 'Address line 3'] );
    $postcode->setOptions( ['label' => 'Postcode'] );
    
    $submit     = $form->get('submit');
    $submit->setAttributes(['value'=>'Save and continue']);
    
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>

<h2 class="header">Edit trust corporation details</h2>

<?php ############################ trust corp form ############################ ?>

<?= $this->form()->openTag($form); ?>

<?php if(isset($this->useTrustRoute )): ?>
<p class="role-select group">
    <a class="js-form-popup" href="<?= $this->useTrustRoute ?>">Use details of the <?=$this->trustName ?></a>
</p>
<?php endif;?>

<?php if(isset($this->addAttorneyRoute )): ?>
<p class="role-select group">
    <a class="js-form-popup" href="<?= $this->addAttorneyRoute ?>">Using an individual?</a>
</p>
<?php endif;?>

<?= $this->formElement($csrf) ?>
<?= $this->formElementErrors($csrf) ?>

<?= $this->formErrorList(); ?>

<fieldset>

    <div class="form_element">
        <?= $formLabel->openTag() . $name->getOption('label') . $formLabel->closeTag() ?>
        <?= $this->formElement($name) ?>
        <?= $this->formElementErrors($name) ?>
    </div>
    
    <div class="form_element">
        <?= $formLabel->openTag() . $companyNumber->getOption('label') . $formLabel->closeTag() ?>
        <?= $this->formElement($companyNumber) ?>
        <?= $this->formElementErrors($companyNumber) ?>
    </div>
    
    <div class="form_element">
        <?= $formLabel->openTag() . $email->getOption('label') . $formLabel->closeTag() ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors($email) ?>
    </div>

</fieldset>

<fieldset class="js-PostcodeLookup__postal-add">

    <div class="form_element">
        <?= $formLabel->openTag() . $address1->getOption('label') . $formLabel->closeTag() ?>
        <?= $this->formElement($address1) ?>
        <?= $this->formElementErrors($address1) ?>
    </div>
    
    <div class="form_element">
        <?= $formLabel->openTag() . $address2->getOption('label') . $formLabel->closeTag() ?>
        <?= $this->formElement($address2) ?>
        <?= $this->formElementErrors($address2) ?>
    </div>
    
    <div class="form_element">
        <?= $formLabel->openTag() . $address3->getOption('label') . $formLabel->closeTag(); ?>
        <?= $this->formElement($address3) ?>
        <?= $this->formElementErrors($address3) ?>
    </div>
    
    <div class="form_element">
        <?= $formLabel->openTag() . $postcode->getOption('label') . $formLabel->closeTag(); ?>
        <?= $this->formElement($postcode) ?>
        <?= $this->formElementErrors($postcode) ?>
    </div>

</fieldset>

<p class="action group">
<input type="submit" name="submit" id="form-save" value="Save details" class="button"> 
<button name="cancel" id="form-cancel" type="button" class="button-secondary">Cancel</button>
</p>

<?= $this->form()->closeTag(); ?>