
    <section id="help-system">
      <header>
        <p>A guide to making your lasting power of attorney</p>
      </header>
      <nav class="help-navigation">
        <div class="group">
    	    <h2>Help topics</h2>
    		  <ul class="help-topics">
            <li><a class="js-guidance" href="/guidance/#topic-lpa-basics" data-journey="stageprompt.lpa:help:lpa-basics">LPA basics</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-about-this-tool" data-journey="stageprompt.lpa:help:about-this-tool">About this tool</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-the-2-types-of-lpa" data-journey="stageprompt.lpa:help:the-2-types-of-lpa">The 2 types of LPA</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-donor" data-journey="stageprompt.lpa:help:donor">Donor</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-when-an-lpa-can-be-used" data-journey="stageprompt.lpa:help:when-an-lpa-can-be-used">When an LPA can be used</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-life-sustaining-treatment" data-journey="stageprompt.lpa:help:life-sustaining-treatment">Life-sustaining treatment</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-attorneys" data-journey="stageprompt.lpa:help:attorneys">Attorneys</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-how-attorneys-make-decisions" data-journey="stageprompt.lpa:help:how-attorneys-make-decisions">How attorneys make decisions</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-replacement-attorneys" data-journey="stageprompt.lpa:help:replacement-attorneys">Replacement attorneys</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-certificate-providers" data-journey="stageprompt.lpa:help:certificate-providers">Certificate providers</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-people-to-be-told" data-journey="stageprompt.lpa:help:people-to-be-told">People to be told</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-restrictions-and-guidance" data-journey="stageprompt.lpa:help:restrictions-and-guidance">Restrictions and guidance</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-paying-attorneys" data-journey="stageprompt.lpa:help:paying-attorneys">Paying attorneys</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-signing-the-lpa" data-journey="stageprompt.lpa:help:signing-the-lpa">Signing the LPA</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-registering-the-lpa" data-journey="stageprompt.lpa:help:registering-the-lpa">Registering the LPA</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-applicant" data-journey="stageprompt.lpa:help:applicant">Applicant</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-correspondence-address" data-journey="stageprompt.lpa:help:correspondence-address">Correspondence address</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-previous-powers-of-attorney" data-journey="stageprompt.lpa:help:previous-powers-of-attorney">Previous powers of attorney</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-fees-and-reductions" data-journey="stageprompt.lpa:help:fees-and-reductions">Fees and reductions</a></li>

            <li><a class="js-guidance" href="/guidance/#topic-glossary" data-journey="stageprompt.lpa:help:glossary">Glossary</a></li>

          </ul>
        </div>
      </nav>
      <div class="content help-sections">
<article id="topic-lpa-basics"><h1>LPA basics</h1>

<p>A lasting power of attorney (LPA) is a legal document that lets you (the 'donor') choose trusted people ('attorneys') to make decisions on your behalf.</p>

<p>An LPA is mainly used if you don't have the mental capacity to make decisions yourself.</p>

<h3>Mental capacity: definition</h3>

<p>'Mental capacity' means the ability to make a decision. A person with mental capacity has at least a general understanding of the decision they need to make, why they need to make it and the likely consequences. Sometimes people can make some kinds of decision but don't have the mental capacity to make others.</p>

<p>The Ministry of Justice website has <a href="http://www.justice.gov.uk/protecting-the-vulnerable/mental-capacity-act" rel="external" target="_blank">more information about mental capacity</a>.</p>

<p>An LPA helps you control decisions that affect you, even when you cannot make them yourself. An LPA allows you to plan and choose:</p>

<ul>
<li>what decisions you want to be made on your behalf</li>
<li>who will make those decisions</li>
<li>how you want them to make those decisions</li>
</ul>

<p>In an LPA, you are known as the 'donor'. The people you choose to make decisions are called 'attorneys'.</p>

<h2>What an LPA covers</h2>

<p>There are 2 types of LPA:</p>

<h3>Property and financial affairs</h3>

<p>This LPA covers your money and property. You don't have to own your own home or have a lot of money to make this type of LPA. It can be used on your behalf, with your consent, as soon as it's registered. However, you can state that it will only be used if you don't have mental capacity.</p>

<h3>Health and welfare</h3>

<p>This LPA covers your personal and health care. This type of LPA can only be used if you don't have the mental capacity to make decisions yourself.</p>

<p>You can use it to let your attorneys decide about your daily routine, such as what you wear and eat, moving into a care home or getting help from social services. You can also give your attorneys the power to refuse or agree to any medical treatment you may need to stay alive, if ever you are unable to make that decision. If your attorneys don't have that power, doctors would decide.</p>

<p>Some people make 1 LPA, while others make both. You'll find more information about the 2 types of LPA when you're asked to choose which type to make.</p>

<h2>Protecting your interests</h2>

<p>Your attorneys must always act in your best interests and follow any instructions you give them about making decisions. These instructions can include:</p>

<ul>
<li>whether attorneys make all or some decisions together or individually</li>
<li>conditions or restrictions on how attorneys make decisions</li>
</ul>

<p>You can also include guidance to make sure that attorneys' decisions will be similar to the ones you would make.</p>

<p>Your attorneys can only make decisions that you've allowed them to make in your LPA. For example, if your LPA is for your property and financial affairs, your attorneys can't make decisions about your care or where you live. If your LPA is for your health and welfare, they can't make decisions about your money.</p>

<h3>Code of practice</h3>

<p>Attorneys must follow the <a href="https://www.gov.uk/government/publications/mental-capacity-act-code-of-practice" rel="external" target="_blank">Mental Capacity Act Code of Practice</a>. The principles are:</p>

<ol>
<li><p>Your attorneys must assume that you can make your own decisions unless they establish that you can't do so.</p></li>
<li><p>Your attorneys must help you to make as many of your own decisions as you can. They must take all practical steps to help you to make a decision. They can only treat you as unable to make a decision if they have taken those steps without success.</p></li>
<li><p>Your attorneys must not treat you as unable to make a decision simply because you make an unwise decision.</p></li>
<li><p>Your attorneys must act and make decisions in your best interests when you are unable to make a decision.</p></li>
<li><p>Before your attorneys make a decision or act for you, they must consider whether they can achieve the same result without restricting your rights so much.</p></li>
</ol>

<h2>Safeguards</h2>

<p>An LPA can't be used by your attorneys until it's been registered by the Office of the Public Guardian (OPG). Before an LPA is registered, OPG must be sure that:</p>

<ul>
<li>the LPA is legally correct</li>
<li>the LPA has no errors</li>
<li>people have had the opportunity to object if they have concerns</li>
</ul>

<p>OPG can ask the Court of Protection to remove invalid restrictions, guidance or specific words so that an LPA can be registered.</p>

<p>A donor who still has mental capacity can ask OPG to cancel their registered LPA if they change their mind.</p>

<p>OPG protects people who don't have the mental capacity to make decisions for themselves. If someone raises concerns about how an attorney is acting under an LPA, OPG will investigate or work with other organisations to address complaints.</p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-about-this-tool" class="js-guidance" data-journey="stageprompt.lpa:help:about-this-tool">About this tool</a></li>
<li><a href="/guidance/#topic-the-2-types-of-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:the-2-types-of-lpa">The 2 types of LPA</a></li>
<li><a href="/guidance/#topic-donor" class="js-guidance" data-journey="stageprompt.lpa:help:donor">Donor</a></li>
<li><a href="/guidance/#topic-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:attorneys">Attorneys</a></li>
</ul>

</article>
<article id="topic-about-this-tool"><h1>About this tool</h1>

<p>This digital LPA tool helps you make your lasting power of attorney (LPA).</p>

<p>You'll be asked some questions. For each question, you'll need to give some information or make choices. You'll also find links to detailed guidance.</p>

<p>You can stop at any time and save the information you've entered. You may want to do this if you need to think about a decision or discuss your LPA with someone. Sign back in when you're ready to continue.</p>

<p>With this digital tool:</p>

<ul>
<li>you can't complete the whole process online – you need to print and sign your LPA and send it to the Office of the Public Guardian (OPG) to be registered</li>
<li>you can only make an LPA for England and Wales – your LPA may not be recognised in other countries</li>
</ul>

<p>You need to print your completed LPA document so that you and the other people involved can sign it. The law says that an LPA must be a paper document with handwritten signatures or marks.</p>

<p>If you can't sign or make a mark yourself, you can ask someone else to sign on your behalf.</p>

<h2>The 3 steps</h2>

<ol>
<li>Create: make decisions about your LPA, choose the people you want to be involved and print your completed LPA document.</li>
<li><p>Sign: make sure that all the required people sign your LPA document in the correct order. See <a href="/guidance/#topic-signing-the-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:signing-the-lpa">Signing the LPA</a></p></li>
<li><p>Apply to register: fill in more details, pay the application fee and then send the documents to OPG. See <a href="/guidance/#topic-registering-the-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:registering-the-lpa">Registering your LPA</a></p></li>
</ol>

<p>Apply to register your LPA sooner rather than later, in case there are any problems to sort out before it's registered. Your LPA will then be ready to use as soon as you need it.</p>

<h2>Fees</h2>

<p>It costs £110 to register an LPA. Some people qualify for a reduced fee or can pay no fee.</p>

<p>See <a href="/guidance/#topic-fees-and-discounts" class="js-guidance" data-journey="stageprompt.lpa:help:fees-and-discounts">Fees and reductions</a></p>

<p>You can pay by:</p>

<ul>
<li>cheque</li>
<li>WorldPay secure online payment</li>
</ul>

<h2>Before you begin</h2>

<p>You need to make quite a few decisions when you make your LPA. You should think about these decisions in advance. It's important to know how your LPA will work and to talk to the people you want to be involved.</p>

<h3>Questions to ask yourself</h3>

<ul>
<li>Who will be your attorneys? These are the people who act on your behalf under the LPA.</li>
<li>How many attorneys do you need?</li>
<li>Should you have replacement attorneys? These are people who step in if original attorneys can no longer act, so they're a way to protect your LPA.</li>
<li>How should your attorneys make decisions on your behalf? Should they act together or individually, or a mixture of the two?</li>
<li>Do you want any conditions or restrictions on the way your attorneys make decisions?</li>
<li>Do you want to give any guidance to your attorneys about how to make decisions?</li>
<li>Who's the independent person – the certificate provider – who can sign your LPA to confirm that you understand it and no one is forcing you to make it? This person is a safeguard who can raise concerns when you make your LPA.</li>
<li>Are there any 'people to be told' about your LPA when it is about to be registered? These people are a safeguard who can raise concerns about your LPA before it can be used.</li>
</ul>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-lpa-basics" class="js-guidance" data-journey="stageprompt.lpa:help:lpa-basics">LPA basics</a></li>
<li><a href="/guidance/#topic-fees-and-reductions" class="js-guidance" data-journey="stageprompt.lpa:help:fees-and-reductions">Fees and reductions</a></li>
</ul>

</article>
<article id="topic-the-2-types-of-lpa"><h1>The 2 types of LPA</h1>

<p>There are 2 types of LPA. Some people make 1, while others make both.</p>

<h2>Property and financial affairs LPA</h2>

<p>You choose people you trust to make decisions on your behalf about money and financial matters, including:</p>

<ul>
<li>opening, closing and using your bank or building society accounts</li>
<li>claiming, receiving and using your benefits, pensions and allowances</li>
<li>paying household and other bills</li>
<li>buying and selling your house and other property</li>
</ul>

<p>The people you choose to make decisions are known as 'attorneys'. You can have 1 attorney or more.</p>

<p>You don't have to own your own home or have a lot of money to make a property and financial affairs LPA. For example, if it's hard to manage your bank account or bills alone, you may want someone to help.</p>

<p>You can also make a separate LPA for your business affairs if you want different people to make those decisions.</p>

<p>You can choose that your LPA will only be used if you are no longer able to make decisions. Or you can choose that it can be used while you have mental capacity because you want people to help you with your finances.</p>

<h2>Health and welfare LPA</h2>

<p>You choose people you trust to make decisions on your behalf about things such as:</p>

<ul>
<li>giving or refusing consent to particular types of health care, including medical treatment</li>
<li>you staying in your own home and getting help and support from social services</li>
<li>whether you move into residential care and finding a good care home</li>
<li>day-to-day matters such as your diet, dress or daily routine</li>
</ul>

<p>The people you choose to make decisions are known as 'attorneys'. You can have 1 attorney or more.</p>

<p>You must also choose whether your attorneys or your doctors will make decisions if you ever need treatment to stay alive and you aren't capable of deciding.</p>

<p>As a safeguard, a health and welfare LPA can only be used when you don't have the mental capacity to make decisions.</p>

<h2>Health and welfare: other ways to plan</h2>

<p>There are other ways to make your views known and help other people make decisions about your health and welfare.</p>

<h3>Advance statement of your preferences and wishes</h3>

<p>This is a written statement setting out your preferences and wishes for any care you may need in future. This isn't legally binding but the people looking after you have to take what you say into account when they decide about your best interests. NHS Choices website has <a href="http://www.nhs.uk/Planners/end-of-life-care/Pages/advance-statement.aspx" rel="external" target="_blank">information about advance statements.</a></p>

<h3>Care plan</h3>

<p>If you have a long-term health condition, you can create a written care plan with your GP, nurse or social worker that sets out ways of helping you look after yourself on a day-to-day basis. NHS Choices website has <a href="http://www.nhs.uk/Planners/Yourhealth/Pages/Careplan.aspx" rel="external" target="_blank">information about care plans.</a></p>

<h3>Advance decision</h3>

<p>This is a legally binding document that allows you to specify types of treatments that you don't want, in case you aren't able to make a decision about them in the future. NHS Choices website has <a href="http://www.nhs.uk/Planners/end-of-life-care/Pages/advance-decision-to-refuse-treatment.aspx" rel="external" target="_blank">information about advance decisions.</a></p>

<p>If you've made an advance decision, you can still make an LPA. If you want the advance decision to be taken into account, you should state this when you have the opportunity to 'add extra instructions' in the restrictions and conditions section of your LPA. Send a copy of your advance decision to the Office of the Public Guardian (OPG) when you apply to register your LPA.</p>

<p>When making a health and welfare LPA, you'll have to decide whether your attorneys or your doctors should make decisions about life-sustaining treatment. If you let your attorneys decide about life-sustaining treatments that you've previously made an advance decision about, the LPA will take the place of the advance decision.</p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-when-an-lpa-can-be-used" class="js-guidance" data-journey="stageprompt.lpa:help:when-an-lpa-can-be-used">When an LPA can be used</a></li>
<li><a href="/guidance/#topic-life-sustaining-treatment" class="js-guidance" data-journey="stageprompt.lpa:help:life-sustaining-treatment">Life-sustaining treatment</a></li>
<li><a href="/guidance/#topic-restrictions-and-guidance" class="js-guidance" data-journey="stageprompt.lpa:help:restrictions-and-guidance">Restrictions and guidance</a></li>
</ul>

</article>
<article id="topic-donor"><h1>Donor</h1>

<p>The donor is the person who makes the LPA. The registered LPA can be used if the donor loses mental capacity.</p>

<h3>Mental capacity: definition</h3>

<p>'Mental capacity' means the ability to make a decision. A person with mental capacity has at least a general understanding of the decision they need to make, why they need to make it and what is likely to happen when they've made it. People can sometimes make certain decisions but don't have the mental capacity to make others.</p>

<p>The Ministry of Justice website has <a href="http://www.justice.gov.uk/protecting-the-vulnerable/mental-capacity-act" rel="external" target="_blank">information about mental capacity</a>.</p>

<p>An LPA is a legal document that allows you (the donor) to choose people – known as your attorneys – to make decisions for you. You can make an LPA for your property and financial affairs, or your health and welfare. Some people choose to make both.</p>

<p>Only you can give others the power to make decisions on your behalf. This applies whether you get help making your LPA or not.</p>

<h2>Who can be a donor</h2>

<p>An LPA is for 1 person only. You can make an LPA if:</p>

<ul>
<li>you are at least 18 years old</li>
<li>you have the mental capacity to do so</li>
</ul>

<p>It's fine to get help when making your LPA. Many people talk to family, friends or a legal advisor. But you alone must make the decisions about your LPA. For example, no one else should choose your attorneys for you.</p>

<p>Most people can make an LPA. However, there could be complications because of:</p>

<ul>
<li>residency – if you live or have property outside England and Wales</li>
<li>bankruptcy – if you are bankrupt or subject to a debt relief order and want to make an LPA for your property and financial affairs</li>
</ul>

<h3>Residency and property</h3>

<p>LPAs cover people who live or have assets in England and Wales. Your LPA may not work in other countries, including Scotland and Northern Ireland. You should think about getting legal advice if:</p>

<ul>
<li>you live outside England and Wales</li>
<li>you have property outside England and Wales</li>
<li>you're planning to move away from England and Wales</li>
<li>there are other reasons why where you live complicates your situation</li>
</ul>

<h3>Bankruptcy and debt relief orders</h3>

<p>There are rules about bankruptcy and debt relief orders for a property and financial affairs LPA.</p>

<p>If you are bankrupt or subject to a debt relief order, you can make, sign and register a property and financial affairs LPA. However, your attorneys will not have power over all of your property. If this applies to you, you should think about getting legal advice before you make your LPA.</p>

<p>If you become bankrupt or subject to a debt relief order after your property and financial affairs LPA is made or registered, it will be cancelled.</p>

<p>If an attorney becomes bankrupt or subject to a debt relief order, they can no longer be your attorney under your property and financial affairs LPA.</p>

<p>Bankruptcy does not affect a health and welfare LPA.</p>

<h2>Other names</h2>

<p>If you use more than one name or used to be known by a different name, you should make a list of these. This will help your attorneys deal with banks and other organisations on your behalf if your LPA is used.</p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-lpa-basics" class="js-guidance" data-journey="stageprompt.lpa:help:lpa-basics">LPA basics</a></li>
<li><a href="/guidance/#topic-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:attorneys">Attorneys</a></li>
<li><a href="/guidance/#topic-how-attorneys-make-decisions" class="js-guidance" data-journey="stageprompt.lpa:help:how-attorneys-make-decisions">How attorneys make decisions</a></li>
</ul>

</article>
<article id="topic-when-an-lpa-can-be-used"><h1>When an LPA can be used</h1>

<h2>Health and welfare LPA</h2>

<p>A health and welfare LPA takes effect only after it's registered and if you don't have the mental capacity to make decisions. Your attorneys cannot make decisions for you when you can make them yourself.</p>

<h2>Property and financial affairs LPA</h2>

<p>A property and financial affairs LPA usually takes effect when it's registered. You decide whether your attorneys should act on your behalf and in which circumstances. If you don't have mental capacity, your attorneys can act and make decisions on your behalf.</p>

<p>However, you can choose that your property and financial affairs LPA will take effect – and your attorneys will be able to act for you – only when you don't have mental capacity.</p>

<p>Banks and other financial institutions sometimes want written confirmation that a donor does not have mental capacity before they'll recognise an attorney's authority to act under an LPA.</p>

<h3>As soon as it's registered (and also when I don't have mental capacity)</h3>

<p>Choose this option if:</p>

<ul>
<li>you want your attorneys to be able to help you either now or in the future with your property and financial affairs while you have mental capacity</li>
</ul>

<p>If it's difficult to do things, you might want your attorneys to help you. For example, if you can’t leave the house or it’s hard to talk to your electricity supplier, you might ask your attorneys to deal with the bank or pay bills. You can also decide not to let your attorneys make certain decisions, for example, about selling your house.</p>

<p>As long as you have mental capacity, you control your property and financial affairs.</p>

<h3>Only when I don't have mental capacity</h3>

<p>Choose this option if:</p>

<ul>
<li><p>you don't want your attorneys to make decisions on your behalf while you can make them yourself</p></li>
<li><p>you want the security of having the LPA registered and ready to use in case you don't have mental capacity in the future</p></li>
</ul>

<p>After you've chosen this option and filled in the rest of your information, these words will appear in the 'Restrictions and guidance' section of the LPA document that you print:</p>

<blockquote>
  <p>I would like my LPA to take effect only when I don't have capacity to make decisions about my property and financial affairs.</p>
</blockquote>

<p>When you reach the 'Restrictions and guidance' section in this LPA tool, you can add instructions. Some people explain how their mental capacity should be assessed. For example:</p>

<blockquote>
  <p>My attorneys shall only act under this power if they have obtained a written medical opinion stating that I am no longer mentally capable of managing and administering my property and financial affairs.</p>
</blockquote>

<p>or:</p>

<blockquote>
  <p>This lasting power of attorney only applies if my GP or another doctor confirms in writing that I don't have capacity to make specific decisions about property or finances.</p>
</blockquote>

<p>However, if you trust your attorneys to assess your mental capacity, you do not need to add instructions.</p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-registering-the-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:registering-the-lpa">Registering the LPA</a></li>
<li><a href="/guidance/#topic-restrictions-and-guidance" class="js-guidance" data-journey="stageprompt.lpa:help:restrictions-and-guidance">Restrictions and guidance</a></li>
</ul>

</article>
<article id="topic-life-sustaining-treatment"><h1>Life-sustaining treatment</h1>

<p>'Life-sustaining treatment' means care, surgery, medicine or other help from doctors that's needed to keep someone alive.</p>

<p>You can state in your health and welfare LPA what you'd want to happen if you needed life-sustaining treatment and you no longer had mental capacity.</p>

<p>You have 2 options:</p>

<ul>
<li>Option A. Yes. I want to give my attorneys authority to give or refuse consent to life-sustaining treatment on my behalf.</li>
<li>Option B. No. I don’t want to give my attorneys authority to give or refuse consent to life-sustaining treatment on my behalf.</li>
</ul>

<p>If you choose option B it means that doctors will make the decisions about life-sustaining treatment instead of your attorneys.</p>

<p>After you print out your LPA document, you'll have to sign and date the option you've chosen. This must be witnessed.</p>

<p>See <a href="/guidance/#topic-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:attorneys">Attorneys</a> for information on choosing your attorneys.</p>

<h2>Life-sustaining treatment: definition</h2>

<p>Life-sustaining treatment can include:</p>

<ul>
<li>a serious operation, such as heart bypass surgery</li>
<li>chemotherapy, radiotherapy or another cancer treatment</li>
<li>an organ transplant</li>
<li>artificial nutrition or hydration (food or water given other than by mouth)</li>
</ul>

<p>Whether some treatments are life-sustaining depends on the situation. For example, if someone had pneumonia, a simple course of antibiotics could be life-sustaining.</p>

<p>Decisions about life-sustaining treatment can be needed in unexpected circumstances. One example is a routine operation where things don't go as planned. </p>

<h3>Option A: attorneys</h3>

<p>Choose option A if you want your attorneys to decide about life-sustaining treatment if ever you need it and can't make the decisions yourself.</p>

<p>At the end of the LPA tool there is a section where you can add restrictions and guidance for your attorneys. If you have specific wishes about life-sustaining treatment, make them clear in that section, so that any decisions your attorneys make are as close as possible to the decisions you would have made.</p>

<p>You can specify medical or physical conditions where your attorneys must or must not consent to life-sustaining treatment on your behalf. For example, you can state that your attorneys must not agree to life-sustaining treatment if you are in a persistent vegetative state.</p>

<p>If you have already made an 'advance decision' to refuse a specific life-sustaining treatment, your LPA will override the advance decision if you give your attorneys the power to decide about life-sustaining treatment.</p>

<p>An advance decision is a legally binding document in which you state which life-sustaining treatments you don't want, in case you cannot decide at some point.</p>

<p>See <a href="/guidance/#topic-restrictions-and-guidance" class="js-guidance" data-journey="stageprompt.lpa:help:restrictions-and-guidance">Restrictions and guidance</a> for more on giving guidance to your attorneys.</p>

<h3>Option B: doctors</h3>

<p>Choose option B if you want your doctors to decide about life-sustaining treatment if you can't. If the situation arises, they must:</p>

<ul>
<li>carry out an assessment of your best interests</li>
<li>take into account, where possible, the views of your attorneys and other people involved in your welfare</li>
<li>take into account what you have said or written about life-sustaining treatment, including any guidance you've given in your LPA</li>
</ul>

<h3>Making your treatment preferences known</h3>

<p>If you've made an advance decision to refuse treatment that your attorneys or doctors must take into account, you can refer to it when adding 'extra instructions' under the 'restrictions and conditions' section of this LPA tool. You'll also need to include a copy of the decision when you send your LPA to the Office of the Public Guardian (OPG) to be registered.</p>

<p><a href="http://www.nhs.uk/Planners/end-of-life-care/Pages/advance-decision-to-refuse-treatment.aspx" rel="external" target="_blank">NHS Choices has information about advance decisions.</a></p>

<p>You can also let people know your views on treatments and care in:</p>

<ul>
<li>statements of preference</li>
<li>care plans</li>
</ul>

<p>See <a href="/guidance/#topic-the-2-types-of-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:the-2-types-of-lpa">The 2 types of LPA</a> for more information.</p>

<p>There's more about life-sustaining treatment, advance decisions and how health professionals must respond to your written wishes in chapter 9 of the <a href="http://www.justice.gov.uk/protecting-the-vulnerable/mental-capacity-act" rel="external" target="_blank">Mental Capacity Act 2005 Code of Practice</a>.</p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:attorneys">Attorneys</a></li>
<li><a href="/guidance/#topic-restrictions-and-guidance" class="js-guidance" data-journey="stageprompt.lpa:help:restrictions-and-guidance">Restrictions and guidance</a></li>
<li><a href="/guidance/#topic-the-2-types-of-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:the-2-types-of-lpa">The 2 types of LPA</a></li>
</ul>

</article>
<article id="topic-attorneys"><h1>Attorneys</h1>

<p>Attorneys are people you trust and appoint under your LPA to make decisions on your behalf when you don't have mental capacity.</p>

<p>You must have at least 1 attorney. There's no upper limit but too many attorneys could make things difficult, as they'll need to work together.</p>

<p>You should think about replacement attorneys – people who step in if 1 of your original attorneys can no longer act. See <a href="/guidance/#topic-replacement-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:replacement-attorneys">Replacement attorneys</a> for more information.</p>

<h2>Who can be an attorney</h2>

<p>In legal terms, an 'attorney' is a person who's allowed to act on behalf of someone.</p>

<p>Attorneys don't need to be solicitors. Many people choose family members, friends and other people they trust with no legal background. If an attorney is not a professional, the important thing is that you know each other well and they respect your views and  will act in your best interests.</p>

<p>You can ask anyone with mental capacity aged 18 or over to be your attorney, including:</p>

<ul>
<li>your wife, husband, civil partner or partner</li>
<li>a family member</li>
<li>a close friend</li>
<li>a professional, such as a solicitor</li>
</ul>

<p>Make sure that each person agrees to be your attorney before you name them in your LPA.</p>

<p>If you choose your wife, husband or civil partner and your relationship is later legally ended, they will usually have to stop being your attorney. However, you can state in your restrictions that they can continue to be your attorney if your relationship legally ends. If you don't and they are your only attorney, your LPA will be cancelled.</p>

<p>A person who is on the Disclosure and Barring Service barred list can't act as an attorney. They're breaking the law if they do.</p>

<h3>Property and financial affairs LPA attorneys</h3>

<p>An undischarged bankrupt or a person subject to a debt relief order can't be an attorney for a property and financial affairs LPA. If an attorney becomes bankrupt or subject to a debt relief order after the LPA has been registered, they will no longer be able to act.</p>

<p>Bankruptcy and debt relief orders don't affect health and welfare LPAs.</p>

<p>If you appoint a professional attorney for a property and financial affairs LPA, such as a solicitor, you must name an individual. You can't just give a job title or the name of a firm. Professional attorneys usually charge fees.</p>

<h3>Trust corporation</h3>

<p>A trust corporation can be an attorney for a property and financial affairs LPA. A trust corporation manages funds: for example, savings, pensions, investments. It is usually run by a commercial bank or firm of solicitors.</p>

<p>If your finances are complex or you don't have anyone you want to appoint, you might choose a trust corporation. If you're considering this, you should get legal or financial advice.</p>

<p>If you appoint a trust corporation, make sure you use the exact name they operate under in your LPA. You can't appoint more than 1 trust corporation in your LPA.</p>

<h3>Health and welfare LPA attorneys</h3>

<p>An attorney for a health and welfare LPA must be a person. You can have as many attorneys as you need.</p>

<h2>When attorneys can act</h2>

<p>Your LPA can only be used after it's been registered by the Office of the Public Guardian (OPG).</p>

<p>There are different rules about when attorneys can start making decisions on your behalf, depending on:</p>

<ul>
<li>the type of LPA</li>
<li>whether you still have the mental capacity to make decisions</li>
</ul>

<p><a href="/guidance/#topic-when-an-lpa-can-be-used" class="js-guidance" data-journey="stageprompt.lpa:help:when-an-lpa-can-be-used">When an LPA can be used</a> explains the rules for the 2 types of LPA.</p>

<h3>Mental capacity: definition</h3>

<p>'Mental capacity' means the ability to make a decision. A person with mental capacity has at least a general understanding of the decision they need to make, why they need to make it and the likely consequences. Sometimes people can make some kinds of decision but don't have the mental capacity to make others.</p>

<p>The Ministry of Justice website has <a href="http://www.justice.gov.uk/protecting-the-vulnerable/mental-capacity-act" rel="external" target="_blank">more information about mental capacity</a>.</p>

<h2>When attorneys can no longer act</h2>

<p>An attorney can no longer act on your behalf if they:</p>

<ul>
<li>lose mental capacity</li>
<li>decide they no longer want to act as your attorney (known as 'disclaiming their appointment')</li>
<li>were your wife, husband or civil partner but your relationship has legally ended and you've not stated in your LPA restrictions that they can continue</li>
<li>become bankrupt or subject to a debt relief order and were an attorney for a property and financial affairs LPA</li>
</ul>

<p>If you've said that your attorneys must act together for some or all decisions, they will not be able to make those decisions if 1 dies or can no longer act for you for another reason. To protect your LPA, you should consider appointing replacement attorneys.</p>

<p>If you cancel your LPA, your attorneys can no longer act on your behalf.</p>

<h3>Concerns about attorneys</h3>

<p>The Office of the Public Guardian (OPG) does not supervise attorneys. However, If someone believes your attorneys are not acting in your best interests, they can raise concerns with OPG. OPG or other organisations, such as the police or social services, may investigate.</p>

<h3>Questions to ask yourself</h3>

<p>Most donors take some time choosing the best people to be their attorneys. Consider these questions:</p>

<ul>
<li>How many attorneys do you want to appoint?</li>
<li>Are these people willing to act? Have you discussed your LPA fully with them?</li>
<li>Do they understand the role and responsibilities of an attorney?</li>
<li>Do you trust them to act in your best interests?</li>
<li>Do they know you, your beliefs and your preferences well enough to make decisions for you?</li>
<li>Do they have the skills to act under your LPA and do they manage their own affairs well? For example, are they good with money?</li>
<li>Who can be your replacement attorneys?</li>
</ul>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-restrictions-and-guidance" class="js-guidance" data-journey="stageprompt.lpa:help:restrictions-and-guidance">Restrictions and guidance</a></li>
<li><a href="/guidance/#topic-replacement-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:replacement-attorneys">Replacement attorneys</a></li>
</ul>

</article>
<article id="topic-how-attorneys-make-decisions"><h1>How attorneys make decisions</h1>

<p>If you have more than 1 attorney, you must decide whether you want them to make some or all decisions on their own or whether they should agree some or all decisions unanimously. The legal terms are 'severally' and 'jointly'.</p>

<p>Your options are:</p>

<ul>
<li>jointly and severally</li>
<li>jointly</li>
<li>jointly for some decisions, and jointly and severally for other decisions</li>
</ul>

<p>Most people choose jointly and severally because it is the most flexible and practical way for attorneys to make decisions.</p>

<p>Whichever way you appoint your attorneys to act, they must always act in your best interests and make every effort to find out whether you can make a decision before they do.</p>

<p>Each choice is explained below. If you are not sure which option is best for your circumstances, then you can get legal advice.</p>

<h2>Jointly and severally (attorneys act either together or individually)</h2>

<p>Your attorneys can make decisions on your behalf on their own or together.</p>

<p>Any action taken by any attorney alone is as valid as if they were the only attorney. It's up to your attorneys to choose how they make decisions but they must always act in your best interests.</p>

<p>Most people choose this option because:</p>

<ul>
<li>attorneys can make simple or urgent decisions quickly and easily</li>
<li>if an attorney can no longer act, the LPA won't be cancelled</li>
</ul>

<p>It is possible for 1 attorney to make decisions for you without asking your other attorneys.</p>

<p>If you choose this option, you must not say anywhere else in the LPA that certain decisions must be made by:</p>

<ul>
<li>1 particular attorney</li>
<li>some or all of your attorneys</li>
<li>a minimum number of attorneys</li>
</ul>

<p>You can say how you’d like your attorneys to make a particular decision in the guidance section of your LPA. However, they don’t have to follow your guidance.</p>

<p>See <a href="/guidance/#topic-restrictions-and-guidance" class="js-guidance" data-journey="stageprompt.lpa:help:restrictions-and-guidance">Restrictions and guidance</a> for more information.</p>

<h2>Jointly (attorneys agree every decision unanimously)</h2>

<p>Your attorneys must always make all decisions together. They must agree unanimously and they must all sign any relevant documents.</p>

<p>Choose this option if you want your attorneys to agree on every decision, regardless of how large or small it is.</p>

<p>With this option:</p>

<ul>
<li>if your attorneys can’t all agree on a decision, it can’t be made</li>
<li>if your attorneys can’t work together, your LPA won’t work</li>
<li>if 1 attorney can no longer act or dies, your LPA will stop working, unless you’ve appointed replacements</li>
</ul>

<p>If you have appointed replacement attorneys, they all take over if 1 of your original attorneys can no longer act – your original attorneys stop acting for you. This is because the law treats attorneys who act jointly as a single unit.</p>

<h2>Jointly for some decisions, and jointly and severally for other decisions</h2>

<p>Your attorneys must make certain decisions together and agree them unanimously – but they can make other decisions individually.</p>

<p>If you choose this option you must clearly state which decisions your attorneys should make together and agree unanimously: that is, when they should act jointly.</p>

<p>Some people pick this option because they don’t mind their attorneys taking everyday decisions alone but want them to make important decisions together, such as selling a house.</p>

<p>With this option:</p>

<ul>
<li>if your attorneys can’t agree on a joint decision, it can’t be made</li>
<li>if 1 attorney can no longer act or dies, your remaining attorneys won't be able to make any of the joint decisions, unless you’ve appointed replacements</li>
</ul>

<p>If 1 attorney can no longer act and you’ve appointed replacements:</p>

<ul>
<li>the replacement attorneys take over making all joint decisions from your original attorneys</li>
<li>the replacement and remaining original attorneys can make any decisions they’re allowed to make individually</li>
</ul>

<h3>Examples of working jointly for some decisions, and jointly and severally for others</h3>

<p>Property and financial affairs LPA examples:</p>

<blockquote>
  <p>My attorneys must act jointly in relation to decisions about selling or letting my house and may act jointly and severally for everything else.</p>
  
  <p>My attorneys must act jointly in relation to decisions about investments in stocks and shares and may act jointly and severally for everything else.</p>
</blockquote>

<p>In the first example, 'everything else' means all financial decisions apart from selling or letting your house. In the second example, 'everything else' means all money matters apart from investing in stocks and shares.</p>

<p>Health and welfare LPA examples:</p>

<blockquote>
  <p>My attorneys must act jointly in relation to decisions about where I live and may act jointly and severally for everything else.</p>
  
  <p>My attorneys must act jointly in relation to decisions I have authorised them to make about life-sustaining treatment and may act jointly and severally for everything else.</p>
</blockquote>

<p>In both examples, 'everything else' means all decisions about your day-to-day care and medical treatment, except specific life-sustaining treatment decisions.</p>

<h3>Questions to ask yourself</h3>

<ul>
<li>Do you trust each of your attorneys to make decisions in your best interests? If not, are these the right attorneys?</li>
<li>Do your attorneys know what you would decide if you could?</li>
<li>What might stop your attorneys working together? Do they get on? What would happen if they fell out?</li>
<li>Even if your attorneys can make most decisions on their own, are there some big decisions that you want them to agree on?</li>
<li>Do you want your attorneys or replacement attorneys to make all their decisions together and agree everything unanimously?</li>
<li>Are you happy for your attorneys to choose whether they make decisions together or individually?</li>
<li>Do your attorneys understand how you would like them to make decisions?</li>
<li>Do you know what will happen if 1 attorney can't act any more?</li>
<li>Do you want replacement attorneys? They're an important backup if your attorneys have to make some or all decisions together.</li>
</ul>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:attorneys">Attorneys</a></li>
<li><a href="/guidance/#topic-replacement-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:replacement-attorneys">Replacement attorneys</a></li>
<li><a href="/guidance/#topic-restrictions-and-guidance" class="js-guidance" data-journey="stageprompt.lpa:help:restrictions-and-guidance">Restrictions and guidance</a></li>
</ul>

</article>
<article id="topic-replacement-attorneys"><h1>Replacement attorneys</h1>

<p>Replacement attorneys are people you choose to step in if 1 of your original attorneys can no longer make decisions on your behalf.</p>

<p>A replacement attorney will step in if 1 of your attorneys:</p>

<ul>
<li>dies</li>
<li>loses mental capacity</li>
<li>decides they can no longer act on your behalf (known as 'disclaiming their appointment')</li>
<li>was your wife, husband or civil partner but your relationship has legally ended</li>
<li>becomes bankrupt or subject to a debt relief order – this only applies to property and financial affairs LPAs</li>
</ul>

<p>A replacement attorney can't replace another replacement attorney. </p>

<h2>Who can be a replacement attorney</h2>

<p>A replacement attorney must meet the same requirements as an original attorney. This includes having mental capacity and being 18 or over when you sign your LPA. See <a href="/guidance/#topic-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:attorneys">Attorneys</a> help topic for more on the requirements.</p>

<p>A person who is on the Disclosure and Barring Service barred list can't act as a replacement attorney. They're breaking the law if they do.</p>

<h2>Protecting your LPA</h2>

<p>Having replacement attorneys means that your LPA should still work if an original attorney can no longer act on your behalf.</p>

<p>Without replacements:</p>

<ul>
<li>if you have only 1 attorney and that attorney can no longer act for you, your LPA will no longer work</li>
<li>if you have attorneys who must make all or some decisions together ('jointly') and 1 attorney can no longer act, the rest will not be able to make those joint decisions</li>
</ul>

<p>If your LPA can't be used and you don't have mental capacity, someone you know will have to apply to the Court of Protection to get the power to act on your behalf – this can be expensive and take a long time.</p>

<h2>When a replacement attorney steps in</h2>

<p>A replacement attorney can only act if the original attorney they're replacing is permanently unable to make decisions for 1 of the reasons above.</p>

<p>A replacement attorney:</p>

<ul>
<li>can't temporarily stand in for an attorney who is still able to act (for example, while the first attorney is on holiday)</li>
<li>can't replace a replacement attorney</li>
</ul>

<p>If your attorneys have to make all or some decisions jointly and 1 can no longer act, your replacement attorneys make those joint decisions instead. Both your remaining original attorneys and your replacements can make any decisions that don't have to be made jointly.</p>

<p>Replacement attorneys usually step in as soon as 1 of your original attorneys stops acting for you. If you include more than 1 replacement attorney in your LPA, they all start at the same time, unless you've:</p>

<ol>
<li>Appointed your attorneys to act jointly and severally.</li>
<li>Stated the order in which your original attorneys will be replaced.</li>
</ol>

<h2>Stating an order</h2>

<p>You can only state an order if your attorneys act jointly and severally. You can only state an order for replacing original attorneys.</p>

<h3>Examples:</h3>

<blockquote>
  <p>If one of my attorneys (my mother and father) can no longer act, I would like that attorney to be replaced by my sister. If later on my other parent can no longer act, I would like my brother to step in to replace that person as my attorney.</p>
  
  <p>If my attorney Dave Smith becomes unable to act under this LPA, I want replacement attorney Jane Hall to step in and act in his place.</p>
</blockquote>

<h2>Replacement attorney examples</h2>

<blockquote>
  <p>You choose your husband as your attorney. You appoint your best friend as a replacement attorney in case your husband dies before you or can no longer act for another reason.</p>
  
  <p>You choose 2 attorneys. You appoint a replacement who can step in and work with 1 of the attorneys if the other can no longer act. (If your attorneys must make any or all decisions jointly, the remaining original attorney won't be able to make those decisions. The replacement will replace both original attorneys for the joint decisions.)</p>
  
  <p>You choose your wife and adult son as attorneys. You appoint your 3 grandchildren, who are all over 18, as replacement attorneys. You don't state an order, so all 3 will step in if 1 of your original attorneys can no longer act.</p>
</blockquote>

<h2>Questions to ask yourself</h2>

<ul>
<li>Do you want replacement attorneys in case your original attorneys can no longer act? How many?</li>
<li>Would it be better to choose several attorneys to act jointly and severally instead of just 1 attorney?</li>
<li>Do the people you're considering as replacement attorneys understand that it may be years before they'll need to act for you, if at all?</li>
<li>Would you want new attorneys to replace original ones in a particular order? (This is only possible if you have said that attorneys should make decisions jointly and severally.)</li>
</ul>

<p>You need to choose your replacements as carefully as your original attorneys.</p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:attorneys">Attorneys</a></li>
<li><a href="/guidance/#topic-how-attorneys-make-decisions" class="js-guidance" data-journey="stageprompt.lpa:help:how-attorneys-make-decisions">How attorneys make decisions</a></li>
</ul>

</article>
<article id="topic-certificate-providers"><h1>Certificate providers</h1>

<p>A certificate provider is an impartial person who confirms that you understand what you're doing and that nobody is forcing you to make an LPA.</p>

<p>If you name 'people to be told', you need 1 certificate provider.</p>

<p>If you don't name 'people to be told', you need 2 certificate providers.</p>

<p><a href="/guidance/#topic-people-to-be-told" class="js-guidance" data-journey="stageprompt.lpa:help:people-to-be-told">People to be told</a> help topic has more information.</p>

<h2>A certificate provider's role</h2>

<p>A certificate provider is a safeguard. They help to make sure that all's well when you make your LPA. They must confirm that:</p>

<ul>
<li>you understand the significance of the LPA</li>
<li>you have not been put under pressure to make it</li>
<li>there has been no fraud involved in making the LPA</li>
<li>there is no other reason for concern</li>
</ul>

<p>If possible, they should discuss your LPA with you in private, without attorneys or other people present, before they sign to 'certify' their part of the LPA.</p>

<h2>Who can be a certificate provider</h2>

<p>A certificate provider must be 18 or over and either:</p>

<ul>
<li>someone who has known you well personally for at least 2 years, or</li>
<li>someone with the relevant professional skills and expertise to be able to confirm the things listed above</li>
</ul>

<p>'People to be told' can be certificate providers.</p>

<h3>Someone who has known you well for at least 2 years</h3>

<p>If you want someone who has known you well for at least 2 years, you should ask a friend or neighbour, someone you know at a social or sports club, a work colleague, or similar.</p>

<p>They must be more than an acquaintance. They have to know you well enough to have an honest conversation with you about making your LPA and about the things they have to confirm when they sign the LPA.</p>

<h3>Someone with relevant professional skills</h3>

<p>If you want to choose someone with relevant professional skills, they must be one of the following:</p>

<ul>
<li>a registered healthcare professional, such as your GP</li>
<li>a solicitor, barrister or advocate</li>
<li>a registered social worker</li>
<li>an independent mental capacity advocate (IMCA)</li>
<li>someone else with professional skills that enable them to judge whether you can make the decisions you need to make for your LPA</li>
</ul>

<p>If you choose a professional, ask what fee they charge. </p>

<h2>People who can't be certificate providers</h2>

<p>The certificate provider must not be:</p>

<ul>
<li>an attorney or replacement attorney for the LPA</li>
<li>an attorney or replacement attorney in any other LPA or enduring power of attorney (EPA) that you have already made</li>
<li>a member of your or your attorneys' families, including wives, husbands, civil partners, in-laws and step-relatives</li>
<li>an unmarried partner, boyfriend or girlfriend of yours or of any of your attorneys (whether or not they live at the same address)</li>
<li>your business partner or an attorney's business partner</li>
<li>your employee or an attorney's employee</li>
<li>an owner, manager, director or employee of a care home where you live, or a member of their family</li>
<li>anyone running or working for a trust corporation appointed as an attorney in this LPA</li>
<li>any other person the Court of Protection may consider is not sufficiently independent</li>
</ul>

<h2>Explaining how the person is qualified</h2>

<p>When you fill in the digital form you'll be asked to tick one of the following to explain how the certificate provider knows you:</p>

<blockquote>
  <p>I'd rather they filled in this part of the LPA themselves</p>
  
  <p>They have known me well personally for at least 2 years</p>
  
  <p>They have relevant professional skills and expertise</p>
</blockquote>

<p>If you pick the second or third option, the details must be written in 1 of the text boxes provided. The certificate provider must sign this part of the completed LPA document when it is printed.</p>

<p>If you pick the first option, the certificate provider will fill in these details on the LPA document when they sign it.</p>

<h3>Details to write in the box</h3>

<p>If they know you well personally, clearly state how: for example, "friend", "neighbour" or "colleague".  This is more important than stating how many years they have known you. It's a common mistake to say something like: "I've known the donor for 20 years." This doesn't explain your relationship.</p>

<p>The certificate provider must sign this statement on the printed LPA, so you must write it from their point of view: for example, "I have been a colleague of the donor for 3 years" or "I've lived next door to [your name] for 8 years."</p>

<p>If they have relevant professional skills and experience, state what they are. If they have relevant specialist training or experience as part of their profession, state that as well.</p>

<p>They have to this sign this statement on the printed LPA, so you must write it from the certificate provider's point of view: for example, "I am an Independent Mental Health Advocate, certified by the Department of Health."</p>

<h3>Questions to ask yourself</h3>

<ul>
<li>Has the person known you well for at least 2 years?</li>
<li>If the person does not know you well personally, do they have the professional skills to make a judgement about your ability to make an LPA?</li>
<li>Is the person not allowed to be a certificate provider because they have a close working relationship with or are related to you or 1 of your attorneys?</li>
<li>Have you named any 'people to be told'? (If not, remember that you'll need 2 certificate providers instead of 1.)</li>
</ul>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-people-to-be-told" class="js-guidance" data-journey="stageprompt.lpa:help:people-to-be-told">People to be told</a></li>
<li><a href="/guidance/#topic-signing-the-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:signing-the-lpa">Signing the LPA</a></li>
<li><a href="/guidance/#topic-registering-the-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:registering-the-lpa">Registering the LPA</a></li>
</ul>

</article>
<article id="topic-people-to-be-told"><h1>People to be told</h1>

<p>You can choose 'people to be told' who will be notified when you or your attorneys apply to register your LPA.</p>

<h2>Why tell people?</h2>

<p>Letting people know about your LPA when it's about to be registered provides extra security. It gives people who know you well a chance to raise concerns.</p>

<p>This safeguard is especially important if there's a long time between making your LPA and registering it.</p>

<p>However, you don't have to choose 'people to be told'. If you don't, you'll need 2 people – known as certificate providers – instead of 1, to confirm that you've made the LPA of your own free will. See <a href="/guidance/#topic-certificate-providers" class="js-guidance" data-journey="stageprompt.lpa:help:certificate-providers">Certificate providers</a> for more information.</p>

<h2>Choose 'people to be told'</h2>

<p>You can choose up to 5 people to be told but they can't be your attorneys or replacement attorneys. Many donors choose family members or close friends.</p>

<p>Talk to the people before you name them and explain that:</p>

<ul>
<li>they don't have to do anything right away</li>
<li>they will only be told when you or your attorneys apply to register your LPA</li>
<li>they do not have to do anything when they are contacted, unless they have concerns</li>
</ul>

<h2>How people are told</h2>

<p>Just before you apply to register your LPA, you must send each of the 'people to be told' a form (LPA001) to let them know about it. If your attorneys apply to register your LPA, they must do the same. You can download this form when you apply to register the LPA with this tool.</p>

<p>The form sets out reasons why people can object and how to object.</p>

<h2>Where there are no concerns</h2>

<p>If the 'people to be told' have no concerns, they don't have to do anything.</p>

<h2>Where there are reasons to object to the LPA</h2>

<p>If a 'person to be told' wants to raise concerns about your LPA, they have 3 weeks to object to the Office of the Public Guardian (OPG) from the date they were notified.</p>

<p>There are rules about the sort of concerns people can raise. They can't object to your LPA simply because they don't like it. People can only object to an LPA being registered on 'factual grounds' or 'prescribed grounds'.</p>

<h3>Factual grounds</h3>

<p>A 'person to be told' can object to an LPA's registration if:</p>

<ul>
<li>you or an attorney has died</li>
<li>you and an attorney were married or had a civil partnership and your relationship has legally ended</li>
<li>an attorney doesn't have the mental capacity to be an attorney</li>
<li>an attorney has decided to stop acting (known as 'disclaiming their appointment')</li>
<li>you or an attorney are bankrupt, interim bankrupt or subject to a debt relief order (this only applies to property and financial affairs LPAs)</li>
</ul>

<h3>Prescribed grounds</h3>

<p>A 'person to be told' can object to an LPA's registration if:</p>

<ul>
<li>the power meant to be created by the LPA is not valid – for example, if they don't believe you had the capacity to make an LPA</li>
<li>the power created by the LPA no longer exists – if you, the donor, revoked it at a time when you had mental capacity</li>
<li>there was fraud or undue pressure on you to make the LPA</li>
<li>an attorney proposes to behave in a way that would go beyond their power under your LPA or would not be in your best interests</li>
</ul>

<h3>Questions to ask yourself</h3>

<ul>
<li>Do you want anyone to be told when you or your attorneys apply to register my LPA?</li>
<li>Have you discussed what's involved with your 'people to be told'?</li>
<li>Do they understand why you want to name them and what will happen if an application to register your LPA is made?</li>
<li>Are they happy to be named in your LPA?</li>
</ul>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-certificate-providers" class="js-guidance" data-journey="stageprompt.lpa:help:certificate-providers">Certificate providers</a></li>
<li><a href="/guidance/#topic-registering-the-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:registering-the-lpa">Registering the LPA</a></li>
</ul>

</article>
<article id="topic-restrictions-and-guidance"><h1>Restrictions and guidance</h1>

<p>You can place conditions and restrictions on your attorneys and give them guidance but you don't have to. If you leave this blank, your attorneys will be free to make decisions they think are right.</p>

<p>Complicated or badly written restrictions and guidance can make an LPA unworkable. The Office of the Public Guardian (OPG) might not register it or the Court of Protection might need to change it. If it goes to the court, the restrictions will be 'severed', which means removed from the LPA. This can take a long time.</p>

<p>If you're not sure about what you can put in this section of your LPA, you might want to get legal advice.</p>

<h3>Restrictions and conditions: definition</h3>

<p>These are things your attorneys must or must not do when making decisions for you.</p>

<h3>Guidance: definition</h3>

<p>This means things you'd like your attorneys to think about when acting under your LPA: your wishes, beliefs and preferences. Your attorneys don't have to follow guidance but they should keep it in mind when making decisions for you.</p>

<h2>Restrictions and conditions</h2>

<p>Use words such as 'must', 'shall' and 'have to' if you write restrictions or conditions.</p>

<h3>Property and financial affairs LPA</h3>

<p>You can add restrictions or conditions about, for instance, managing your bank account or seeking professional advice about your tax.</p>

<p>Workable examples:</p>

<blockquote>
  <p>My attorneys must continue to make donations to charities that I have previously supported or for which I have set up standing order payments.</p>
  
  <p>My attorneys must not make any gifts.</p>
  
  <p>My attorneys must not sell my home unless, in my doctor's opinion, I can no longer live independently.</p>
  
  <p>My attorneys must send annual accounts to my brothers and sisters.</p>
  
  <p>My attorneys must instruct a tax accountant to prepare my annual tax return.</p>
</blockquote>

<h3>Health and welfare LPA</h3>

<p>You can add restrictions or conditions about, for instance, medical treatment that fits with your beliefs.</p>

<p>Workable examples:</p>

<blockquote>
  <p>My attorneys must ensure that I am fed a vegan diet with no animal products.</p>
  
  <p>I consent to the disclosure to my attorneys of all relevant information concerning me.</p>
  
  <p>My attorneys must not consent to any medical treatment involving blood products, as this is against my religion.</p>
  
  <p>My attorneys must not decide that I am to move into residential care unless my doctor says that I can no longer live independently.</p>
</blockquote>

<p>These are just a few examples. Don't add any that aren't right for you. You can make restrictions and conditions about other things that matter to you.</p>

<h2>Guidance</h2>

<p>Avoid words such as 'must' and 'shall'. Instead use words such as 'prefer' and 'would like', so it is clear that you are giving your attorneys advice but not instructions. If you definitely want your attorneys to do something, include it in the restrictions and conditions.</p>

<h3>Property and financial affairs LPA</h3>

<p>You can add guidance about how you'd like, for instance, your bank accounts or tax to be managed.</p>

<p>Workable examples:</p>

<blockquote>
  <p>I would like to maintain a minimum balance of £1,000 in my current account.</p>
  
  <p>I prefer to invest in ethical funds.</p>
  
  <p>I would like my attorneys to consult my doctor if they believe I may not have mental capacity to make decisions about my house.</p>
  
  <p>I would like to donate £100 each year to Age UK.</p>
</blockquote>

<h3>Health and welfare LPA</h3>

<p>You can add guidance, for instance, about where you'd like to live and who you'd prefer to look after you.</p>

<p>You don’t have to give any guidance. If your attorneys understand your beliefs and values, you may feel there is no need for further guidance in the LPA.</p>

<p>Workable examples of guidance</p>

<blockquote>
  <p>I prefer to live within 5 miles of my sister.</p>
  
  <p>I prefer to be prescribed generic medicine whenever possible.</p>
  
  <p>I would like to take exercise at least 3 times a week whenever I am physically able to do so.</p>
  
  <p>My attorneys should consult my family when making decisions about life-sustaining treatment.</p>
</blockquote>

<p>The last of these only applies if you allow your attorneys to decide about life-sustaining treatment.</p>

<h2>Avoiding problems</h2>

<p>There are things you can't make your attorneys do. If you would like your attorneys to do something that you are not allowed to include as a restriction, you may be able to include it as guidance instead.</p>

<h3>Contradictions</h3>

<p>Don't appoint attorneys to make decisions in 1 way, then include a restriction that makes them act differently.</p>

<p>If you have stated that your attorneys should act jointly – so they must agree unanimously on every decision – you can't add that if 1 dies, the others can continue to act.</p>

<p>If you have stated that your attorneys must act jointly and severally – so they can make any decision on your behalf on their own or together – you must not add these sort of restrictions and conditions:</p>

<ul>
<li>that 1 attorney has to do what another attorney says</li>
<li>that 1 attorney must deal with your business and another with your private affairs</li>
<li>that where attorneys disagree, the majority should decide</li>
<li>that they must make some decisions together – you should appoint them to act 'jointly for some decisions, and jointly and severally for other decisions' instead if this is what you want</li>
</ul>

<p>These restrictions will not work.</p>

<h3>Gifts</h3>

<p>Instructions about gifts often cause problems. There are strict limits on the kinds of gifts that attorneys can give on your behalf. They can give presents on 'customary occasions', including weddings, birthdays and religious holidays. They can donate to charities you’ve previously given to. Any gifts should be 'reasonable' and take into account how much money you have.</p>

<p>You can't authorise attorneys to go beyond these limits. Here are types of gifts you can't authorise:</p>

<ul>
<li>gifts intended to reduce inheritance tax liability</li>
<li>trust funds for grandchildren</li>
<li>payment of school fees for grandchildren</li>
<li>interest-free loans to family</li>
<li>maintenance for any family member other than your wife, husband, civil partner or child under 18</li>
</ul>

<p>Your attorneys must apply to the Court of Protection if they want to make gifts like this on your behalf.</p>

<h3>Other mistakes</h3>

<p>You should avoid these common mistakes:</p>

<ul>
<li>You can't tell your attorneys to do anything against the law – this includes anything to do with euthanasia and assisted suicide.</li>
<li>You can't say that attorneys should act in the best interests of your wife, husband, partner or children. Your attorneys act for you, not anyone else.</li>
<li>You can't say a replacement attorney can only start acting in specific circumstances – see <a href="/guidance/#topic-replacement-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:replacement-attorneys">Replacement attorneys</a> for more information. For instance, you can't use restrictions to add special circumstances – such as an original attorney being on holiday – in which your replacement attorney can step in.</li>
<li>Don’t add health and welfare restrictions to a property and financial affairs LPA. Don't add property and financial restrictions to a health and welfare LPA. You should make a separate LPA for each instead.</li>
<li>You can't tell an attorney to change your will – it's outside their powers.</li>
<li>You can't give an attorney power to appoint a replacement attorney.</li>
</ul>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-how-attorneys-make-decisions" class="js-guidance" data-journey="stageprompt.lpa:help:how-attorneys-make-decisions">How attorneys make decisions</a></li>
<li><a href="/guidance/#topic-life-sustaining-treatment" class="js-guidance" data-journey="stageprompt.lpa:help:life-sustaining-treatment">Life-sustaining treatment</a></li>
</ul>

</article>
<article id="topic-paying-attorneys"><h1>Paying attorneys: fees and expenses</h1>

<p>Leave this box empty if your attorneys won't be paid or will only get expenses.</p>

<p>Many attorneys don't get fees. For example, if you appoint your husband, wife, partner, a family member or a friend, they may be happy to act on your behalf without being paid. However, many professional attorneys, such as solicitors or accountants, charge for their services.</p>

<p>Fees are paid out of your funds.</p>

<p>You can set different fees for different attorneys. For non-professional attorneys, these are often set as a payment each year.</p>

<p>If you agree to pay a fee to a non-professional, it must be specified here – if you don't, your attorney can't be paid.</p>

<h3>Expenses</h3>

<p>Whether they are paid fees or not, all attorneys can claim reasonable out-of-pocket expenses, such as postage, travel costs and the cost of an accountant preparing annual accounts. Expenses, like fees, are paid out of your funds. Don't write anything here if your attorneys will only get expenses, not fees.</p>

<h3>Examples of setting fees</h3>

<p>Here's how you might fill in this section if you have non-professional attorneys:</p>

<blockquote>
  <p>I wish each of my attorneys to be paid £[fill in the amount here that you want to pay your attorneys] per year for their services under this LPA.</p>
</blockquote>

<p>You can set a professional attorney's fee by referring to standard rates:</p>

<blockquote>
  <p>I wish my professional attorneys to be paid the standard solicitor rate as set by [state the name of a relevant professional organisation here].</p>
</blockquote>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-attorneys" class="js-guidance" data-journey="stageprompt.lpa:help:attorneys">Attorneys</a></li>
<li><a href="/guidance/#topic-how-attorneys-make-decisions" class="js-guidance" data-journey="stageprompt.lpa:help:how-attorneys-make-decisions">How attorneys make decisions</a></li>
</ul>

</article>
<article id="topic-signing-the-lpa"><h1>Signing the LPA</h1>

<p>The people involved in the LPA must sign it in the correct order. If they don't, the Office of the Public Guardian (OPG) won't register it and your attorneys will not be able to use it.</p>

<h3>Order of signing</h3>

<p>The LPA must be signed in this order:</p>

<ol>
<li>Donor.</li>
<li>Donor's witness.</li>
<li>Certificate provider(s).</li>
<li>Attorney(s) and any replacement attorney(s).</li>
<li>Attorneys' witness(es).</li>
</ol>

<h3>Donor</h3>

<p>You (the donor) must sign your LPA before anyone else.</p>

<p>You must sign:</p>

<ul>
<li>part A</li>
<li>any continuation sheets (numbered A1 or A2)</li>
<li>the statement about life-sustaining treatment on page 6, if it is a health and welfare LPA</li>
</ul>

<p>An independent witness must then sign. Your signatures must be made and witnessed on the same date. </p>

<p>If you can't sign the document, there will be an extra sheet with the LPA (continuation sheet A3) that someone must sign for you. You must be present and must tell the person to sign. Two witnesses must watch when continuation sheet A3 is signed.</p>

<h3>Certificate provider(s)</h3>

<p>The certificate provider(s) must sign part B next.</p>

<p>If there are 2 certificate providers, the second must sign continuation sheet B.</p>

<p>Certificate providers can sign in any order. They should sign as soon as possible after the donor - they can sign on the same day but must sign within a year. </p>

<h3>Attorneys and replacement attorneys</h3>

<p>Attorneys and replacement attorneys must then sign part C of your LPA. They can sign in any order.</p>

<p>Their signatures must be witnessed. You (the donor) can't be a witness but your attorneys can be witnesses for each other.</p>

<p>Attorneys and replacements should sign as soon as possible after the certificate providers. They can sign on the same day and must sign within a year.</p>

<h3>Witnesses</h3>

<p>Witnesses are impartial people aged at least 18 years who watch you and your attorneys (including any replacements) sign your LPA. Witnesses must then sign the LPA to confirm that they saw you and your attorneys sign it. </p>

<p>Your (the donor's) witness can't be:</p>

<ul>
<li>1 of your attorneys</li>
<li>1 of your replacement attorneys</li>
<li>an employee of a trust corporation that you've named as an attorney or replacement attorney</li>
</ul>

<p>The same person can witness both donor and attorney signatures, so long as they are not 1 of your attorneys. But you don’t have to use the same witness for all signatures.</p>

<h3>Confirming the dates</h3>

<p>You'll need to confirm the order of signing when you apply to register the LPA using this digital tool. It will ask for the dates that the donor, certificate providers and attorneys signed the LPA document.</p>

<p>If you notice that the dates are not in the correct order, then you must print the document again and have the relevant people sign it in the correct order before you attempt to register the LPA.</p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-registering-the-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:registering-the-lpa">Registering the LPA</a></li>
</ul>

</article>
<article id="topic-registering-the-lpa"><h1>Registering the LPA</h1>

<p>You can apply to register the LPA when you have filled in and printed the LPA document and you, your certificate provider(s), your attorneys and the witnesses have signed it.</p>

<p>To apply to register the LPA:</p>

<ol>
<li>Using this tool, complete a registration form (this form, the LPA002, is different from the LPA itself).</li>
<li>Pay the application fee online or by cheque.</li>
<li>Print and sign the form.</li>
<li>Send it to the Office of the Public Guardian (OPG) with the signed LPA document.</li>
</ol>

<p>Don't make any changes to the LPA document after you've signed it. That could make it invalid, so you'd have to print it again and get everyone to sign it again.</p>

<p>Before you register, this digital tool will ask you questions about things such as signing and notification dates to make sure everything is correct.</p>

<p>Once that's done, you can pay the £110 application fee online or by cheque. If you get means-tested benefits or have a low income, you may be able to pay less or no fee. <a href="/guidance/#topic-fees-and-reductions" class="js-guidance" data-journey="stageprompt.lpa:help:fees-and-reductions">Fees and reductions</a> has more information.</p>

<p>Once you've paid:</p>

<ol>
<li>Print the registration form (LPA002). The tool will have automatically filled it in for you.</li>
<li>Sign the form.</li>
<li>Send it with your signed LPA document to the OPG.</li>
</ol>

<p>OPG will check the LPA to make sure there are no errors. It will then register and stamp your LPA and return it to you. This takes between 8 and 10 weeks.</p>

<h2>Why you should register your LPA</h2>

<p>Your attorneys can only use your LPA to make decisions on your behalf after OPG has registered it and sent it back to you officially stamped.</p>

<p>If you register your LPA as soon as it is signed, OPG can spot mistakes while they can still be changed. If there are any errors, you may have to make all or part of the LPA again. You can only do that if you still have mental capacity. However, you don't have to register your LPA straight away.</p>

<p>If you no longer have mental capacity, your attorneys can apply to register your LPA – however, it won't be possible to correct any errors. If there are mistakes, OPG can't register the LPA and the LPA can't be used. Your attorneys – or someone else – will have to apply to the Court of Protection to get the power to make decisions on your behalf or get a declaration that the LPA can be treated as valid. This can be a long process and can cost a lot more than an LPA.</p>

<h3>The information you'll need to fill in</h3>

<p>This registration tool will ask you:</p>

<ul>
<li>who is applying to register the LPA – this will be you (the donor) or at least 1 of the attorneys</li>
<li>the correspondence address – give details of where OPG should write or phone while your application is processed</li>
<li>the dates the LPA was signed – give the dates when you, the certificate provider(s) and attorneys signed the printed LPA document</li>
<li>the dates you notified your 'people to be told' – if you named 'people to be told' when making your LPA, then you must send them the notification forms before you apply to register</li>
<li>other powers of attorney – give details of any enduring power of attorney (EPA) or registered LPA that you've made as a donor</li>
</ul>

<p>The rest of the details will be completed automatically for you.</p>

<h3>Print it, sign it and send it</h3>

<p>Once you've filled everything in, print out the registration form and sign it.</p>

<p>You need a PDF reader like Adobe Reader (<a href="http://www.adobe.com/uk/products/reader.html" rel="external" target="_blank">http://www.adobe.com/uk/products/reader.html</a>) to view and print the LPA forms.</p>

<p>Send the following documents to OPG:</p>

<ol>
<li>the signed LPA document. You must include pages 1 and 2, which are important parts of the form, and any continuation sheets that have been printed and signed.</li>
<li>The signed 'Application to register a lasting power of attorney' form (LPA002). You can download this when you have answered the questions.</li>
</ol>

<p>If you want to apply to pay lower or no application fees, you must include:</p>

<ol>
<li>The signed 'Application for exemption or remission of EPA/LPA application to register fees' form (LPA120A). You can download this at the same time as you download the application to register form.</li>
<li>Proof that you should pay less or don't have to pay at all.</li>
</ol>

<p>See <a href="/guidance/#topic-fees-and-reductions" class="js-guidance" data-journey="stageprompt.lpa:help:fees-and-reductions">Fees and reductions</a> to find out if you can pay less.</p>

<h3>What happens when OPG gets your LPA?</h3>

<p>If you (the donor), are applying to register the LPA, OPG lets the attorneys know about the application. If an attorney is applying, OPG tells you and any other attorneys.</p>

<p>OPG then processes the LPA and holds it for at least 4 weeks.</p>

<p>The 4-week wait is set by law. It gives people time to raise concerns they have about the LPA: for example, if they think you're being forced into making it or that someone is committing fraud.</p>

<p>OPG also uses the time to check that the LPA has been made correctly and there's nothing that would make it invalid or unworkable. If there is something that must be corrected before it can be registered, OPG will contact you.</p>

<p>The registered LPA document that OPG sends you is the same form that you filled in and sent to OPG – but you will see it's been stamped, once OPG's registered it. </p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-signing-the-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:signing-the-lpa">Signing the LPA</a></li>
<li><a href="/guidance/#topic-fees-and-reductions" class="js-guidance" data-journey="stageprompt.lpa:help:fees-and-reductions">Fees and reductions</a></li>
<li><a href="/guidance/#topic-people-to-be-told" class="js-guidance" data-journey="stageprompt.lpa:help:people-to-be-told">People to be told</a></li>
</ul>

</article>
<article id="topic-applicant"><h1>Applicant</h1>

<p>The applicant is the person applying to register the LPA. The applicant will also receive the stamped LPA once it's registered.</p>

<p>Someone else, such as a solicitor, can help with an application. But the person who is applying must sign the 'Application to register a lasting power of attorney' form (LPA002). This form will be available to download after you have paid the application fee.</p>

<p>The Office of the Public Guardian (OPG) needs to know who is applying to register the LPA so that it can send the registered and stamped LPA to the right person.</p>

<p>If the applicant has named a correspondent, they will receive the registered LPA instead of the applicant.</p>

<h2>Who can apply to register an LPA</h2>

<p>Either you (the donor) or 1 or more of your attorneys, can apply to register your LPA. A donor and attorney can't apply to register an LPA together.</p>

<h3>If you have more than 1 attorney</h3>

<p>If any of your attorneys want to register your LPA, the rules about who can apply depend on how you've said your attorneys must make decisions.</p>

<p>If all decisions are to be made jointly:</p>

<ul>
<li>all attorneys must apply to register the LPA together</li>
<li>all attorneys must sign the application form (LPA002)</li>
</ul>

<p>If you've said some or all decisions can be made jointly and severally:</p>

<ul>
<li>any of the attorneys can apply to register the LPA</li>
<li>those who apply must sign the application form (LPA002)</li>
</ul>

<p>If more than 1 attorney applies to register your LPA, OPG will send the registered and stamped LPA to the attorney whose name appears first on the application.</p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-correspondence-address" class="js-guidance" data-journey="stageprompt.lpa:help:correspondence-address">Correspondence address</a></li>
<li><a href="/guidance/#topic-how-attorneys-make-decisions" class="js-guidance" data-journey="stageprompt.lpa:help:how-attorneys-make-decisions">How attorneys make decisions</a></li>
</ul>

</article>
<article id="topic-correspondence-address"><h1>Correspondence address</h1>

<p>The Office of the Public Guardian (OPG) will contact the person named in the correspondence address about the progress of an application to register an LPA. They will also send the registered LPA to this correspondent. </p>

<h2>Who can be the correspondent</h2>

<p>The correspondent can be:</p>

<ul>
<li>the applicant (either you or 1 of your attorneys)</li>
<li>a solicitor or other legal professional</li>
<li>someone else you'd prefer to receive OPG correspondence</li>
</ul>

<p>There can only be one correspondent for each LPA application.</p>

<h2>Why OPG makes contact</h2>

<p>OPG might need to get in touch with the correspondent to:</p>

<ul>
<li>give information about an application's progress</li>
<li>ask a question about your LPA</li>
</ul>

<p>The correspondent will also receive the LPA once it is registered.</p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-applicant" class="js-guidance" data-journey="stageprompt.lpa:help:applicant">Applicant</a></li>
<li><a href="/guidance/#topic-registering-the-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:registering-the-lpa">Registering the LPA</a></li>
</ul>

</article>
<article id="topic-previous-powers-of-attorney"><h1>Previous powers of attorney</h1>

<p>The Office of the Public Guardian (OPG) needs to know about any other LPA or enduring power of attorney (EPA) you've made.</p>

<p>Use the text box in this section of the tool to let OPG know:</p>

<ul>
<li>that there's another LPA or EPA</li>
<li>if there is one, who the attorneys were or are.</li>
</ul>

<p>You should give this information if the EPA or LPA was signed, even if it wasn't registered with OPG or was cancelled.</p>

<p>If OPG needs more details, you will be asked to send the previous LPA or EPA. Usually this doesn't happen and the names of the attorneys are enough.</p>

<p>If you don't have a copy of the older LPA or EPA, write information in the text box that might help OPG to locate your records. For example, a reference number or a registration date are useful.</p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-registering-the-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:registering-the-lpa">Registering the LPA</a></li>
</ul>

</article>
<article id="topic-fees-and-reductions"><h1>Fees, reductions and exemptions</h1>

<p>It costs £110 to apply to register an LPA. If you (the donor) have a low income or get certain means-tested benefits, you can pay a lower fee or no fee.</p>

<ol>
<li><p>If you receive particular means-tested benefits, you won't have to pay anything (this called an 'exemption').</p></li>
<li><p>If you have an income before tax of less than £12,000 a year, you will only have to pay half (this is known as a '50 per cent remission').</p></li>
<li><p>If you get Universal Credit, you may also be entitled to a remission. The Office of the Public Guardian (OPG) will work out how much you should pay when it receives your application.</p></li>
</ol>

<p>If an attorney applies to register the LPA, the attorney's financial circumstances aren't taken into account. The attorney can pay the fee and reclaim it from the donor's funds.</p>

<p>It is only the donor whose benefits and income matter.</p>

<h2>Means-tested benefits: no fee</h2>

<p>If you (the donor) get any of these means-tested benefits, you won't have to pay a fee:</p>

<ul>
<li>Income Support</li>
<li>Income-based Employment and Support Allowance</li>
<li>Income-based Jobseeker's Allowance</li>
<li>Guarantee Credit element of State Pension Credit</li>
<li>a combination of Working Tax Credit and at least one of:

<ul>
<li>Child Tax Credit</li>
<li>Disability Element of Working Tax Credit</li>
<li>Severe Disability Element of Working Tax Credit</li>
</ul></li>
<li>Housing Benefit</li>
<li>Council Tax Reduction (not the 25% single person reduction or the Class U exemption) or Council Tax Support</li>
<li>Local Housing Allowance.</li>
</ul>

<p>If you have been awarded personal injury damages of more than £16,000, you can't get an exemption, even if the damages were ignored when you were assessed for a benefit.</p>

<p>Disability Living Allowance, Invalidity Benefit and Personal Independence Payment don't allow you to get an exemption from paying the fee.</p>

<h3>Proof of benefits</h3>

<p>You have to prove that you (the donor) get 1 of the relevant benefits. Your proof should be a recent letter from:</p>

<ul>
<li>the Department for Work and Pensions (DWP)
or</li>
<li>another relevant benefit provider confirming that you receive benefits.</li>
</ul>

<p>The letter must confirm that you got the benefit at the time the LPA was sent to OPG for registration. The letter should include these details:</p>

<ul>
<li>title</li>
<li>full name</li>
<li>address including postcode</li>
</ul>

<p>Send your proof to the Office of the Public Guardian (OPG) with all the following:</p>

<ul>
<li>LPA document</li>
<li>application to register form (LPA002)</li>
<li>application for remission form (LPA120A)</li>
</ul>

<h2>Low income: reduced fee</h2>

<p>If you have a gross annual income of less than £12,000 you will be eligible to pay only half of the fee (this is called a 'remission').</p>

<p>Gross annual income is income before tax. It's not just salary or wages – it may come from different sources, such as:</p>

<ul>
<li>non-means-tested benefits (for example, Attendance Allowance and Disability Living Allowance)</li>
<li>pensions</li>
<li>interest from capital investments</li>
<li>rental income from property</li>
</ul>

<h3>Proof of low income</h3>

<p>You have to send OPG documents that prove you have a low income. These must be documents that have your title, full name, address and postcode printed on them and they must be from the current tax year. (Tax years run from 5 April one year to 4 April the next year.) Proof can include photocopies of:</p>

<ul>
<li>3 months' consecutive wage slips or a P60</li>
<li>statements from a pension provider</li>
<li>a recent tax return if you're self-employed</li>
<li>statements or vouchers showing interest from capital, stocks, shares or bonds</li>
</ul>

<p>You can also send an official letter or notice from the payer of non-means-tested benefits – this can't be a copy.</p>

<p>If you don't have an income, you have to send OPG a signed statement explaining how you support yourself.</p>

<p>Send your proof to OPG with all the following:</p>

<ul>
<li>LPA document</li>
<li>application to register form (LPA002)</li>
<li>application for remission form (LPA120A)</li>
</ul>

<h2>Universal Credit: reduced fee</h2>

<p>If you receive Universal Credit, you may also be able to pay less.</p>

<p>Because Universal Credit is being tested and replaces several existing benefits, OPG will have to look at your application before it can say how much of the fee you'll have to pay.</p>

<p>If you state that you get Universal Credit, you won't be charged through this digital tool to make your application. This tool will still create all the documents you need, but you won't be asked to pay.</p>

<h3>Proof of Universal Credit</h3>

<p>Send a copy of your benefit award letter to OPG with all the following:</p>

<ul>
<li>LPA document</li>
<li>application to register form (LPA002)</li>
<li>application for remission form (LPA120A)</li>
</ul>

<p>OPG will contact you to let you know how much you'll have to pay and to arrange payment. OPG aims to do this within 7 working days of getting your application.</p>

<h3>Related help topics</h3>

<ul>
<li><a href="/guidance/#topic-registering-the-lpa" class="js-guidance" data-journey="stageprompt.lpa:help:registering-the-lpa">Registering the LPA</a></li>
</ul>

</article>
<article id="topic-glossary"><h1>Glossary</h1>

<p>Here are words you'll see when you're making your lasting power of attorney (LPA). The help topics explain many of them in more detail.</p>

<p><strong>Applicant</strong> </p>

<blockquote>
  <p>The applicant is the person who applies to register the LPA – that can be you (the donor) or 1 or more of your attorneys. The Office of the Public Guardian (OPG) usually sends the registered and stamped LPA to the applicant. However, if you tell OPG to correspond with a legal professional about your LPA application, OPG will send the registered LPA to that person.</p>
</blockquote>

<p><strong>Attorney</strong></p>

<blockquote>
  <p>Attorneys are the people you choose to make decisions for you. You know them well and trust them to respect your views and act in your best interests. Attorneys don't need to be lawyers. Many people choose their wife, husband, civil partner, partner, children, other relatives or close friends. Attorneys must be at least 18 years' old.</p>
</blockquote>

<p><strong>Certificate provider</strong> </p>

<blockquote>
  <p>Certificate providers are impartial people who confirm that you understand what you are doing and that nobody is forcing you to make the LPA. If you name any 'people to be told' in your LPA, you need 1 certificate provider. If you haven't, you need 2 certificate providers. Also see 'People to be told'.</p>
</blockquote>

<p><strong>Donor</strong></p>

<blockquote>
  <p>You are the donor. The donor is the person making the LPA and choosing other people to make decisions on their behalf. Only the donor can make decisions about their LPA, such as choosing their attorneys. A donor must be at least 18 years' old and have mental capacity when they make their LPA.</p>
</blockquote>

<p><strong>Exemption</strong></p>

<blockquote>
  <p>If you, the donor, get certain means-tested benefits, you will not have to pay to apply to register your LPA. This is known as an 'exemption'. Also see 'Remission'. </p>
</blockquote>

<p><strong>Guidance</strong></p>

<blockquote>
  <p>You can include guidance in your LPA. Guidance is what you'd like your attorneys to think about when making decisions for you. Attorneys should take guidance into account but don't have to follow it. Also see 'Restrictions'.</p>
</blockquote>

<p><strong>Jointly</strong></p>

<blockquote>
  <p>'Jointly' means that your attorneys must unanimously agree on every decision they make for you. If attorneys can't agree, they can't make a decision. If 1 attorney can no longer act on your behalf, the others won't be able to make these decisions either.</p>
</blockquote>

<p><strong>Jointly and severally</strong></p>

<blockquote>
  <p>'Jointly and severally' means that each attorney can make any decision on their own or they can decide together if they prefer. This is the most practical option as decisions won't be delayed, or not made, because attorneys can't meet or agree.</p>
</blockquote>

<p><strong>Jointly for some decisions, and jointly and severally for other decisions</strong></p>

<blockquote>
  <p>'Jointly for some decisions, and jointly and severally for other decisions' means that your attorneys must unanimously agree on some specific decisions but can make others on their own. Donors who pick this option must clearly state all the decisions that must be agreed unanimously. If 1 attorney can no longer act on your behalf, the others won't be able to make these decisions either. But they can continue to make other decisions.</p>
</blockquote>

<p><strong>Lasting power of attorney (LPA)</strong></p>

<blockquote>
  <p>An LPA is a legal document that allows you to choose other people to make decisions for you. There are 2 types of LPA: </p>
</blockquote>

<ul>
<li>health and welfare LPA, which can only be used if you don't have mental capacity</li>
<li>property and financial affairs LPA, which can be used as soon as it's registered, if you decide you need people to help you, and if you don't have mental capacity</li>
</ul>

<blockquote>
  <p>An LPA must be registered by the Office of the Public Guardian (OPG) before it can be used.</p>
</blockquote>

<p><strong>Life-sustaining treatment</strong></p>

<blockquote>
  <p>Life-sustaining treatment is any care, medicine, surgery or other remedy that a doctor says is needed to keep you alive. If you make a health and welfare LPA, you can give your attorneys the power to allow or refuse life-sustaining treatment for you – otherwise, doctors will decide. Decisions about this type of treatment can only be made by others if you don't have mental capacity.</p>
</blockquote>

<p><strong>Mental capacity</strong></p>

<blockquote>
  <p>Mental capacity means the ability to make a decision. A person with mental capacity has at least a general understanding of the decision they need to make, why they need to make it and what is likely to happen when they make it. Sometimes people can make some kinds of decision but don't have the mental capacity to make others. The Ministry of Justice website has <a href="http://www.justice.gov.uk/protecting-the-vulnerable/mental-capacity-act" rel="external" target="_blank">more about mental capacity</a>.</p>
</blockquote>

<p><strong>Office of the Public Guardian (OPG)</strong></p>

<blockquote>
  <p>OPG is the agency in England and Wales that registers LPAs and protects people who don't have mental capacity. Also see 'Registration'.</p>
</blockquote>

<p><strong>People to be told</strong></p>

<blockquote>
  <p>People to be told are individuals you choose to be notified when you apply to register your LPA. These people provide extra security as they get a chance to raise any concerns about your LPA before it's registered – for example, if they believe you've been put under pressure to make it.</p>
</blockquote>

<p><strong>Registration</strong></p>

<blockquote>
  <p>An LPA must be registered with OPG before it can be used. The 'Register' section of this tool will guide you through the process. Also see 'Exemption' and 'Remission'.</p>
</blockquote>

<p><strong>Remission</strong></p>

<blockquote>
  <p>If you (the donor) have an income of less than £12,000 a year before tax, you pay less to apply to register your LPA. This is known as a 'remission'. Also see 'Exemption'.</p>
</blockquote>

<p><strong>Replacement attorneys</strong></p>

<blockquote>
  <p>Replacement attorneys are people you choose to step in if 1 or more of your attorneys can no longer act or decide for you.</p>
</blockquote>

<p><strong>Restrictions and conditions</strong></p>

<blockquote>
  <p>You can specify restrictions and conditions in your LPA. These tell your attorneys things that they must and must not do when making decisions and acting for you. Many donors don't add restrictions and conditions as they trust their attorneys to make the decisions they would make themselves. Also see 'Guidance'.</p>
</blockquote>

<p><strong>Trust corporation</strong></p>

<blockquote>
  <p>A trust corporation can only be an attorney for a property and financial affairs LPA. A trust corporation manages your funds, including savings, pensions or investments. A trust corporation is usually run by a commercial bank or firm of solicitors. You can't appoint more than 1 trust corporation in your LPA.</p>
</blockquote>

<p><strong>Witness</strong></p>

<blockquote>
  <p>Witnesses are impartial people who watch you and your attorneys, including any replacement attorneys, sign your LPA. They must also sign the LPA to say they've seen you and your attorneys sign.</p>
</blockquote>

</article>
      </div>
      <div class="action group">
        <p>Need help? Ring us on <strong>0300 456 0300</strong>. Alternatively, email us at <strong><a href="mailto:customerservices@PublicGuardian.gsi.gov.uk?subject=Digital%20LPA%20Enquiry">customerservices@PublicGuardian.gsi.gov.uk</a></strong>.</p>
        <hr>
        <a href="#" class="js-popup-close button-secondary">Close help</a>
      </div>
    </section>