<?php


$form           = $this->form;

$email          = $form->get('email');
$email_confirm  = $form->get('email_confirm');
$submit         = $form->get('submit');
$formLabel      = $this->plugin('formLabel');

$form->prepare();

?>

<? if( $this->sent ){ ?>

    <h2>Thank you</h2>

    <p>We've emailed a link to <strong><?= $email->getValue() ?></strong> so that you can reset your password.</p>

    <p>If you haven't received the email within a few minutes, please check your spam, bulk or junk email folder – it may have been mistakenly blocked by your email system.</p>

    <p>If it doesn't arrive at all, please check that you've given us the correct email address for your existing LPA account &ndash; we'll only send a password reset link to the email address belonging to an account.</p>

    <p><a href="<?= $this->url('login') ?>">Sign in</a></p>

<? } else { ?>

    <p>Enter your email address below. If there's an account associated with the address, we'll send you a link to reset your password.</p>

    <div class="form">

        <?= $this->form()->openTag( $form->setAttribute( 'class', 'form' ) ); ?>

            <? # TODO - how are errors meant to be styled? ?>

            <?= $this->formElement($form->get('secret')) ?>
            
            <div class="group <?= count($form->get('secret')->getMessages()) > 0 ? 'validation' : ''; ?>">
            <?= $this->formElementErrors($form->get('secret')) ?>
            </div>

            <? if (isset($this->error) || count($form->getMessages()) > 0) { ?>
                <div class="validation-summary group" role="alert" aria-labelledby="error-heading" tabindex="-1">
                <h1 id="error-heading">There was a problem submitting the form</h1>
                <p>Because of the following problems:</p>
                <ol>
                <?php 
                    foreach ($form->getElements() as $element) {
                        foreach ($element->getMessages() as $elementMessage) {
                            echo '<li><a href="#' . $element->getAttribute('name') . '">';
                            echo $elementMessage;
                            echo '</a></li>';
                        }
                    }            

                    if (isset($this->error)) {
                        echo '<li><a href="">';
                        switch($this->error){
                            case 'RECEIVED_IN_LAST_5_MINUTES':
                                echo $this->escapehtml( "You've already asked to reset your password in the last 5 minutes. We've sent you an email with your password reset instructions. If it hasn't arrived, please check your spam or junk mail folder: your email service may have filtered it by mistake." ); break;
                            case 'ACCOUNT_NOT_FOUND':
                                echo$this->escapehtml( "We could not find an account for this email address." ); break;
                            case 'ACCOUNT_NOT_ACTIVE':
                                echo $this->escapehtml( "You need to activate your account before you reset your password." ); break;
                            default:
                                echo $this->escapehtml( $this->error );
                        }
                        echo '</a></li>';
                    }
                ?>
                </ol>
                </div>
            <? } ?>

            <div class="group <?= count($email->getMessages()) > 0 ? 'validation' : ''; ?>">

                <?= $formLabel->openTag() . $email->getOption('label'); ?>
                    <?= $this->formElementErrors($email) ?>
                    <?= $this->formInput(
                            $email->setAttributes([
                                'id' => 'email',
                                'autocomplete' => 'off'
                            ])
                        ) 
                    ?>

                <?= $formLabel->closeTag() ?>
                
            </div>
            
            <div class="group <?= count($email_confirm->getMessages()) > 0 ? 'validation' : ''; ?>">

            <?= $formLabel->openTag() . $email_confirm->getOption('label'); ?>
                <?= $this->formElementErrors($email_confirm) ?>
                
                <?= $this->formInput(
                        $email_confirm->setAttributes([
                            'id' => 'email_confirm',
                            'autocomplete' => 'off'
                        ])
                    ) 
                ?>

                <?= $formLabel->closeTag() ?>
            </div>

            <div class="action group"><p class="action group">

                <?= $this->formInput(
                    $submit->setAttributes([
                        'id' => 'form-submit',
                        'value' => 'Email me the link',
                        'class' => 'button'
                    ])
                ) ?>

            </div>

        <?= $this->form()->closeTag(); ?>

    </div>

<? } ?>
