
<div class="form">

    <div class="validation-summary group" role="alert" aria-labelledby="error-heading" tabindex="-1">
        <h1 id="error-heading">You can’t reset your password with the link you’ve used</h1>
        <p>This might be because you've:</p>
        <ul>
            <li>already used this link</li>
            <li>asked for another link since</li>
            <li>changed the link</li>
        </ul>
        <p><a href="<?= $this->url('forgot-password') ?>">Ask for a new link</a> so you can reset your password.</p>
    </div>

</div>
