<?php

    $form = $this->formErrorTextExchange($this->form, []);

    $password          = $form->get('password');
    $password_confirm  = $form->get('password_confirm');

    $password->setAttributes([
        'id' => 'password',
        'autocomplete' => 'off'
    ]);

    $password_confirm->setAttributes([
        'id' => 'password_confirm',
        'autocomplete' => 'off'
    ]);

    $form->prepare();

    //---

    $formLabel = $this->plugin('formLabel');

?>
<div class="account form">

    <p>Your password has to be at least 8 characters long and must contain at least 1 lower-case letter, 1 capital letter and 1 number. Never share your password with anyone.</p>

    <?= $this->form()->openTag(  $form->setAttribute( 'class', 'form' ) ); ?>

        <div class="<?= $this->elementGroupClass($form->get($form->csrfName())) ?>">
            <?= $this->formElement($form->get($form->csrfName())) ?>
        </div>

        <? if (isset($this->error) || count($form->getMessages()) > 0) { ?>
            <div class="validation-summary group" role="alert" aria-labelledby="error-heading" tabindex="-1">
                <h1 id="error-heading">There was a problem submitting the form</h1>
                <p>Because of the following problems:</p>
                <ol>
                    <?php
                    $this->formLinkedErrorList($form);

                    if (isset($this->error)) {
                        echo '<li><a href="">';
                        switch($this->error){
                            default:
                                echo $this->escapehtml( $this->error );
                        }
                        echo '</a></li>';
                    }
                    ?>
                </ol>
            </div>
        <? } ?>

        <div class="<?= $this->elementGroupClass($password); ?>">
            <?= $formLabel->openTag() . $password->getOption('label'); ?>
            Password
            <br>
            <?= $this->formElementErrors($password) ?>
            <?= $this->formElement($password) ?>
            <?= $formLabel->closeTag() ?>
        </div>

        <div class="<?= $this->elementGroupClass($password_confirm); ?>">
            <?= $formLabel->openTag() . $password_confirm->getOption('label'); ?>
            Confirm Password
            <br>
            <?= $this->formElementErrors($password_confirm) ?>
            <?= $this->formElement($password_confirm) ?>
            <?= $formLabel->closeTag() ?>
        </div>

        <div class="form-submit-button">
            <input name="submit" id="form-submit" value="Reset my password" class="button" type="submit">
        </div>

    <?= $this->form()->closeTag(); ?>

</div>
