<?php

$form              = $this->form;

$password          = $form->get('password');
$password_confirm  = $form->get('password_confirm');

$form->prepare();

?>
<div class="account form">

    <p>Your password has to be at least 8 characters long and must contain at least 1 lower-case letter, 1 capital letter and 1 number. Never share your password with anyone.</p>

    <?= $this->form()->openTag(  $form->setAttribute( 'class', 'form' ) ); ?>

        <div class="<?= $this->elementGroupClass($form->get('secret')) ?>">
            <?= $this->formElement($form->get('secret')) ?>
        </div>

        <? if (isset($this->error) || count($form->getMessages()) > 0) { ?>
            <div class="validation-summary group" role="alert" aria-labelledby="error-heading" tabindex="-1">
                <h1 id="error-heading">There was a problem submitting the form</h1>
                <p>Because of the following problems:</p>
                <ol>
                    <?php
                    $this->linkedErrorList($form);

                    if (isset($this->error)) {
                        echo '<li><a href="">';
                        switch($this->error){
                            default:
                                echo $this->escapehtml( $this->error );
                        }
                        echo '</a></li>';
                    }
                    ?>
                </ol>
            </div>
        <? } ?>

        <div class="group">

            <label for="password" class="required">New password</label>

            <?= $this->formInput(
                $password->setAttributes([
                    'id' => 'password',
                    'autocomplete' => 'off'
                ])
            ) ?>

            <p class='form-element-errors'>
                <?= $this->formElementErrors($password) ?>
            </p>

        </div>

        <div class="group">

            <label for="password_confirm" class="required">Re-enter new password</label>

            <?= $this->formInput(
                $password_confirm->setAttributes([
                    'id' => 'password_confirm',
                    'autocomplete' => 'off'
                ])
            ) ?>

            <p class='form-element-errors'>
                <?= $this->formElementErrors($password_confirm) ?>
            </p>

        </div>

        <div class="form-submit-button">
            <input name="submit" id="form-submit" value="Reset my password" class="button" type="submit">
        </div>

    <?= $this->form()->closeTag(); ?>

</div>
