<?php
    $form        = $this->form;
    $form->setAttribute('class', 'form');
    $csrf        = $form->get('secret');
    
    $lowIncome       = $form->get('reducedFeeLowIncome');
    $lowIncomeValueOptions = $lowIncome->getOptions()['value_options'];
    $lowIncomeValueOptions['yes']['label'] = "Yes";
    $lowIncomeValueOptions['no']['label'] = "No";
    
    $lowIncomeValueOptions['yes'] += [
            'label_attributes' => [
                    'for' => 'low-income-yes'
            ],
            'attributes' => [
                    'id' => 'low-income-yes'
            ],
    ];
    $lowIncomeValueOptions['no'] += [
            'label_attributes' => [
                    'for' => 'low-income-no'
            ],
            'attributes' => [
                    'id' => 'low-income-no'
            ],
    ];
    $lowIncome->setOptions(['value_options'=>$lowIncomeValueOptions, 'label' => "Is the donor’s gross annual income less than £12,000?"]);

    $universalCredit       = $form->get('reducedFeeUniversalCredit');
    $universalCreditValueOptions = $universalCredit->getOptions()['value_options'];
    $universalCreditValueOptions['yes']['label'] = "Yes";
    $universalCreditValueOptions['no']['label']  = "No";
    
    $universalCreditValueOptions['yes'] += [
            'label_attributes' => [
                    'for' => 'universal-credit-yes'
            ],
            'attributes' => [
                    'id' => 'universal-credit-yes'
            ],
    ];
    $universalCreditValueOptions['no'] += [
            'label_attributes' => [
                    'for' => 'universal-credit-no'
            ],
            'attributes' => [
                    'id' => 'universal-credit-no'
            ],
    ];
    $universalCredit->setOptions(['value_options'=>$universalCreditValueOptions, 'label'=>"Does the donor receive Universal Credit?"]);
    
    $submit      = $form->get('submit');
    $submit->setAttributes(['class'=>'button gotonextpart', 'value'=>'Save and continue']);
    
    $formLabel   = $this->plugin('formLabel');
    $form->prepare();
?>

<section id="lpa-type" class="section current">
	
	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. Fee remission based on Universal Credit and gross annual income</h2>
	
    <div class="accordion-content">
    	
        <?= $this->form()->openTag($form); ?>
            
            <?= $this->formElement($csrf) ?>
            
            <?= $this->formErrorList(); ?>
            
            
    	    <div class="section-intro">
    	       <h2>Universal Credit</h2>
                <p>In order to apply for this exemption, you must enclose copies of letters from the DWP or your benefit provider confirming that the benefit is being paid at the time the LPA is sent to us for registration. <a class="js-guidance" href="/help/#topic-fees-and-reductions" data-journey-click="stageprompt.lpa:help:fees-and-reductions">Find out more about acceptable proof</a>.</p>
            
                <div class="emphasised option group">
                    <?= $formLabel->openTag($universalCredit) . $universalCredit->getOption('label') . $formLabel->closeTag(); ?>
                    <?= $this->formElement($universalCredit)?>
                    
                    <p class='form-element-errors'>
                        <?= $this->formElementErrors($universalCredit) ?>
                    </p>
                </div>
    	    </div>
            
            <div class="section-intro">
        	   <h2>Income</h2>
                <p>In order to apply for this reduction, you should send us proof of your gross annual income, such as wage slips, tax returns or statements from a pension provider. The evidence provided should cover a period of at least three months. <a class="js-guidance" href="/help/#topic-fees-and-reductions" data-journey-click="stageprompt.lpa:help:fees-and-reductions">Find out more about acceptable proof</a>.</p>
            
                <div class="emphasised option group">
                    <?= $formLabel->openTag($lowIncome) . $lowIncome->getOption('label') . $formLabel->closeTag(); ?>
                    <?= $this->formElement($lowIncome)?>
                    
                    <p class='form-element-errors'>
                        <?= $this->formElementErrors($lowIncome) ?>
                    </p>
                </div>
    		</div>
                
                <p>Insufficient evidence will result in delays to your application and if your claim is rejected you'll need to pay the rest of the fee.</p>
                
                <p>By clicking below I certify that the above information is correct and that to the best of my knowledge and belief, I have completed the application in accordance with the provisions of the Mental Capacity Act 2005 and all statutory instruments made under it.</p>
                
            <div class="accordion-actions">
				<p>
                    <input type="submit" name="save" value="Save and continue" class="button gotonextpart">
                </p>
            </div>
            
        <?= $this->form()->closeTag(); ?>
    	
    </div>
    
</section>