<?php
$form        = $this->form;
$csrf        = $form->get('secret');

$form->setAttribute('class', 'form');

$type        = $form->get('how-would-you-rate');
$typeValueOptions = $type->getOptions()['value_options'];

$typeValueOptions['very-satisfied']['label'] = 'Very satisfied';
$typeValueOptions['satisfied']['label'] = 'Satisfied';
$typeValueOptions['neither-satisfied-or-dissatisfied']['label'] = 'Neither satisfied or dissatisfied';
$typeValueOptions['dissatisfied']['label'] = 'Dissatisfied';
$typeValueOptions['very-dissatisfied']['label'] = 'Very dissatisfied';

$details = $form->get('details');
$details->setOptions(['label' => 'Please take a moment to tell us about your experience, what worked and what didn\'t']);

$details->setAttributes([
    'id' => 'details',
    'rows' => 10,
    'cols' => 67,
]);

$email = $form->get('email');
$email->setOptions(['label' => 'Your email address (optional)']);

$email->setAttributes([
    'id' => 'email',
    'type' => 'email',
    'maxlength' => 100,
]);

$type->setOptions( ['value_options' => $typeValueOptions] );

$formLabel   = $this->plugin('formLabel');
?>

<?= $this->form()->openTag($form); ?>
    
            <?= $this->formElement($csrf) ?>
            
            <?= $this->formErrorList(); ?>
            
            <div class="emphasised option group">
                <?= $this->formElement($type)?>
                
                <p class='form-element-errors'>
                    <?= $this->formElementErrors($type) ?>
                </p>
            </div>
    
             <div class="group">
                
                <h3 id="instructions-label">
                    <?= $formLabel->openTag($details) . $details->getOption('label'); ?>
                    <?= $formLabel->closeTag() ?>
                </h3>
                
                <p>
                <?= $this->formElement($details)?>
                </p>
                
                <p class='form-element-errors'>
                    <?= $this->formElementErrors($details) ?>
                </p>
                
            </div>       
        
            <div class="group">
                
                <h3 id="instructions-label">
                    <?= $formLabel->openTag($email) . $details->getOption('label'); ?>
                    <?= $formLabel->closeTag() ?>
                </h3>
                
                <p>
                <?= $this->formElement($email)?>
                </p>
                
                <p class='form-element-errors'>
                    <?= $this->formElementErrors($email) ?>
                </p>
                
            </div>
            
          		<p>
            <input type="submit" name="send" id="send" value="Send" class="button">
        </p>
       <?= $this->form()->closeTag(); ?>
            
            
