<?php
$form = $this->form;
$csrf = $form->get('secret');

$form->setAttribute('class', 'form');

$type = $form->get('rating');
$typeValueOptions = $type->getOptions()['value_options'];

$typeValueOptions['very-satisfied']['label'] = 'Very satisfied';
$typeValueOptions['satisfied']['label'] = 'Satisfied';
$typeValueOptions['neither-satisfied-or-dissatisfied']['label'] = 'Neither satisfied or dissatisfied';
$typeValueOptions['dissatisfied']['label'] = 'Dissatisfied';
$typeValueOptions['very-dissatisfied']['label'] = 'Very dissatisfied';

$details = $form->get('details');

$details->setAttributes([
    'id' => 'details',
    'rows' => 10,
    'cols' => 67
]);

$email = $form->get('email');

$email->setAttributes([
    'id' => 'email',
    'type' => 'email',
    'maxlength' => 100
]);

$type->setOptions([
    'value_options' => $typeValueOptions
]);

$formLabel = $this->plugin('formLabel');
?>

<?= $this->form()->openTag($form); ?>
    
<?= $this->formElement($csrf)?>

<?= $this->formErrorList(); ?>

<div class="form_element">
    <?= $formLabel->openTag($type)?>
    How would you rate your experience with this service?
    <?= $formLabel->closeTag(); ?>
    <?= $this->formElement($type)?>
    <?= $this->formElementErrors($type)?>
</div>

<div class="form_element">
    <?= $formLabel->openTag($details)?>
    Please take a moment to tell us about your experience, what worked and what didn't
    <?= $formLabel->closeTag(); ?>

    
    <p>
    <?= $this->formElement($details)?>
    </p>
    
        <?= $this->formElementErrors($details)?>
</div>

<div class="form_element">
                        We are always working to improve this service. If you are happy to be contacted to give further feedback, please leave your email address.
                
                                <?= $formLabel->openTag($email)?>
                Your email address (optional)
                <?= $formLabel->closeTag(); ?>
                
                <p>
                <?= $this->formElement($email)?>
                </p>
                
                    <?= $this->formElementErrors($email)?>
                
            </div>

<p>
	<input type="submit" name="send" id="send" value="Send" class="button">
</p>
<?= $this->form()->closeTag(); ?>
            
            
