
<p>Thank you for giving us your feedback on the digital LPA tool: we regularly update this service and are paying careful attention to all the comments we're receiving.</p>

<p>If you have a question that needs a response, please email <a href="mailto:customerservices@publicguardian.gsi.gov.uk">customerservices@publicguardian.gsi.gov.uk</a> or call 0300 456 0300, as emails to this address will not be answered directly.</p>

<p>Thank you again: your feedback will help improve the tool for everyone.</p>

<p><a href="/home">Return to the tool</a></p>

