
<html>
<head></head>
<body>

<h1>LPA digital tool feedback</h1>

<h2>Sent</h2>

<?= htmlspecialchars($this->sentTime); ?>

<h2>Rating</h2>

<?= htmlspecialchars($this->rating); ?>

<h2>Comments</h2>

<?= htmlspecialchars($this->details); ?>

<h2>Email</h2>

<?= htmlspecialchars($this->email); ?>

<h2>Feedback link clicked from</h2>

<?= htmlspecialchars($this->fromPage); ?>

<h2>User Agent</h2>

<?= htmlspecialchars($this->agent); ?>

</body>
</html>
