<html>
<head></head>
<body>

<p>Hello,</p>
 
<p>The Office of the Public Guardian (OPG) is committed to providing a quality service.</p>

<p>We would be very grateful if you could provide feedback before 06 October about making and paying for your Lasting Power of Attorney online, in a short 10 minute survey.</p>

<p>We also welcome your comments and suggestions.</p>

<p>By giving us your feedback, you will help us to make our services better.</p>
 
<p>All the information you provide is kept confidential and used only for monitoring customer satisfaction.</p>

<p>Please click <a href="https://www.surveymonkey.com/r/Online-LPA-Pilot">here</a> to go to the survey now.</p>

<?php echo $this->partial('email/partials/signoff.phtml'); ?>

</body>
</html>
