<html>
<head></head>
<body>
	<p>
		Thank you for completing the LPA online for <strong><?= $this->lpa->document->donor->name ?>'s
		lasting power of attorney (LPA) for <?= (($this->lpa->document->type==Opg\Lpa\DataModel\Lpa\Document\Document::LPA_TYPE_PF)?"property and financial affairs":"health and welfare") ?></strong>.
	</p>
	
	<p>Reference number <?= $this->cellStyles(\Opg\Lpa\DataModel\Lpa\Formatter::id($this->lpa->id)) ?></p>
	
	<?php if($this->lpa->payment->reference != null):?>
	<p>Payment reference number: <?= $this->cellStyles($this->lpa->payment->reference) ?></p>
	<?php endif;?>

	<p>If you haven't already you should print off the LPA and sign before sending it to the OPG. Instructions on the order people must sign are on the cover sheet of the LPA.</p>

	<div style='width:500px;margin-left:40px'>
		<strong><a href="<?=$this->signinUrl ?>">Sign in to download and print the LPA form</a></strong>
	</div>
	
	<p>If the donor is applying for an exemption or reduction of the fee, you'll need to download and sign the fee remission form too. If the donor has included "people to notify" in their LPA, you'll also need to download notification letters and send them to the people the donor has nominated. You'll find links to both the fee remission form and the "people to notify" letters on the same page as the link to the LPA itself.</p>
	
	<p>
	If you have paid the LPA registration fee but not sent in the LPA form to be registered, we will send you a reminder email 20 days after payment. If we have still not received the LPA 40 days after the payment date, we will refund the fee to the account it was paid from.
	</p>
	
	<p><strong>Remember, an LPA must be registered before it can be used.</strong></p>

	<? if( true ){ ?>
		<p>Please <a href="https://www.surveymonkey.com/r/Online-LPA-Pilot">take our survey</a> to help us to improve the digital LPA service.</p>
	<? } ?>

<p>This is an automatic email - please don't reply to this address. If you need to contact us you can:</p> 

<?php echo $this->partial('email/partials/signoff.phtml'); ?>	
</body>
</html>
