<html>
<head></head>
<body>

<p>You have asked us to change your email address to <?= $this->newEmailAddress ?>.</p>

<p>We have sent an email to the new address - please follow the link in the email in order to complete the update.</p>

<p>Until then, your current email address will remain the active email address for your account.</p>

<p>This is an automatic email - please don't reply to this address. If you need to contact us you can:</p>

<?php echo $this->partial('email/partials/signoff.phtml'); ?>

</body>
</html>
