<html>
<head></head>
<body>

<p>You have requested an update to your email address.</p>

<p>If you've do not wish to change your email address, just ignore this email.</p>

<p>To continue with the change, please click the following link in order to activate the new email address:</p>

<div style='width:500px;margin-left:40px;font-weight:bold'><a href="<?= $this->activateUrl ?>">Verify my new email address</a></div>

</p>

<p>This is an automatic email - please don't reply to this address. If you need to contact us you can:</p>

<?php echo $this->partial('email/partials/signoff.phtml'); ?>

</body>
</html>
