<html>
<head></head>
<body>

<p>This email is about the online account you used to create a lasting power of attorney at <a href="https://www.lastingpowerofattorney.service.gov.uk/login">lastingpowerofattorney.service.gov.uk</a></p>

<p><strong>Nothing in this email affects any LPAs you've already made and registered with the Office of the Public Guardian.</strong> It's just about the account: if you've registered an LPA, you can safely ignore this mail and keep using that LPA. But if you have any draft or unregistered LPAs held on the website, or if you think you'll want to sign back in the future to look at your documents, then this may affect you.</p>

<p>It's been 8 months since you last signed in to your account.
    If a user doesn't sign in for 9 months, we close their account and delete all the information associated with it.
    This is to protect your privacy: we don't want to hold this data for longer than we need to.
</p>

<div style='width:500px;margin-left:40px'>
    <strong>In 1 month's time we will delete your account</strong>
</div>

<p> If you do want to keep your account, you should just <a href="https://www.lastingpowerofattorney.service.gov.uk/login">sign in</a>
    &ndash; that will reset the 9-month timer.
</p>

<p>If your account is deleted:
<ul>
    <li>LPAs registered with the Office of the Public Guardian will not be affected at all</li>
    <li>unregistered LPA drafts that you only have online will be deleted</li>
    <li>you can register an LPA you've already printed out,
        but you won't be able to use the tool to automatically fill in the other forms you need
        &ndash; this could make things more complicated
</ul>
</p>
<p>If you're sure that you're finished with your account, you can either
    ignore this email or <a href="https://www.lastingpowerofattorney.service.gov.uk/login">sign in</a> and delete the account yourself.
</p>

<p>This is an automatic email &ndash; please don't reply to this address. If you need to contact us you can:</p>

<?php echo $this->partial('email/partials/signoff.phtml'); ?>
</body>
</html>