<html>
<head></head>
<body>

<p>You told us you'd forgotten the password for your LPA account.</p>

<div style='width:500px;margin-left:40px;font-weight:bold'><a href="<?= $this->callback ?>">Choose a new password now</a></div>

<p>If you've remembered your password or do not want to reset it, just ignore this email and sign in as usual.</p>

<p>This is an automatic email - please don't reply to this address. If you need to contact us you can:</p>

<?php echo $this->partial('email/partials/signoff.phtml'); ?>

</body>
</html>
