<?php echo $this->partial('email/partials/header.phtml'); ?>
<table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF" style="margin-bottom: 19px; margin-top: 19px;">
    <tr>
        <td width="100%">
            <table width="580" cellpadding="0" cellspacing="0" border="0" align="center">
                <tr>
                    <td width="75%">
                        <img src="https://neil-files-tmp.s3-eu-west-1.amazonaws.com/email-images/opg-logo-v1.png" alt="OPG" border="0">
                        <h1 style="font-size: 36px; line-height: 1.315; font-weight: 700; margin: 20px 0 26px 0; color: #0b0c0c">
                            Reset Password
                        </h1>
                        <p style="font-size: 19px; line-height: 1.315; margin: 0 0 20px 0; color: #0b0c0c">
                            You told us you'd forgotten the password for your LPA account.
                        </p>
                        <p style="font-size: 19px; line-height: 1.315; margin: 0 0 20px 0; color: #0b0c0c">
                            <!-- URLs have white-space: nowrap so that they don't wrap -->
                            <a style="white-space: nowrap; color: #005ea5" href="<?= $this->callback ?>">Choose a new password now</a>
                        </p>
                        <p style="font-size: 19px; line-height: 1.315; margin: 0 0 20px 0; color: #0b0c0c">
                            If you've remembered your password or do not want to reset it, just ignore this email and sign in as usual.
                        </p>
                        <p style="font-size: 19px; line-height: 1.315; margin: 0 0 20px 0; color: #0b0c0c">
                            This is an automatic email - please don't reply to this address.
                        </p>
                        <?php echo $this->partial('email/partials/footer.phtml'); ?>
                    </td>
                    <td width="25%">&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>
