<html>
<head></head>
<body>

<p>You told us that you'd forgotten the password for your LPA account. However, you haven't activated the account yet.</p>

<p>First, please activate your account using the link below:</p>

<div style='width:500px;margin-left:40px;font-weight:bold'><a href="<?php echo $this->callback ?>">Activate My account now</a></div>

<p>Once you've done that, use the website's 'Forgotten your password?' link again. This time, we'll send you an email that will let you reset your password.</p>

<p>This is an automatic email - please don't reply to this address. If you need to contact us you can:</p>

<?php echo $this->partial('email/partials/signoff.phtml'); ?>

</body>
</html>