
<html>
<head></head>
<body>

<p>Thank you for registering to use the digital LPA tool.</p>

<p><strong>Use this link to activate and start using your account:</strong></p>

<div style='width:500px;margin-left:40px'>
    <a href="<?= $this->callback ?>"><?= $this->escapehtml($this->callback) ?></a>
</div>

<p>If the link doesn't work, copy it into your browser's address bar.  The link will expire in 24 hours.</p>

<strong>You must activate your account before you can create a lasting power of attorney (LPA).</strong>

<p>You must activate your account within 24 hours. If you don't, the account will be automatically deleted and you'll have to register again.</p>

<p>This is an automatic email - please don't reply to this address. If you need to contact us you can:</p>

<div>
    <p>Call <strong>0300 456 0300</strong></p>
    <p>Email <a href='mailto:customerservices@PublicGuardian.gsi.gov.uk'>customerservices@PublicGuardian.gsi.gov.uk</a></p>
</div>

<br/><br/>

<p><strong style="font-size:1.2em">Office of the Public Guardian</strong></p>
<p>PO Box 16185, Birmingham B2 2WH</p>
<p><a href="https://www.lastingpowerofattorney.service.gov.uk/home">www.lastingpowerofattorney.service.gov.uk</a></p>

</body>
</html>
