<?php
    $form = $this->formErrorTextExchange($this->form, []);
    
    $csrf = $form->get('secret');
    $form->setAttributes(['id'=>'decisions-form', 'class' => 'form']);
    
    $how        = $form->get('how');
    $howValueOptions = $how->getOptions()['value_options'];
    $howValueOptions['jointly-attorney-severally']['label'] = 'Jointly and severally' . $this->partial('application/how-primary-attorneys-make-decision/partials/jointly-severally.phtml');
    $howValueOptions['jointly']['label'] = 'Jointly' . $this->partial('application/how-primary-attorneys-make-decision/partials/jointly.phtml');
    $howValueOptions['depends']['label'] = 'Jointly for some decisions, and jointly and severally for other decisions' . $this->partial('application/how-primary-attorneys-make-decision/partials/depends.phtml');
    
    $howValueOptions['jointly-attorney-severally'] += [
            'label_attributes' => [
                    'for' => 'how-jointly-attorney-severally'
            ],
            'attributes' => [
                    'id' => 'how-jointly-attorney-severally'
            ],
    ];
    $howValueOptions['jointly'] += [
            'label_attributes' => [
                    'for' => 'how-jointly'
            ],
            'attributes' => [
                    'id' => 'how-jointly'
            ],
    ];
    $howValueOptions['depends'] += [
            'label_attributes' => [
                    'for' => 'how-depends'
            ],
            'attributes' => [
                    'id' => 'how-depends'
            ],
    ];
    
    $how->setOptions(['value_options'=>$howValueOptions]);
    $how->setLabelOptions(['disable_html_escape' => true]);
    
    $howDetails = $form->get('howDetails');
    $howDetails->setAttributes([
        'rows' => 24,
        'cols' => 80,
    ]);
    
    $submit     = $form->get('submit');
    $submit->setAttributes(['class'=>'button gotonextpart', 'value'=>'Save and continue']);
        
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>

<section id="primary-attorney-decisions" class="section current">
	
	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. How should your attorneys make decisions?</h2>
	
    <div class="accordion-content">


		<div class="section-intro">

			<p>Your choice here is very important as it affects how your LPA can be used. Whichever option you choose, your attorneys must always act in your best interests.</p>

			<p><a class="js-guidance" href="/help/#topic-how-attorneys-make-decisions" data-journey-click="stageprompt.lpa:help:how-attorneys-make-decisions">Get help with making this decision</a></p>
		</div>

		<h3>How should the attorneys make decisions?</h3>
		
        <?= $this->form()->openTag($form); ?>
    
        <?= $this->formElement($csrf) ?>
        <?= $this->formElementErrors($csrf) ?>

        <div class="emphasised option group">
            
            <?= $this->formElement($how)?>
            
            <p class='form-element-errors'>
                <?= $this->formElementErrors($how) ?>
            </p>
            
        </div>

        <div id="toggle-how-depends" class="details-textbox" data-toggled-by="#how-depends" style="display: none;">
				<p class="hint">Please tell us which decisions have to be made jointly, and which can be made jointly and severally. 
				
				<a class="js-guidance" href="/help/#topic-how-attorneys-make-decisions" data-journey-click="stageprompt.lpa:help:how-attorneys-make-decisions">Take a look at the guidance</a> for examples of how to make your wishes clear.</p>
				
                <?= $this->formElement($howDetails)?>
                
                <p class='form-element-errors'>
                    <?= $this->formElementErrors($howDetails) ?>
                </p>
        </div>        

        <div class="accordion-actions">
			<p>
                <?= $this->formElement($submit) ?>
            </p>
        </div>
        
        <?= $this->form()->closeTag(); ?>
		
        
    </div>	

</section>