<?php
    $title      = 'LPA Donor';
    $this->headTitle($title);
    $form       = $this->form;
    $title      = $form->get('name-title');
    $firstname  = $form->get('name-first');
    $lastname   = $form->get('name-last');
    $otherNames   = $form->get('otherNames');
    $dob        = $form->get('dob-date');
    $email      = $form->get('email-address');
    $address1   = $form->get('address-address1');
    $address2   = $form->get('address-address2');
    $address3   = $form->get('address-address3');
    $postcode   = $form->get('address-postcode');
    $canSign    = $form->get('canSign');
    $submit     = $form->get('submit');
    
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>


<?= $this->form()->openTag($form); ?>

<div class="form_element">

    <?= $formLabel->openTag() . $title->getOption('label'); ?>
    
    <?= $this->formSelect($title) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($title) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $firstname->getOption('label'); ?>
    
    <?= $this->formInput($firstname) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($firstname) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $lastname->getOption('label'); ?>
    
    <?= $this->formInput($lastname) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($lastname) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $otherNames->getOption('label'); ?>
    
    <?= $this->formInput($otherNames) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($otherNames) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $dob->getOption('label'); ?>
    
    <?= $this->formDate($dob) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($dob) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $email->getOption('label'); ?>
    
    <?= $this->formInput($email) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($email) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address1->getOption('label'); ?>
    
    <?= $this->formInput($address1) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address1) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address2->getOption('label'); ?>
    
    <?= $this->formInput($address2) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address2) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address3->getOption('label'); ?>
    
    <?= $this->formInput($address3) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address3) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $postcode->getOption('label'); ?>
    
    <?= $this->formInput($postcode) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($postcode) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $canSign->getOption('label'); ?>
    
    <?= $this->formcheckbox($canSign) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($canSign) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $this->formInput($submit) ?>

</div>


<?= $this->formElement($form->get('secret')) ?>

<?= $this->form()->closeTag(); ?>