<?php
    $form       = $this->form;
    $csrf       = $form->get('secret');
    $title      = $form->get('name-title');
    $firstname  = $form->get('name-first');
    $lastname   = $form->get('name-last');
    $otherNames   = $form->get('otherNames');
    $dob        = $form->get('dob-date');
    $email      = $form->get('email-address');
    $address1   = $form->get('address-address1');
    $address2   = $form->get('address-address2');
    $address3   = $form->get('address-address3');
    $postcode   = $form->get('address-postcode');
    $canSign    = $form->get('canSign');
    
    $form->setAttribute('class', 'form js-PersonForm js-PostcodeLookup');

    $title->setOptions( ['label' => 'Title'] );
    $firstname->setOptions( ['label' => 'First names'] );
    $lastname->setOptions( ['label' => 'Last names'] );
    $otherNames->setOptions( ['label' => 'Other names'] );
    $dob->setOptions( ['label' => 'Date of birth'] );
    $email->setOptions( ['label' => 'Email address'] );
    $address1->setOptions( ['label' => 'Address line 1'] );
    $address2->setOptions( ['label' => 'Address line 2'] );
    $address3->setOptions( ['label' => 'Address line 3'] );
    $postcode->setOptions( ['label' => 'Postcode'] );
    $canSign->setOptions( ['label' => 'This person cannot physically sign the LPA'] );
    
    $submit     = $form->get('submit');
    $submit->setAttributes(['value'=>'Save and continue']);
    
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>
<h2 class="header">Edit the donor's details</h2>
<?= $this->form()->openTag($form); ?>

<div class="<?= $this->elementGroupClass($csrf) ?>">
    <?= $this->formElement($csrf) ?>
</div>

<?= $this->formErrorList(); ?>
        
<fieldset>

<div class="group">

    <?= $formLabel->openTag() . $title->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formInput($title) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($title) ?>
    </p>
    
    

</div>


<div class="group">

    <?= $formLabel->openTag() . $firstname->getOption('label') . $formLabel->closeTag(); ?>
    
     
    <?= $this->formInput($firstname) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($firstname) ?>
    </p>
    
</div>


<div class="form_element">

    <?= $formLabel->openTag() . $lastname->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formInput($lastname) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($lastname) ?>
    </p>
    
    

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $otherNames->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formInput($otherNames) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($otherNames) ?>
    </p>
    
    

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $dob->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formDate($dob) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($dob) ?>
    </p>
    
    

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $email->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formInput($email) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($email) ?>
    </p>
    
    

</div>

</fieldset>
<div class="form_element">

    <?= $formLabel->openTag() . $address1->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formInput($address1) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address1) ?>
    </p>
    
    

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address2->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formInput($address2) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address2) ?>
    </p>
    
    

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address3->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formInput($address3) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address3) ?>
    </p>
    
    

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $postcode->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formInput($postcode) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($postcode) ?>
    </p>
    
    

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $canSign->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formcheckbox($canSign) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($canSign) ?>
    </p>
    
    

</div>


<p class="action group">
<input type="submit" name="submit" id="form-save" value="Save details" class="button"> 
<button name="cancel" id="form-cancel" type="button" class="button-secondary">Cancel</button>
</p>

<?= $this->form()->closeTag(); ?>
