<?php
    $form       = $this->form;
    $csrf       = $form->get('secret');
    $title      = $form->get('name-title');
    $firstname  = $form->get('name-first');
    $lastname   = $form->get('name-last');
    $otherNames = $form->get('otherNames');
    $dobDay     = $form->get('dob-date-day');
    $dobMonth   = $form->get('dob-date-month');
    $dobYear    = $form->get('dob-date-year');
    $email      = $form->get('email-address');
    $address1   = $form->get('address-address1');
    $address2   = $form->get('address-address2');
    $address3   = $form->get('address-address3');
    $postcode   = $form->get('address-postcode');
    $canSign    = $form->get('canSign');
    
    $form->setAttribute('class', 'form js-PersonForm js-PostcodeLookup');

    $title->setOptions(     ['label' => 'Title'] );
    $firstname->setOptions( ['label' => 'First names'] );
    $lastname->setOptions(  ['label' => 'Last name'] );
    $otherNames->setOptions(['label' => 'Other names'] );
    
    $dobDay->setOptions(    ['label' => 'Day'] );
    $dobMonth->setOptions(  ['label' => 'Month'] );
    $dobYear->setOptions(   ['label' => 'Year'] );
    
    $dobDay->setAttribute('id', 'dob-day');
    $dobMonth->setAttribute('id', 'dob-month');
    $dobYear->setAttribute('id', 'dob-year');
    
    $email->setOptions(     ['label' => 'Email address'] );
    $address1->setOptions(  ['label' => 'Address line 1'] );
    $address2->setOptions(  ['label' => 'Address line 2'] );
    $address3->setOptions(  ['label' => 'Address line 3'] );
    $postcode->setOptions(  ['label' => 'Postcode'] );
    $canSign->setOptions(   ['label' => 'This person cannot physically sign the LPA'] );
    $canSign->setAttribute('class', 'donor-cannot-sign');
    
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>
<h2 class="header">Edit the donor's details</h2>
<?= $this->form()->openTag($form); ?>

<?= $this->formElement($csrf) ?>
<?= $this->formElementErrors($csrf) ?>

<?= $this->formErrorList(); ?>
        
<fieldset>
    
    <div class="group">
        <?= $formLabel->openTag() . $title->getOption('label') . $formLabel->closeTag(); ?>
        <?= $this->formElement($title) ?>
        <?= $this->formElementErrors($title) ?>
    </div>
    
    <div class="group">
        <?= $formLabel->openTag() . $firstname->getOption('label') . $formLabel->closeTag(); ?>
        <?= $this->formElement($firstname) ?>
        <?= $this->formElementErrors($firstname) ?>
    </div>
    
    
    <div class="group">
        <?= $formLabel->openTag() . $lastname->getOption('label') . $formLabel->closeTag(); ?>
        <?= $this->formElement($lastname) ?>
        <?= $this->formElementErrors($lastname) ?>
    </div>
    
    <details>
        <summary class="hint" role="button" aria-expanded="false">Is this person known by any other names?</summary>
        <div class="group">
            <?= $formLabel->openTag() . $otherNames->getOption('label') . $formLabel->closeTag(); ?>
            <?= $this->formElement($otherNames) ?>
            <?= $this->formElementErrors($otherNames) ?>
        </div>
    </details>
    
    <div class="group">
        
        <label for="dob" id="dob-label" class="required">Date of birth</label>
        
        <div class="dob-element">
        
            <div class="form-group form-group-day">
                <?= $formLabel->openTag($dobDay) . $dobDay->getOption('label') . $formLabel->closeTag(); ?>
                <?= $this->formElement($dobDay) ?>
            </div>
            
            <div class="form-group form-group-month">
                <?= $formLabel->openTag($dobMonth) . $dobMonth->getOption('label') . $formLabel->closeTag(); ?>
                <?= $this->formElement($dobMonth) ?>
            </div>
            
            <div class="form-group form-group-year">
                <?= $formLabel->openTag($dobYear) . $dobYear->getOption('label') . $formLabel->closeTag(); ?>
                <?= $this->formElement($dobYear) ?>
            </div>
        </div>
        
    </div>
    <div class="group">
        <?= $this->formElementErrors($dobYear) ?>
    </div>
    
    <div class="group">
        <?= $formLabel->openTag() . $email->getOption('label') . $formLabel->closeTag(); ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors($email) ?>
    </div>

</fieldset>

<fieldset class="js-PostcodeLookup__postal-add">

        <div class="<?= $this->elementGroupClass($address1); ?>">
            <?= $formLabel->openTag() . $address1->getOption('label') . $formLabel->closeTag(); ?>
            <?= $this->formElement($address1) ?>
            <?= $this->formElementErrors($address1) ?>
        </div>
        
        <div class="<?= $this->elementGroupClass($address2); ?>">
            <?= $formLabel->openTag() . $address2->getOption('label') . $formLabel->closeTag(); ?>
            <?= $this->formElement($address2) ?>
            <?= $this->formElementErrors($address2) ?>
        </div>
        
        <div class="<?= $this->elementGroupClass($address3); ?>">
            <?= $formLabel->openTag() . $address3->getOption('label') . $formLabel->closeTag(); ?>
            <?= $this->formElement($address3) ?>
            <?= $this->formElementErrors($address3) ?>
        </div>
        
        <div class="<?= $this->elementGroupClass($postcode); ?>">
            <?= $formLabel->openTag() . $postcode->getOption('label') . $formLabel->closeTag(); ?>
            <?= $this->formElement($postcode) ?>
            <?= $this->formElementErrors($postcode) ?>
        </div>
</fieldset>

<fieldset id="donor-sign">
<div class="option group">
    <?= $formLabel->openTag($canSign) . $this->formcheckbox($canSign); ?>
    <?= $canSign->getOption('label'). $formLabel->closeTag(); ?>
    <span class="hint">We'll include an extra signature sheet so someone can sign on their behalf</span>
    <?= $this->formElementErrors($canSign) ?>
</div>
</fieldset>

<p class="action group">
<input type="submit" name="submit" id="form-save" value="Save details" class="button"> 
<button name="cancel" id="form-cancel" type="button" class="button-secondary">Cancel</button>
</p>

<?= $this->form()->closeTag(); ?>
