<?php 
use Opg\Lpa\DataModel\Lpa\Document\Donor;
?>
<section id="donor" class="section current">
	
	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. Who is the donor for this LPA?</h2>
	
    <div class="accordion-content">
    		<div class="section-intro">
    			<p>The 'donor' is the person appointing other people to make decisions on their behalf. The donor:</p>
    
    			<ul>
    				<li>must be 18 or over</li>
    				<li>must be able to make their own decisions when they create the LPA – this is known as having mental capacity</li>
    			</ul>
    
    			<p>Only the donor can make decisions about their LPA and the people to involve.</p>
    
    
    			<p><a href="/guidance/#topic-donor" class="js-guidance" data-journey-click="stageprompt.lpa:help:donor">Find out more about being a donor</a></p>
    		</div>
    		
    <?php if($this->lpa->document->donor instanceof Donor): ?>		
    		<div class="person-summary group">
    			<div class="person">
    				<h3><?=$this->lpa->document->donor->name->__toString()?></h3>
    				<p>
    				<?=$this->lpa->document->donor->address->__toString()?>
    				</p>
    			</div>
    
    			<ul class="actions">
    				<li><a href="<?=$this->editDonorUrl?>" data-form="donor" class="js-form-popup">View/edit details</a></li>
    			</ul>
    		</div>
    		<div class="accordion-actions group">
    			<p>
    				<a href="<?=$this->nextRoute?>" class="button gotonextpart" role="button">Save and continue</a>
    			</p>
    		</div>
    
    <?php else:?>
    
            <p>
                <a class="add button js-form-popup" data-form="donor" href="/lpa/<?=$this->lpa->id?>/donor/add" role="button">Add donor details</a>
            </p>
    		
    		<div class="accordion-actions group">
    			<p>
    				<span disabled="1" class="button">Save and continue</span>
    			</p>
    		</div>
    <?php endif;?>
    
    </div>

</section>