aws-vault exec identity -- terraform state pull > account.tfstate
cp account.tfstate account.tfstate.backup


aws-vault exec identity -- terraform state rm "aws_cloudwatch_log_group.vpc_flow_logs"
aws-vault exec identity -- terraform state rm "aws_flow_log.vpc_flow_logs"
aws-vault exec identity -- terraform state rm "aws_db_subnet_group.data_persistence"
aws-vault exec identity -- terraform state rm "aws_default_route_table.default"
aws-vault exec identity -- terraform state rm "aws_default_subnet.public[0]"
aws-vault exec identity -- terraform state rm "aws_default_subnet.public[1]"
aws-vault exec identity -- terraform state rm "aws_default_subnet.public[2]"
aws-vault exec identity -- terraform state rm "aws_default_vpc.default"
aws-vault exec identity -- terraform state rm "aws_eip.nat[0]"
aws-vault exec identity -- terraform state rm "aws_eip.nat[1]"
aws-vault exec identity -- terraform state rm "aws_eip.nat[2]"
aws-vault exec identity -- terraform state rm "aws_kms_key.secrets_encryption_key"
aws-vault exec identity -- terraform state rm "aws_nat_gateway.nat[0]"
aws-vault exec identity -- terraform state rm "aws_nat_gateway.nat[1]"
aws-vault exec identity -- terraform state rm "aws_nat_gateway.nat[2]"
aws-vault exec identity -- terraform state rm "aws_route.default"
aws-vault exec identity -- terraform state rm "aws_route.private[0]"
aws-vault exec identity -- terraform state rm "aws_route.private[1]"
aws-vault exec identity -- terraform state rm "aws_route.private[2]"
aws-vault exec identity -- terraform state rm "aws_route_table.private[0]"
aws-vault exec identity -- terraform state rm "aws_route_table.private[1]"
aws-vault exec identity -- terraform state rm "aws_route_table.private[2]"
aws-vault exec identity -- terraform state rm "aws_route_table_association.private[0]"
aws-vault exec identity -- terraform state rm "aws_route_table_association.private[1]"
aws-vault exec identity -- terraform state rm "aws_route_table_association.private[2]"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.api_rds_password"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.api_rds_username"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.opg_lpa_admin_jwt_secret"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.opg_lpa_api_notify_api_key"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.opg_lpa_common_account_cleanup_notification_recipients"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.opg_lpa_common_admin_accounts"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.opg_lpa_front_csrf_salt"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.opg_lpa_front_email_sendgrid_api_key"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.opg_lpa_front_email_sendgrid_webhook_token"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.opg_lpa_front_gov_pay_key"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.opg_lpa_front_os_places_hub_license_key"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.opg_lpa_pdf_owner_password"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.performance_platform_db_password"
aws-vault exec identity -- terraform state rm "aws_secretsmanager_secret.performance_platform_db_username"
aws-vault exec identity -- terraform state rm "aws_subnet.private[0]"
aws-vault exec identity -- terraform state rm "aws_subnet.private[1]"
aws-vault exec identity -- terraform state rm "aws_subnet.private[2]"
