[project]
name = "pipeline-scripts"
version = "0.0.0"
requires-python = "==3.14.6"
dependencies = [
    "awscli==1.45.28",
    "boto3==1.43.62",
    "requests==2.34.2",
    "pipelinescriptslib",
]
[tool.uv]
package = false
[tool.uv.sources]
pipelinescriptslib = { path = "lib", editable = true }
[tool.uv.workspace]
members = []
