<?php
    $form           = $this->form;
    $csrf           = $form->get('secret');
    $canSustainLife = $form->get('canSustainLife');
    
    $canSustainLifeOptions = $canSustainLife->getOptions()['value_options'];
    $canSustainLifeOptions[true] += [
            'label_attributes' => [
                    'for' => 'can-sustain-life-true'
            ],
            'attributes' => [
                    'id' => 'can-sustain-life-true'
            ],
    ];
    $canSustainLifeOptions[false] += [
            'label_attributes' => [
                    'for' => 'can-sustain-life-false'
            ],
            'attributes' => [
                    'id' => 'can-sustain-life-false'
            ],
    ];
    $canSustainLife->setOptions(['value_options'=>$canSustainLifeOptions]);
    
    $submit         = $form->get('submit');
    $submit->setAttributes(['class'=>'button gotonextpart']);
    
    $formLabel      = $this->plugin('formLabel');
    $form->prepare();
?>
<section id="life-sustaining" class="section current">
	
	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. Can your attorneys give or refuse consent to life-sustaining treatment?</h2>

    <div class="accordion-content">
  
		<div class="section-intro">

            <p>This is a very important decision. Read the guidance carefully before you answer.</p>
            <ul>
            	<li>Life-sustaining treatment is any treatment a doctor considers necessary to keep you alive</li>
            	<li>If you don’t allow your attorneys to give or refuse consent on your behalf, your doctors will make decisions about life-sustaining treatment</li>
            	<li>Your attorneys can only make decisions about life-sustaining treatment if you don't have mental capacity</li>
            </ul>
            
    		<p><a href="/help/#topic-life-sustaining-treatment" class="js-guidance" data-journey-click="stageprompt.lpa:help:life-sustaining-treatment">Read guidance on making this decision </a></p>

		</div>

		<h3>Do you want to give your attorneys authority to make decisions about life-sustaining treatment on your behalf?</h3>
    
        <?= $this->form()->openTag($form); ?>
        
        
        <div class="<?= $this->elementGroupClass($csrf) ?>">
            <?= $this->formElement($csrf) ?>
            <?= $this->formElementErrors($csrf) ?>
        </div>
        
        <div class="emphasised option group">
            <?= $this->formRadio($canSustainLife) ?>
            
            <p class='form-element-errors'>
                <?= $this->formElementErrors($canSustainLife) ?>
            </p>
        </div>
        
        
        <div class="accordion-actions">
        <p>
            <?= $this->formInput($submit) ?>
        </p>
        </div>
                
        <?= $this->form()->closeTag(); ?>
    
    </div>
    
</section>