
<h2>Thank you</h2>
<p>We've emailed a link to <strong><?= $this->escapehtml( $this->email ) ?></strong> which you will need to use to verify your new email address.</p>
<p>If you haven't received the email within a few minutes, please check your spam, bulk or junk email folder – it may have been mistakenly blocked by your email system.</p>
<p>If it doesn't arrive at all, please check that you've given us the correct email address for your existing LPA account &ndash; we'll only send a password reset link to the email address belonging to an account.</p>

<p><a href="<?= $this->url('login') ?>">Sign in</a></p>
