
<h2>Thank you</h2>
<p>We've emailed a link to <strong><?= $this->escapehtml( $this->email ) ?></strong> which you will need to use to verify your new email address.</p>
<p>If you haven't received the email within a few minutes, please check your spam, bulk or junk email folder – it may have been mistakenly blocked by your email system.</p>

<p><a href="<?= $this->url('login') ?>">Sign in</a></p>
