<div class='accordion-content'>


    <div class="next-step-section">

        <h2>Print and sign your LPA</h2>

        <p class="block">You’re now ready to print and sign your LPA document, before you send it to the Office of the
            Public
            Guardian.</p>

        <p class="block">It’s essential that you sign the parts of your LPA in the right order – this guide shows you
            how. If you
            sign them in the wrong order, your LPA will be invalid and you may have to pay an additional fee.</p>

        <a class="button" href="<?= $this->lp1Url ?>" target="_blank">Print LPA</a>

    </div>

    <div class="next-step-section">

        <h2>Post your LPA to the Office of the Public Guardian</h2>

        <p>You need to send us:</p>

        <ul>
            <li>Your signed LPA (all sections, from 1-15)</li>
            <li>If you're applying for a fee reduction
                <ul>
                    <li>a completed application form for your exemption (LPA 120A)</li>
                    <li>evidence to support this application</li>
                </ul>
            </li>
        </ul>

        <p>And if you're paying by cheque:</p>

        <ul>
            <li>A cheque for the application fee, payable to ‘Office of the Public Guardian’</li>
        </ul>

        <p>Post all documents to this address:</p>

        <p><strong>
                Office of the Public Guardian<br>
                PO Box 16185<br>
                Birmingham<br>
                B2 2WH
            </strong></p>

        <p>If you’ve not already done so, remember to send the notification letters to [Correspondent details inserted
            automatically]</p>


        <h2>What happens next?</h2>

        <p>It will take 8 to 10 weeks to register the LPA if there are no mistakes in the application. This includes a
            waiting period in which anyone entitled to object to the registration of the LPA can lodge their objection.
            This waiting period is an important safeguard and is required by law.</p>

        <p>We'll send the registered LPA and any correspondence to <?= $this->correspondentName ?>.</p>

        <h2>Create another LPA?</h2>

        <p><strong><a href="<?= $this->cloneUrl ?>" class="js-clonewarning">Make an LPA based on this one</a></strong>
            (you'll be able to add people in a single click).</p>

        <p><a href="/user/dashboard/create">Make an LPA from scratch</a>.</p>

        <h2>Finished?</h2>

        <p><a href="/user/dashboard">View my LPAs</a>.</p>

        <p><a href="/logout">Sign out of this service.</a></p>


    </div>

</div>
