<div class="accordion-content">

<p>This document is for reference only. If you need to change anything in your LPA you'll have to create a new one.</p>

<h2>LPA form</h2>
<p><a id="registration_fm_lnk" class="pdf_dl_lnk" href="<?= $this->lp1Url ?>" target="_blank">Download the LPA form (PDF)</a></p>

<?php if(isset($this->lpa120Url)): ?>
  	<h2>Remission form</h2>
    <p><a id="notification_lnk" class="pdf_dl_lnk" href="<?= $this->lpa120Url ?>" target="_blank">Download the fee remission form (PDF)</a></p>
<?php endif;?>

<?php if(isset($this->lp3Url)): ?>
  	<h2>Notification letters</h2>
 	<p><a id="notification_lnk" class="pdf_dl_lnk" href="<?= $this->lp3Url ?>" target="_blank">Download the letter to send to your 'people to notify' (PDF)</a></p>
<?php endif;?>

<hr>

    <h2>Create another LPA?</h2>

    <p><a href="<?= $this->cloneUrl ?>">Make an LPA based on this one</a> (you'll be able to add people in a single click).</p>

    <p><a href="/user/dashboard/create">Make an LPA from scratch</a>.</p>

                        
</div>