<?php
    $form       = $this->form;
    
    $donor = $form->get('sign-date-donor');
    $donor->setAttributes(['placeholder' => 'DD/MM/YYYY']);
    
    $certificateProvider = $form->get('sign-date-certificate-provider');
    $certificateProvider->setAttributes(['placeholder' => 'DD/MM/YYYY']);
    
    $numAttorneys = count($this->attorneyNames);
    $attorney = [];
    for ($i=0; $i<$numAttorneys; $i++) {
        $attorney[$i] = $form->get('sign-date-attorney-' . $i);
        $attorney[$i]->setAttributes(['placeholder' => 'DD/MM/YYYY']);
    }
    
    $csrf       = $form->get('secret');
    
    $form->setAttributes(['class' => 'form']);
    
    $submit     = $form->get('submit');
    $submit->setAttributes(['class'=>'button', 'id'=>'form-submit', 'value'=>'Check dates']);
    
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>

<section id="signature-dates" class='section current'>
	<h2 class='accordion-header'>3.  When was the LPA signed?</h2>
	<div class='accordion-content'>
	
		<div class="section-intro">

<p>Please give the date each person below signed the LPA.</p>

<p>This is so we can check that the signatures were <a href="/help/#topic-signing-the-lpa" class="js-guidance" data-journey-click="stageprompt.lpa:help:signing-the-lpa">made in the right order</a>.</p>

<div class="application-notice info-notice">
  <p>After you click ‘continue’, below, you will
no longer be able to edit any information in this LPA. If the
donor wishes to edit any details, <a href="/create/review/">they should do so now</a>, then print it again and get it
signed again.</p>
</div>


    </div>


	<?= $this->form()->openTag($form); ?>
    
    <?= $this->formElement($csrf) ?>
    <?= $this->formElementErrors($csrf) ?>
    
    <?= $this->formErrorList(); ?>
    
<div class="person-summary group">
<div class="person">
	<h3><?= $this->donorName ?> (the donor)</h3>
	<p class="date-field">
		<label for="donor">
			This person signed part A of the LPA on
			
			<?= $this->formElement($donor) ?>
            <?= $this->formElementErrors($donor) ?>
            
        </label>
	</p>
		<div class="application-notice help-notice">
  		<p class="hint">Remember, if any continuation sheets were used they must also<br> have been signed at the same time as or before the donor signed part A.</p>
	</div>
</div>
</div>
<div class="person-summary group">
  <div class="person">
      <h3><?= $this->certificateProviderName ?> (certificate provider)</h3>
      <p class="date-field">
      	<label for="certificateProvider_0">This person signed part B of the LPA on
      	
            <?= $this->formElement($certificateProvider) ?>
            <?= $this->formElementErrors($certificateProvider) ?>
            
        </label>
      </p>
  </div>
</div>

<?php for ($i=0; $i<$numAttorneys; $i++) : ?>

    <div class="person-summary group">
        <div class="person">
  			<h3><?= $this->attorneyNames[$i]; ?> (attorney)</h3>
				<p class="date-field">
			<label for="attorney_0">This person signed part C of the LPA on
			     <?= $this->formElement($attorney[$i]) ?>
                 <?= $this->formElementErrors($attorney[$i]) ?>
            </label>
		</p>
	  </div>
</div>

<?php endfor; ?>

		<div class="accordion-actions group">
			        <div class="accordion-actions group">
            <p><?= $this->formElement($submit) ?></p>
        </div>
        
		</div>


    <?= $this->form()->closeTag(); ?>

	</div>
</section>
