### Base image - contains dependencies required for build
FROM public.ecr.aws/lambda/python:3.8 AS base

# fixes security issues detected in build.
RUN yum update -y rpm openssl

# Dependencies required to install psycopg2 (postgres driver)
# used in SQLAlchemy
RUN yum install -y gcc postgresql-devel

# Install Python dependencies for worker
COPY docker/api-requirements.txt /service-perfplat/
RUN pip install -r /service-perfplat/api-requirements.txt --target ${LAMBDA_TASK_ROOT}

### Final image - contains compiled dependencies
FROM public.ecr.aws/lambda/python:3.8

# fixes security issues detected in build.
RUN yum update -y rpm openssl

RUN yum install -y postgresql && \
    yum clean all && \
    rm -rf /var/cache/yum

COPY --from=base ${LAMBDA_TASK_ROOT} ${LAMBDA_TASK_ROOT}

# Copy lambda code to image
COPY ./perfplat /service-perfplat/perfplat

EXPOSE 4343

ENTRYPOINT ["python", "/service-perfplat/perfplat/lpa_make_perfplatform.py"]
