### Base image - contains dependencies required for build
FROM public.ecr.aws/lambda/python:3.9 AS base

# Dependencies required to install psycopg2 (postgres driver)
# used in SQLAlchemy
RUN yum install -y gcc postgresql-devel

# Install Python dependencies for worker
COPY service-perfplat/docker/worker-requirements.txt /service-perfplat/
RUN pip install -r /service-perfplat/worker-requirements.txt --target ${LAMBDA_TASK_ROOT}

### Final image - contains compiled dependencies
FROM public.ecr.aws/lambda/python:3.9

RUN yum install -y postgresql && \
    yum clean all && \
    rm -rf /var/cache/yum

# Fix security issues detected in build
RUN yum update -y rpm openssl-libs python python-libs

COPY --from=base ${LAMBDA_TASK_ROOT} ${LAMBDA_TASK_ROOT}

# Copy lambda code to image
COPY service-perfplat/perfplat /service-perfplat/perfplat

# Move the handler to the correct place in the filesystem so the lambda
# image can reference it
RUN mv /service-perfplat/perfplat/worker/handler.py ${LAMBDA_TASK_ROOT}/app.py

CMD ["app.exec"]
