### Image to deploy dev local dev dependencies and configuration

# Depends on localstack being present; also requires the perfplat
# worker to be up so that events can be proxied

FROM amazonlinux:2

RUN yum install -y zip jq wget python3 git && \
    pip3 install awscli

# fixes security issues detected in build.
RUN yum update -y nss nss-util nss-softokn nspr expat cyrus-sasl-lib curl

ENV WAITFORIT_VERSION="v2.4.1"

RUN wget -q -O /usr/local/bin/waitforit https://github.com/maxcnunes/waitforit/releases/download/$WAITFORIT_VERSION/waitforit-linux_amd64 && \
    chmod +x /usr/local/bin/waitforit

# Deploy a lambda proxy which proxies SQS events to the real perfplat worker
COPY ./dev-proxy /service-perfplat/dev-proxy
RUN chmod +x /service-perfplat/dev-proxy/deploy_proxy.sh

CMD ["/service-perfplat/dev-proxy/deploy_proxy.sh"]
