<?php

declare(strict_types=1);

namespace MakeShared\Telemetry;

use JsonSerializable;
use Telemetry\Tracer;

// see https://docs.aws.amazon.com/xray/latest/devguide/xray-api-sendingdata.html
class Segment implements JsonSerializable
{
    private string $segmentName;

    private float $start;
    private ?float $end = null;

    // segment ID, e.g. 70de5b6f19ff9a0a, generated by constructor
    private string $id;

    // from the x-amz-trace-id header on the initiating request
    // e.g. 1-581cf771-a006649127e371903a2de979
    private string $traceId;

    /** @var Segment[] $children */
    private array $children = [];

    public bool $sampled = true;

    // parent segment ID; set for subsegments, and on the root segment
    // if a Parent was specified in the x-amz-trace-id header
    private ?string $parentSegmentId = null;

    public function __construct(
        string $segmentName,
        string $traceId,
        ?string $parentSegmentId = null,
        bool $sampled = true,
    ) {
        $this->segmentName = $segmentName;
        $this->traceId = $traceId;
        $this->parentSegmentId = $parentSegmentId;
        $this->sampled = $sampled;

        $this->id = bin2hex(random_bytes(16 / 2));
        $this->start = microtime(true);
    }

    public function addChild(string $segmentName): Segment
    {
        $child = new Segment($segmentName, $this->traceId, $this->id, $this->sampled);
        $this->children[] = $child;
        return $child;
    }

    public function end(): void
    {
        if ($this->hasEnded()) {
            return;
        }

        foreach ($this->children as $child) {
            if (!$child->hasEnded()) {
                $child->end();
            }
        }

        $this->end = microtime(true);
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getParentSegmentId(): ?string
    {
        return $this->parentSegmentId;
    }

    public function hasEnded(): bool
    {
        return !is_null($this->end);
    }

    public function jsonSerialize(): mixed
    {
        $serialized = [
            'name' => $this->segmentName,
            'id' => $this->id,
            'start_time' => $this->start,
            'end_time' => $this->end,
            'trace_id' => $this->traceId,
        ];

        if (!is_null($this->parentSegmentId)) {
            $serialized['parent_id'] = $this->parentSegmentId;
            $serialized['type'] = 'subsegment';
        }

        if (count($this->children) > 0) {
            $serialized['subsegments'] = $this->children;
        }

        return $serialized;
    }
}
