<?php use Opg\Lpa\DataModel\Lpa\Document\Decisions\AbstractDecisions; ?>

<?=$this->params['idx'] ?>. The replacement attorneys will act 
<?php if( $this->params['values'] == AbstractDecisions::LPA_DECISION_HOW_JOINTLY_AND_SEVERALLY ):?>
    jointly and severally
<?php elseif( $this->params['values'] == AbstractDecisions::LPA_DECISION_HOW_JOINTLY ):?>
    jointly
<?php else:?>
    jointly for some decisions, and jointly and severally for other decisions
<?php endif;?>