<?php $this->layout('layout::default', ['title' => 'Feedback']);

$this->addErrorMap([
    'start-date' => [
        'empty-string' => [
            'summary'   => 'You didn\'t enter a start date',
            'field'     => 'Enter the start date'
        ],
        'invalid-date' => [
            'summary'   => 'You didn\'t enter a valid start date',
            'field'     => 'Enter a valid start date in the past'
        ],
        'future-date' => [
            'summary'   => 'The start date is in the future',
            'field'     => 'Enter a valid start date in the past'
        ],
    ],
    'end-date' => [
        'empty-string' => [
            'summary'   => 'You didn\'t enter an end date',
            'field'     => 'Enter the end date'
        ],
        'invalid-date' => [
            'summary'   => 'You didn\'t enter a valid end date',
            'field'     => 'Enter a valid end date in the past'
        ],
        'future-date' => [
            'summary'   => 'The end date is in the future',
            'field'     => 'Enter a valid end date in the past'
        ],
        'end-before-start' => [
            'summary'   => 'The end date is before the start date',
            'field'     => 'Enter a valid end date that is not before the start date'
        ]
    ]
]);
?>

<?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

<form method="post" action="<?= $this->url('feedback') ?>" novalidate>
    <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

    <div class="govuk-form-group">
        <fieldset class="govuk-fieldset" role="group">
            <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
                <h1 class="govuk-fieldset__heading">
                    Feedback
                </h1>
            </legend>
            <?php $this->insert('snippet::input-date', [
                    'formLabel'     => 'Start date',
                    'formElement'   => $form->get('start-date'),
            ]) ?>

            <?php $this->insert('snippet::input-date', [
                    'formLabel'     => 'End date',
                    'formElement'   => $form->get('end-date'),
                    'attrs' => ['data-cy' => 'end-date']
            ]) ?>
        </fieldset>
    </div>

    <div class="govuk-button-group">
        <button type="submit" class="govuk-button" data-module="govuk-button" data-cy="submit-button">
            Search
        </button>

        <?php if (is_array($feedback) && !empty($feedback)) { ?>
            <button type="submit"
                    class="govuk-button govuk-button--secondary"
                    data-module="govuk-button"
                    formaction="<?= $this->url('feedback') ?>?export=true">
                Export feedback
            </button>
        <?php } ?>
    </div>

</form>

<?php if (is_array($feedback)) { ?>

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-one-third">
            <?php if (empty($feedback)) { ?>
                <p class="govuk-body">No results</p>
            <?php } ?>
        </div>

        <div class="govuk-grid-column-two-thirds">
            <?php if ($earliestAvailableTime instanceof DateTime) { ?>
                <p class="govuk-body">Feedback results are available from <?= $earliestAvailableTime->format('D jS M Y'); ?> onwards</p>
            <?php } ?>
        </div>
    </div>
<?php } ?>

<?php if (is_array($feedback) && !empty($feedback)) {
    $feedbackFields = array_keys($feedback);

    $largeFields = [
            'Details',
            'Browser',
    ];
    ?>

    <div class="app-full-width-container">
        <table class="govuk-table" id="feedback-table">
            <thead class="govuk-table__head">
            <tr class="govuk-table__row">
                <?php foreach ($feedbackFields as $feedbackField) { ?>
                    <th scope="col" class="govuk-table__header <?= (in_array($feedbackField, $largeFields) ? 'govuk-!-width-one-quarter' : ''); ?>"><?= $feedbackField; ?></th>
                <?php } ?>
            </tr>
            </thead>

            <tbody class="govuk-table__body">
            <?php for ($i = 0; $i < count($feedback[$feedbackFields[0]]); $i++) { ?>
                <tr class="govuk-table__row">
                    <?php foreach ($feedbackFields as $feedbackField) { ?>
                        <td class="govuk-table__cell" data-role="<?= strtolower(str_replace(' ', '-', $feedbackField)); ?>">
                            <span class="app-break-word"><?= htmlentities($feedback[$feedbackField][$i]); ?></span>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
<?php } ?>
