<?php $this->layout('layout::default', ['title' => 'LPA Admin Home']) ?>

<h1 class="govuk-heading-xl">LPA Admin Home</h1>

<?php if (isset($user->name)) { ?>
    <p class="govuk-body">Please select an option from the top of the screen.</p>
<?php } else {?>
    <p class="govuk-body">You need to complete your LPA account details first!</p>
    <p class="govuk-body">
        You must <a class="govuk-link" href="https://www.lastingpowerofattorney.service.gov.uk/login">sign in using your account</a> on the LPA online service and fill in your details.
    </p>
<?php } ?>
