<?php $this->layout('layout::default', ['title' => 'Signed Out']); ?>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-l">You have been signed out</h1>

        <p class="govuk-body">Sign in again to continue.</p>

        <a href="<?= $this->e($signinUrl) ?>" role="button" draggable="false"
           class="govuk-button" data-module="govuk-button" data-cy="sign-in-button">
            Sign in
        </a>
    </div>
</div>
