<?php $this->layout('layout::default', ['title' => 'Sign In']);

$this->addErrorMap([
    'email' => [
        'required' => [
            'summary'   => 'Enter a valid gov.uk email address',
            'field'     => 'Enter a valid gov.uk email address',
        ],
        'invalid-email' => [
            'summary'   => 'Enter a valid gov.uk email address',
            'field'     => 'Enter a valid gov.uk email address',
        ],
        'authentication-error' => [
            'summary'   => 'Email and password combination not recognised',
            'field'     => 'Email and password combination not recognised',
        ],
        'authorization-error' => [
            'summary'   => 'You are not permitted to access this service',
            'field'     => 'You are not permitted to access this service',
        ],
        'account-locked' => [
            'summary'   => 'This user account has been locked. Go the LPA Online service to reset your password OR you can attempt again in 15 minutes',
            'field'     => 'This user account has been locked. Go the LPA Online service to reset your password OR you can attempt again in 15 minutes',
        ],
    ],
    'password' => [
        'required' => [
            'summary'   => 'Enter a password',
            'field'     => 'Enter a password',
        ],
    ],
]);
?>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <form method="post" action="<?= $this->url('sign.in') ?>" novalidate>
            <fieldset class="govuk-fieldset" role="group" >
                <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                    Sign in
                </legend>

                <?php $this->insert('snippet::flash-messages', ['messages' => $messages]) ?>

                <?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

                <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement'   => $form->get('email'),
                    'formLabel'     => 'Email address',
                    'formType'      => 'text',
                    'attrs'         => ['data-cy' => 'login-email'],
                ]) ?>

                <?php $this->insert('snippet::input-text', [
                    'formElement'         => $form->get('password'),
                    'formLabel'           => 'Password',
                    'formType'            => 'password',
                    'attrs'               => ['data-cy' => 'login-password'],
                ]) ?>
            </fieldset>
            <button type="submit" class="govuk-button" data-module="govuk-button" data-cy="login-submit-button">
                Continue
            </button>
        </form>
    </div>
</div>
