<?php $this->layout('layout::default', ['title' => 'System Message']); ?>

<?php $this->insert('snippet::flash-messages', ['messages' => $messages]) ?>

<?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

<form method="post" action="<?= $this->url('system.message') ?>">
    <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

    <div class="govuk-form-group">
        <fieldset class="govuk-fieldset" role="group">
            <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
                <h1 class="govuk-fieldset__heading">
                    System Message
                </h1>
            </legend>

            <p class="govuk-body">System messages will be seen by all visitors to the LPA service. They should be used to inform users of scheduled periods of maintenance or changes to the LPA service.</p>

            <?php $this->insert('snippet::input-text', [
                'formElement'   => $form->get('message'),
                'formLabel'     => 'Message',
                'formType'      => 'textarea',
                'attrs' => ['data-cy' => 'message']
            ]) ?>
        </fieldset>
    </div>

    <button type="submit" class="govuk-button" data-module="govuk-button" data-cy="submit-button">
        Set system message
    </button>
</form>
