<?php $this->layout('layout::default', ['title' => 'User Search']);

$this->addErrorMap([
    'email' => [
        'required' => [
            'summary'   => 'Enter a valid email address',
            'field'     => 'Enter a valid email address',
        ],
        'invalid-email' => [
            'summary'   => 'Enter a valid email address',
            'field'     => 'Enter a valid email address',
        ],
    ],
]);
?>

<div class="grid-row">
    <div class="column-full">
        <form method="post" class="form" action="<?= $this->url('user.search') ?>">
            <fieldset>

                <legend>
                    <h1 class="heading-xlarge">User Details</h1>
                </legend>

                <?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

                <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

                <div class="text">
                    <p>Search for a user by email address. If found, the user's account status and other details will be displayed.</p>
                </div>

                <?php $this->insert('snippet::input-text', [
                    'formLabel'     => 'Email address',
                    'formElement'   => $form->get('email'),
                    'formType'      => 'text',
                    'formLabelBold' => false,
                    'attrs'         => ['data-cy' => 'email-address-input'],
                ]) ?>

            </fieldset>

            <div class="form-group">
                <input data-cy="submit-button" class="button" type="submit" value="Search">
            </div>

        </form>

        <?php if (!is_null($user)) { ?>

            <h2 class="heading-medium">User details</h2>

            <div class="user-search-result">
                <ul>
                    <li>
                        <strong class="bold-small">Account status: </strong>

                        <span data-role="user-account-status">
                            <?php if (array_key_exists('isActive', $user)) { ?>
                                <?= ($user['isActive'] ? 'Activated' : 'Not activated'); ?>
                            <?php } elseif (array_key_exists('isDeleted', $user) && $user['isDeleted']) { ?>
                                Deleted
                            <?php } ?>
                        </span>
                    </li>

                    <?php if (isset($user['activatedAt'])) { ?>
                        <li>
                            <strong class="bold-small">Date activated: </strong>
                            <span data-role="user-activation-date"><?= $this->dateFormat($user['activatedAt']) ?></span>
                        </li>
                    <?php } ?>

                    <?php if (array_key_exists('lastLoginAt', $user)) { ?>
                        <li>
                            <strong class="bold-small">Last login time: </strong>
                            <span><?= $this->dateFormat($user['lastLoginAt'], 'Never logged in') ?></span>
                        </li>
                    <?php } ?>

                    <?php if (array_key_exists('failedLoginAttempts', $user)) { ?>
                        <li>
                            <strong class="bold-small">Number of failed login attempts: </strong>
                            <span><?= intval($user['failedLoginAttempts']); ?></span>
                        </li>
                    <?php } ?>

                    <?php if (array_key_exists('isDeleted', $user) && $user['isDeleted']) { ?>
                        <li>
                            <strong class="bold-small">Deleted on: </strong>
                            <span data-role="deletion-date"><?= $this->dateFormat($user['deletedAt'], 'Unknown') ?></span>
                        </li>
                        <li>
                            <strong class="bold-small">Due to: </strong>

                            <span data-role="deletion-reason">
                            <?php if ($user['reason'] == 'expired') { ?>
                                Account expired
                            <?php } elseif ($user['reason'] == 'unactivated') { ?>
                                User did not activate account
                            <?php } elseif ($user['reason'] == 'user-initiated') { ?>
                                User manually deleted their account
                            <?php } ?>
                            </span>
                        </li>
                    <?php } ?>

                    <?php if (array_key_exists('numberOfLpas', $user) && !is_null($user['numberOfLpas'])) { ?>
                        <li>
                            <strong class="bold-small">Number of LPAs: </strong>
                            <span><?= intval($user['numberOfLpas']); ?></span>
                        </li>
                    <?php } ?>
                </ul>
            </div>

        <?php } ?>

    </div>
</div>
