<?php $this->layout('layout::default', ['title' => 'User Details']);

$this->addErrorMap([
    'email' => [
        'required' => [
            'summary'   => 'Enter a valid email address',
            'field'     => 'Enter a valid email address',
        ],
        'invalid-email' => [
            'summary'   => 'Enter a valid email address',
            'field'     => 'Enter a valid email address',
        ],
    ],
]);
?>

<?php $this->insert('snippet::error-summary', ['form' => $form]) ?>

<form method="post" action="<?= $this->url('user.search') ?>">
    <?php $this->insert('snippet::input-hidden', ['formElement' => $form->get('secret')]) ?>

    <div class="govuk-form-group">
        <fieldset class="govuk-fieldset" role="group">
            <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
                <h1 class="govuk-fieldset__heading">
                    User Details
                </h1>
            </legend>

            <p class="govuk-body">Search for a user by email address. If found, the user's account status and other details will be displayed.</p>

            <?php $this->insert('snippet::input-text', [
                'formLabel'     => 'Email address',
                'formElement'   => $form->get('email'),
                'formType'      => 'text',
                'attrs'         => ['data-cy' => 'email-address-input'],
            ]) ?>
        </fieldset>
    </div>

    <button type="submit" class="govuk-button" data-module="govuk-button" data-cy="submit-button">
        Search
    </button>
</form>

<?php if (!is_null($user)) { ?>

    <h2 class="govuk-heading-m">User details</h2>

    <div class="govuk-summary-card" data-cy="user-summary-card">
        <div class="govuk-summary-card__title-wrapper">
            <h3 class="govuk-summary-card__title">
                <?php if (array_key_exists('username', $user)) { ?>
                    <?= htmlspecialchars($user['username']); ?>
                <?php } elseif (array_key_exists('isDeleted', $user) && $user['isDeleted']) { ?>
                    Deleted user
                <?php } ?>
            </h3>
        </div>
        <div class="govuk-summary-card__content">
            <dl class="govuk-summary-list">
                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key">
                        Account status
                    </dt>
                    <dd class="govuk-summary-list__value">
                        <span data-role="user-account-status">
                            <?php if (array_key_exists('isActive', $user)) { ?>
                                <?= ($user['isActive'] ? 'Activated' : 'Not activated'); ?>
                            <?php } elseif (array_key_exists('isDeleted', $user) && $user['isDeleted']) { ?>
                                Deleted
                            <?php } ?>
                        </span>
                    </dd>
                </div>

                <?php if (isset($user['activatedAt'])) { ?>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Date activated
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <span data-role="user-activation-date"><?= $this->dateFormat($user['activatedAt']) ?></span>
                        </dd>
                    </div>
                <?php } ?>

                <?php if (array_key_exists('lastLoginAt', $user)) { ?>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Last login time
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <span><?= $this->dateFormat($user['lastLoginAt'], 'Never logged in') ?></span>
                        </dd>
                    </div>
                <?php } ?>

                <?php if (array_key_exists('failedLoginAttempts', $user)) { ?>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Number of failed login attempts
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <span><?= intval($user['failedLoginAttempts']); ?></span>
                        </dd>
                    </div>
                <?php } ?>

                <?php if (array_key_exists('isDeleted', $user) && $user['isDeleted']) { ?>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Deleted on
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <span data-role="deletion-date"><?= $this->dateFormat($user['deletedAt'], 'Unknown') ?></span>
                        </dd>
                    </div>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Due to
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <span data-role="deletion-reason">
                                <?php if ($user['reason'] == 'expired') { ?>
                                    Account expired
                                <?php } elseif ($user['reason'] == 'unactivated') { ?>
                                    User did not activate account
                                <?php } elseif ($user['reason'] == 'user-initiated') { ?>
                                    User manually deleted their account
                                <?php } ?>
                            </span>
                        </dd>
                    </div>
                <?php } ?>

                <?php if (array_key_exists('numberOfLpas', $user) && !is_null($user['numberOfLpas'])) { ?>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Number of LPAs
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <span>
                                <?php if (intval($user['numberOfLpas']) > 0) { ?>
                                    <a data-role="user-lpa-count" class="govuk-link" href="<?= $this->url('user.lpas', ['id' => $user['userId']], ['email' => $user['username']]) ?>">
                                        <?= intval($user['numberOfLpas']); ?>
                                    </a>
                                <?php } else { ?>
                                    0
                                <?php } ?>
                            </span>
                        </dd>
                    </div>
                <?php } ?>
            </dl>
        </div>
    </div>

<?php } ?>
