<?php $this->layout('layout::default', ['title' => 'LPAs']) ?>

<?php if (!empty($failureReason)) { ?>
    <p class="govuk-body"><?= $failureReason; ?></p>
<?php } else { ?>
    <h1 class="govuk-heading-l">LPAs for <?= $lpasOwner; ?></h1>

    <?php if ($paginator->getOffsetLower() === $paginator->getOffsetUpper()) { ?>
        <p class="govuk-body">Showing LPA <?= $paginator->getOffsetLower(); ?> of <?= $paginator->getTotal(); ?> total LPAs</p>
    <?php } else { ?>
        <p class="govuk-body">Showing LPAs <?= $paginator->getOffsetLower(); ?> to <?= $paginator->getOffsetUpper(); ?> of <?= $paginator->getTotal(); ?> total LPAs</p>
    <?php } ?>

    <?php foreach ($lpas as $lpa) { ?>
        <div class="govuk-summary-card">
            <div class="govuk-summary-card__title-wrapper">
                <h2 class="govuk-summary-card__title">
                    <?= $lpa['id'] ?? 'Unknown ID'; ?>
                </h2>
            </div>
            <div class="govuk-summary-card__content">
                <dl class="govuk-summary-list">
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Started
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <?= isset($lpa['startedAt']) ? $this->dateFormat($lpa['startedAt']) : 'Not started yet'; ?>
                        </dd>
                    </div>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Updated
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <?= isset($lpa['updatedAt']) ? $this->dateFormat($lpa['updatedAt']) : 'Not updated yet'; ?>
                        </dd>
                    </div>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Completed
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <?php if (isset($lpa['completedAt'])) { ?>
                                <?= $this->dateFormat($lpa['completedAt']); ?>
                            <?php } else { ?>
                                Not created yet
                            <?php } ?>
                        </dd>
                    </div>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Created (when the LPA instrument is finished)
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <?php if (isset($lpa['createdAt'])) { ?>
                                <?= $this->dateFormat($lpa['createdAt']); ?>
                            <?php } else { ?>
                                Not created yet
                            <?php } ?>
                        </dd>
                    </div>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Locked
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <?php if (isset($lpa['lockedAt'])) { ?>
                                <?= $this->dateFormat($lpa['lockedAt']); ?>
                            <?php } else { ?>
                                LPA is not locked
                            <?php } ?>
                        </dd>
                    </div>
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            Payment
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <?php if (isset($lpa['payment']['method']) && $lpa['payment']['method'] === 'card') { ?>
                                Paid online on <?= $this->dateFormat($lpa['payment']['date']) ?? 'unknown date'; ?> under reference <?= $lpa['payment']['reference'] ?? 'unknown'; ?>
                            <?php } else if (isset($lpa['payment']['method']) && $lpa['payment']['method'] === 'cheque') { ?>
                                Paid with cheque on <?= $this->dateFormat($lpa['payment']['date']) ?? 'unknown date'; ?>
                            <?php } else { ?>
                                No payment information available
                            <?php } ?>
                        </dd>
                    </div>
                </dl>
            </div>
        </div>
    <?php } ?>

    <?php if ($paginator->getTotal() > $paginator->getPerPage()) { ?>
        <nav class="govuk-pagination" aria-label="Pagination">
            <div class="govuk-pagination__prev">
                <a class="govuk-link govuk-pagination__link" href="<?= $this->url($routeName, $routeParams, array_merge($queryParams, ['page' => $paginator->getPreviousPage()])) ?>" rel="prev">
                    <svg class="govuk-pagination__icon govuk-pagination__icon--prev" xmlns="http://www.w3.org/2000/svg" height="13" width="15" aria-hidden="true" focusable="false" viewBox="0 0 15 13">
                        <path d="m6.5938-0.0078125-6.7266 6.7266 6.7441 6.4062 1.377-1.449-4.1856-3.9768h12.896v-2h-12.984l4.2931-4.293-1.414-1.414z"></path>
                    </svg>
                    <span class="govuk-pagination__link-title">
            Previous<span class="govuk-visually-hidden"> page</span>
          </span>
                </a>
            </div>
            <ul class="govuk-pagination__list">
            <?php foreach($paginator->getPages() as $page) { ?>
                <li class="govuk-pagination__item <?php if ($page === $paginator->getPage()) { ?>govuk-pagination__item--current<?php } ?>">
                    <a class="govuk-link govuk-pagination__link" href="<?= $this->url($routeName, $routeParams, array_merge($queryParams, ['page' => $page])) ?>" aria-label="Page <?= $page; ?>" <?php if ($page === $paginator->getPage()) { ?>aria-current="page"<?php } ?>>
                        <?= $page; ?>
                    </a>
                </li>
            <?php } ?>
            </ul>
            <div class="govuk-pagination__next">
                <a class="govuk-link govuk-pagination__link" href="<?= $this->url($routeName, $routeParams, array_merge($queryParams, ['page' => $paginator->getNextPage()])) ?>" rel="next">
          <span class="govuk-pagination__link-title">
            Next<span class="govuk-visually-hidden"> page</span>
          </span>
                    <svg class="govuk-pagination__icon govuk-pagination__icon--next" xmlns="http://www.w3.org/2000/svg" height="13" width="15" aria-hidden="true" focusable="false" viewBox="0 0 15 13">
                        <path d="m8.107-0.0078125-1.4136 1.414 4.2926 4.293h-12.986v2h12.896l-4.1855 3.9766 1.377 1.4492 6.7441-6.4062-6.7246-6.7266z"></path>
                    </svg>
                </a>
            </div>
        </nav>
    <?php } ?>
<?php } ?>
