#!/bin/sh

rm -f /etc/php/7.0/fpm/conf.d/*xdebug*
rm -f /etc/php/7.0/cli/conf.d/*xdebug*

#These are here because at the moment the base image doesn't support xdebug
rm -f /etc/php/7.0/xdebug-enable.ini
rm -f /etc/php/7.0/xdebug-disable.ini

echo "zend_extension=xdebug.so" >> /etc/php/7.0/xdebug-enable.ini
echo "xdebug.default_enable=1" >> /etc/php/7.0/xdebug-enable.ini
echo "xdebug.max_nesting_level=200" >> /etc/php/7.0/xdebug-enable.ini
echo "xdebug.profiler_enable=0" >> /etc/php/7.0/xdebug-enable.ini
echo "xdebug.remote_autostart=1" >> /etc/php/7.0/xdebug-enable.ini
echo "xdebug.remote_connect_back=0" >> /etc/php/7.0/xdebug-enable.ini
echo "xdebug.remote_enable=1" >> /etc/php/7.0/xdebug-enable.ini
echo "xdebug.remote_handler=dbgp" >> /etc/php/7.0/xdebug-enable.ini
echo "xdebug.remote_mode=req" >> /etc/php/7.0/xdebug-enable.ini
echo "xdebug.remote_port=10000" >> /etc/php/7.0/xdebug-enable.ini
echo "xdebug.remote_log=/var/log/xdebug_remote.log" >> /etc/php/7.0/xdebug-enable.ini
echo "xdebug.idekey=API_DEBUG_SESSION" >> /etc/php/7.0/xdebug-enable.ini

echo ";zend_extension=xdebug.so" >> /etc/php/7.0/xdebug-disable.ini

if [ -n "${OPG_PHP_XDEBUG_REMOTE_HOST}" ]
then
    echo "Enabling PHP XDEBUG"
    cp /etc/php/7.0/xdebug-enable.ini /etc/php/7.0/fpm/conf.d/20-xdebug.ini
    echo "xdebug.remote_host=${OPG_PHP_XDEBUG_REMOTE_HOST}" >> /etc/php/7.0/fpm/conf.d/20-xdebug.ini
    cp /etc/php/7.0/xdebug-enable.ini /etc/php/7.0/cli/conf.d/20-xdebug.ini
    echo "xdebug.remote_host=${OPG_PHP_XDEBUG_REMOTE_HOST}" >> /etc/php/7.0/cli/conf.d/20-xdebug.ini
else
    echo "Disabling PHP XDEBUG - OPG_PHP_XDEBUG_REMOTE_HOST is not configured"
    cp /etc/php/7.0/xdebug-disable.ini /etc/php/7.0/fpm/conf.d/20-xdebug.ini
    cp /etc/php/7.0/xdebug-disable.ini /etc/php/7.0/cli/conf.d/20-xdebug.ini
fi