<section id="payment" class='section current'>

	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. Making payment online through Worldpay payment gateway</h2>
	
	<div class='accordion-content'>
	
		<div class="section-intro">
			
			<h3>Amount due: &pound;<?= $this->lpa->payment->amount ?></h3>
			
		</div>
		
		<h3>It appears you have chosen to cancel online payment. If you would like to choose an alternative payment method, please go to <a href="<?= $this->paymentUrl ?>">payment options page</a></h3>
		
		<div class="accordion-actions group">
			<p>
				<a href='<?= $this->paymentUrl ?>' class="button gotonextpart">Try again</a>
			</p>
		</div>
		
	</div>
	
</section>
