<section id="fee" class="section current">
    
    <h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. Payment</h2>

    <div class="accordion-content">
    
        <div class="section-intro">

            <h2>Reduced fee: £0</h2>
            
            <p>In order to apply for this exemption, you must enclose copies of letters from the DWP or your benefit provider confirming that the benefit is being paid at the time the LPA is sent to us for registration. <a class="js-guidance" href="/help/#topic-fees-and-reductions" data-journey-click="stageprompt.lpa:help:fees-and-reductions">Find out more about acceptable proof</a>.</p>
            
            <p>Insufficient evidence will result in delays to your application and if your claim is rejected you'll need to pay the rest of the fee.</p>
            
            <p>On the next page, you can download the application for remission form with the application to register form. Sign and date this and include it in your application.</p>
        
        </div>
        
		<div class="accordion-actions group">
			<p>
				<a href="<?=$this->nextRoute?>" class="button gotonextpart" role="button">Continue</a>
			</p>
		</div>
        
    </div>
    
</section>