<section id="payment" class='section current'>

	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. Making payment online through Worldpay payment gateway</h2>
	
	<div class='accordion-content'>
	
		<div class="section-intro">
			
			<h3>Amount due: &pound;<?= $this->lpa->payment->amount ?></h3>
			
		</div>
		
		<h3>Sorry, but there appears to be a problem with this payment. Please click the button below to try again. If the problem continues, visit <a href="http://www.worldpay.com/shopper/" target="_blank">WorldPay's support pages</a> for help.</h3>
		
		<h3>If you would like to choose an alternative payment method, please go to <a href="<?= $this->feeUrl ?>">payment options page</a></h3>
		
		<div class="accordion-actions group">
			<p>
				<a href='<?= $this->paymentUrl ?>' class="button gotonextpart">Try again</a>
			</p>
		</div>
		
	</div>
	
</section>
