<section id="fee" class="section current">
    
    <h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. Payment</h2>

    <div class="accordion-content">
    
        <div class="section-intro">

            <h2>We'll contact you about the fee</h2>
            <p>Because Universal Credit (UC) is in its trial phase and replaces several existing benefits, we're looking at remissions on a case-by-case basis.</p>
            <p>This means <strong>the tool will not charge you for this LPA now.</strong></p>
            <p>You must still send us the remissions form that you'll download on the next page, along with supporting evidence for your application. This should be a copy of the donor's benefit award letter. </p>
            <p>Once we receive your application, we'll contact you to let you know how much you'll have to pay and to arrange payment.</p>
        
        </div>
        
		<div class="accordion-actions group">
			<p>
				<a href="<?=$this->nextRoute?>" class="button gotonextpart" role="button">Continue</a>
			</p>
		</div>
        
    </div>
    
</section>