<?php
    $form = $this->formErrorTextExchange($this->form, []);
    
    $csrf       = $form->get($form->csrfName());
    
    $form->setAttributes(['class' => 'form']);
    
    $useNewPostcodeLookupMethod = $form->get('use-new-postcode-lookup-method');
    
    $useNewPostcodeLookupMethod->setAttributes(['id' => 'use-new-postcode-lookup-method']);
    
?>

<div style="min-height:600px">
	<h1>Postcode Lookup Method</h1>
    <?= $this->form()->openTag($form); ?>
        
    <?= $this->formElement($csrf)?>
    <?= $this->formElementErrors($csrf)?>
    
    <?= $this->formErrorList(); ?>
        
    If this box is checked, the MoJ DS postcode lookup service will be used. Otherwise, Postcode Anywhere will be used.
    <br>
    <?= $this->formElement($useNewPostcodeLookupMethod)?>
    <br>
                
	<input type="submit" class="button" value="Set postcode lookup method">
                
     <?= $this->form()->closeTag(); ?>
     
</div>