<?php
    $form = $this->formErrorTextExchange($this->form, []);
    
    $csrf       = $form->get($form->csrfName());
    
    $form->setAttributes(['class' => 'form']);
    
    $message      = $form->get('message');
    
    $message->setAttributes(['id' => 'message']);
    
    $message->setAttributes([
        'rows' => 4,
        'cols' => 80,
    ]);
    

?>

<div style="min-height:600px">
	<h1>System Message</h1>
    <?= $this->form()->openTag($form); ?>
        
    <?= $this->formElement($csrf)?>
    <?= $this->formElementErrors($csrf)?>
    
    <?= $this->formErrorList(); ?>
        
    <?= $this->formElement($message)?>
                
    <?= $this->formElementErrors($message)?>

	<input type="submit" class="button" value="Set system message">
                
     <?= $this->form()->closeTag(); ?>
     
</div>