
<h1>Terms and conditions and privacy policy</h1>

<p><strong>By using this digital lasting power of attorney (LPA) tool you agree to our privacy policy and to these terms and conditions. Please read them carefully.</strong></p>

<h2>Terms and conditions</h2>

<h3>General</h3>

<p>These terms and conditions affect your rights and liabilities under the law. They govern your use of, and relationship with, the digital LPA tool. They don’t apply to other Office of the Public Guardian (OPG) services, or to any other department or service which is linked to in this tool. </p>

<p>We may occasionally update these terms and conditions. This might happen if there’s a change in the law or to the way the tool works. If there’s a change, you’ll be asked to agree to the new terms and conditions the next time you sign in, so you can continue to use the tool. </p>

<p>If you don't agree to the terms and conditions and privacy policy set out in this document, you should not use this tool.</p>

<h3>Applicable law</h3>

<p>Your use of this tool and any dispute arising from its use will be governed by and construed in accordance with the laws of England and Wales, including but not limited to the:</p>

<ul>
<li>Computer Misuse Act 1990 </li>
<li>Data Protection Act 1998</li>
<li>Mental Capacity Act 2005</li>
</ul>

<h3>How to use this tool responsibly</h3>

<p>There are rules that apply to the creation and registration of an LPA that must be adhered to, as well as anything stated in this tool and these terms and conditions.</p>

<p>The tool is intended for use by a donor (the person the LPA is for), or by others on their behalf and only with their consent.</p>

<p>You must provide a valid email address and choose a password to create an account to use this tool. It’s your responsibility to keep your sign-in details safe. You shouldn’t share your password with anyone, or write it down. OPG is not responsible for any breach of information security due to password sharing. Choose a password that can’t be easily guessed.</p>

<p>There are risks in using a shared computer, such as in an internet café, to use this tool. It’s your responsibility to be aware of these risks and to avoid using any computer which may leave your personal information accessible to others. You are responsible if you choose to leave a computer unprotected while signed in to the tool.</p>

<p>We make every effort to check and test this tool whenever we amend or update it. However, you must take your own precautions to ensure that the way you access this tool does not expose you to the risk of viruses, malicious computer code or other forms of interference which may damage your own computer system.</p>

<p>You must not misuse our tool by knowingly introducing viruses, trojans, worms, logic bombs or other material which is malicious or technologically harmful. You must not attempt to gain unauthorised access to our tool, the system on which our tool is stored or any server, computer or database connected to our tool. You must not attack our site via a denial-of-service attack or a distributed denial-of-service attack.</p>

<h2>Privacy policy</h2>

<h3>Information provided by this tool</h3>

<p>OPG works hard to ensure that information within the tool is accurate. However, we can’t guarantee the accuracy and completeness of any information at all times. Guidance contained within this tool should not be considered legal advice. </p>

<p>This tool provides generic information to support you in making and applying to register LPAs. However, OPG can’t give legal advice on individual cases. You should answer questions within this tool based on consideration of the specific circumstances of the donor (the person the LPA is for), seeking advice from a legal professional if needed.</p>

<p>OPG is not responsible for the content or reliability of any linked services or websites, and does not necessarily endorse any views expressed within them.</p>

<p>While OPG makes every effort to ensure this tool is accessible at all times, we are not liable if the tool is unavailable for any period of time. </p>

<h3>How we use your information</h3>

<p>In order to use this tool, you will need to enter personal information relating to several living individuals. Such information includes names, addresses, other contact details, dates of birth, and the relationship of involved parties to the donor. We use this information to populate an application, and for no other purpose. OPG doesn't see what you’ve entered into the tool until your application reaches us through the post.</p>

<p>This tool contains several free-text fields in which you are invited to enter certain types of information. You should not enter sensitive information into these free-text fields unless absolutely necessary for your application. Sensitive information may include, but is not limited to, details of religious beliefs and financial information. Entering sensitive information into these fields is done at your own risk, and OPG is not liable for this.</p>

<p>Separately from the information entered by those using this tool, OPG also collects site-usage information from this tool, which allows us to see how the tool is being used in order to allow us to improve it. This information does not contain any personal data. </p>

<p>We’ll only ever collect information that will help us make the site work better for you; information that will let us contact you if you’ve asked us to, let us give you accurate information if you need it, and give us a sense of how people are using the tool, so we can keep improving it.</p>

<h3>How we keep your information safe</h3>

<p>The OPG takes data security very seriously and we take every step to ensure that your data remains private and secure. All data collected by this tool and stored in our secure database is kept entirely within the European Economic Area (EEA). </p>

<p>The postcode lookup functionality within this tool only returns information about the address in question. No other information is sent to, or returned from, this service.</p>

<p>Because of the global nature of the Internet infrastructure, however, we can't guarantee that information emailed from us will be kept within the EEA. By submitting your information you consent to such transfers outside the EEA.</p>

<p>We’ll never share your information with other organisations for marketing, market research or commercial purposes, and we don’t pass on your personal information to any other websites. </p>

<h3>Online payment</h3>

<p>By paying the non-refundable application fee online you are paying for your application to register an LPA to be processed by OPG. The registration process should usually be completed within 9 weeks of receipt of your application.</p>

<p>If you choose to pay the application fee online, you will be directed to our payment partner, WorldPay, for the payment to be processed. The details you give them will be encrypted, in line with the Payment Card Industry Data Security Standard (PCI-DSS). OPG won’t store any of your payment card details. OPG isn’t liable for any information you enter into WorldPay’s pages, or for the availability of the WorldPay site. To pay online you must abide by WorldPay’s terms and conditions, which you can read here along with some frequently asked questions:    </p>

<p><a href="http://support.worldpay.com/support/index.php?page=tandc" rel="external" target="_blank">WorldPay website terms and conditions</a></p>

<p><a href="https://support.worldpay.com/support/shopper/index.php?page=shopper-faq" rel="external" target="_blank">WorldPay shopper FAQs</a></p>

<h3>How we manage sessions</h3>

<p>This tool can be used to populate an LPA document and associated forms, through a user account that you create. When you’re signed in, personal information about you may be visible to anyone with access to your computer. You stay signed in until you sign out, or until 60 minutes elapse from the time you close or navigate away from the tool. This is in order to keep the tool secure.</p>

<p>Each time you sign out (including automatic sign-outs), the tool stores any information you’ve saved in a secure database, so you don’t have to enter it again.</p>

<p>We do not store any user data in cookies. However, your browser may store cookies while you're using the tool. You can manage cookie settings on your computer yourself.</p>

<h3>Data Protection Act 1998</h3>

<p>This tool complies with all principles of the DPA 1998.</p>

<p>Ministry of Justice (MoJ) is the 'data controller' for the purposes of the Act. However, the information you enter into the tool is not transmitted to OPG, but is stored in a secure database. OPG will only see the information you enter when the paper application reaches us. No personal data will be used in testing this tool.</p>

<p>You have the right, as owner of the account, to delete it, or any and all information in it at any point. We will keep data for 9 months from the date you last visited your account; before this you will be sent an email to ask whether you would like to keep or delete it. This is based on an assumption of 26 weeks for the user to complete an LPA application and send it to OPG, 9 weeks to process the application internally and a 4-week contingency period.</p>

<p>Our hosting provider, and MoJ staff responsible for supporting the tool, will have access to the secure database in which all personal information entered into this tool will be stored. All staff who have access to the secure data have MoJ security clearance.</p>

<p>Anyone who believes their personal data is kept within the tool has the right to submit a subject access request to the MoJ, who will give details of the information stored within the database.</p>

<p>If a subject access request shows that the information is inaccurate, the MoJ will amend or delete the information in the database as requested within 5 days. In these circumstances, we will warn the registered user first by email.</p>

<h3>Disclaimer</h3>

<p>We don’t accept liability for loss or damage incurred by users of this tool, whether direct, indirect or consequential, whether caused by tort, breach of contract or otherwise. This includes loss of income or revenue, business, profits or contracts, anticipated savings, data, goodwill, tangible property or wasted time in connection with this tool or any websites linked to it and any materials posted on it. This condition shall not prevent claims for loss of or damage to your tangible property or any other claims for direct financial loss that are not excluded by any of the categories set out above.</p>

<p>This does not affect our liability for death or personal injury arising from our negligence, nor our liability for fraudulent misrepresentation or misrepresentation as to a fundamental matter, nor any other liability which cannot be excluded or limited under applicable law.</p>

                        
