### Base image - contains dependencies required for build
FROM public.ecr.aws/lambda/python:3.8 AS base

COPY worker-requirements.txt /service-perfplat/

# Dependencies required to install psycopg2 (postgres driver)
# used in SQLAlchemy
RUN yum install -y gcc postgresql-devel

# Install Python dependencies for worker
RUN pip install -r /service-perfplat/worker-requirements.txt --target ${LAMBDA_TASK_ROOT}

### Final image - contains compiled dependencies
FROM public.ecr.aws/lambda/python:3.8

RUN yum install -y postgresql

COPY --from=base ${LAMBDA_TASK_ROOT} ${LAMBDA_TASK_ROOT}

# Copy lambda code to image
COPY perfplatworker /service-perfplat/perfplatworker
COPY perfplatcommon /service-perfplat/perfplatcommon

CMD ["/service-perfplat/perfplatworker/handler.exec"]