<footer class="group" id="footer" role="contentinfo">
  <div class="footer-wrapper">
    <div class="footer-meta">
      <div class="footer-meta-inner">
        <h2 class="visuallyhidden">Support links</h2>
        <ul>
          <li>Built by <a href="https://mojdigital.blog.gov.uk/">MOJ Digital Services</a></li>
        </ul>
        <div class="open-government-licence">
          <h2><a href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2">Open Government Licence</a></h2>
          <p>All content is available under the <a href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2">Open Government Licence v2.0</a>, except where otherwise stated</p>
        </div>
      </div>
      <div class="copyright">
        <a href="http://www.nationalarchives.gov.uk/information-management/our-services/crown-copyright.htm">© Crown copyright</a>
      </div>
    </div>
  </div>
</footer>