name: Set Secrets
description: Fetch secrets from AWS secrets manager and set them as masked environment variables

inputs:
  oidc_set_secrets_role:
    description: "OIDC role for fetching secrets from AWS secrets manager"
    required: true
  secrets_manager_secret_name:
    description: "Name of the aws secrets manager secret"
    required: true
outputs:
  masked_secret: ${{ steps.set_secret.outputs.masked_secret }}


runs:
  using: "composite"
  steps:
      - name: configure AWS credentials for getting pagerduty token
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ inputs.oidc_set_secrets_role }}
          aws-region: eu-west-1
          role-duration-seconds: 1800
          role-session-name: OPGLPAGetSecret

      - name: set secret as masked env var and output
        id: set_secret
        shell: bash
        run: |
          export masked_secret=$(aws secretsmanager get-secret-value --secret-id \
            ${{ inputs.secrets_manager_secret_name }} --region eu-west-1 | jq -r '.SecretString' 2>/dev/null)
          echo "::add-mask::$masked_secret"
          echo "masked_secret=$masked_secret" >> "$GITHUB_ENV"
          echo "masked_secret=$masked_secret" >> "$GITHUB_OUTPUT"
