<?php
    $form = $this->formErrorTextExchange($this->form, []);
    
    $form->setAttribute('class', 'form');
    $csrf        = $form->get('secret');
    
    $reductionOptions       = $form->get('reductionOptions');
    $reductionOptions->setLabelOptions(['disable_html_escape' => true]);
    $reductionOptionsValueOptions = $reductionOptions->getOptions()['value_options'];
    $reductionOptionsValueOptions['reducedFeeReceivesBenefits']['label'] = "The donor currently claims one of <a class=\"js-guidance\" href=\"/help/#topic-fees-and-reductions\" data-journey-click=\"stageprompt.lpa:help:fees-and-reductions\">these benefits</a>, but has not been awarded personal injury damages of more than £16,000";
    $reductionOptionsValueOptions['reducedFeeUniversalCredit']['label'] = "The donor receives Universal Credit";
    $reductionOptionsValueOptions['reducedFeeLowIncome']['label'] = "The donor currently has an income of less than £12,000 a year before tax";
    $reductionOptionsValueOptions['notApply']['label'] = "I'm not applying for a reduced fee";
    
    $reductionOptionsValueOptions['reducedFeeReceivesBenefits'] += [
            'label_attributes' => [
                    'for' => 'reducedFeeReceivesBenefits',
            ],
            'attributes' => [
                    'id' => 'reducedFeeReceivesBenefits'
            ],
    ];
    $reductionOptionsValueOptions['reducedFeeUniversalCredit'] += [
            'label_attributes' => [
                    'for' => 'reducedFeeUniversalCredit',
            ],
            'attributes' => [
                    'id' => 'reducedFeeUniversalCredit'
            ],
    ];
    $reductionOptionsValueOptions['reducedFeeLowIncome'] += [
            'label_attributes' => [
                    'for' => 'reducedFeeLowIncome',
            ],
            'attributes' => [
                    'id' => 'reducedFeeLowIncome'
            ],
    ];
    $reductionOptionsValueOptions['notApply'] += [
            'label_attributes' => [
                    'for' => 'notApply',
                    // @todo temporary inline style. use a class instead.
                    'style' => 'margin-top:30px;font-weight:bold;',
            ],
            'attributes' => [
                    'id' => 'notApply',
            ],
    ];
    
    $reductionOptions->setOptions(['value_options'=>$reductionOptionsValueOptions]);
    
    $submit      = $form->get('submit');
    $submit->setAttributes(['class'=>'button gotonextpart', 'value'=>'L do not want to apply reduction']);
    
    $formLabel   = $this->plugin('formLabel');
    $form->prepare();
?>

<section id="lpa-type" class="section current">
	
	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. Do you want to apply to pay a reduce fee?</h2>
	
    <div class="accordion-content">
    	<div class="section-intro">
                <p>If the donor has an income of less than £12,000 a year before tax or receives certain benefits, they might be eligible for a reduced fee, or no fee at all.</p>
                
                <p><a class="js-guidance" href="/help/#topic-fees-and-reductions" data-journey-click="stageprompt.lpa:help:fees-and-reductions">Find out more about qualifying for a reduction</a></p>
    	
		</div>
	    
    	
        <?= $this->form()->openTag($form); ?>
            
            <?= $this->formElement($csrf) ?>
            
            <?= $this->formErrorList(); ?>
            
            <div class="emphasised option group">
            
                <?= $formLabel->openTag($reductionOptions) . $reductionOptions->getOption('label') . $formLabel->closeTag(); ?>
                
                <?= $this->formElement($reductionOptions)?>
                
                <p class='form-element-errors'>
                    <?= $this->formElementErrors($reductionOptions) ?>
                </p>
            </div>
            
            <div class="accordion-actions">
				<p>
                    <input type="submit" name="save" value="Save and continue" class="button gotonextpart">
                </p>
            </div>
            
        <?= $this->form()->closeTag(); ?>
    	
    </div>
    
</section>