<h3 style="font-size: 19px; line-height: 1.315; font-weight: 700; margin: 38px 0 20px 0;">
    Contact us:
</h3>
<p style="font-size: 16px; line-height: 1.315; margin: 0 0 20px 0;">
    Email <a style="color: #005ea5" href="mailto:customerservices@PublicGuardian.gsi.gov.uk">customerservices@publicguardian.gsi.gov.uk</a>
</p>
<p style="font-size: 16px; line-height: 1.315; margin: 0 0 20px 0;">
    Call <strong>0300 456 0300</strong><br/>
    Monday to Friday (except Wednesday) 9am to 5pm<br/>
    Wednesday 10am to 5pm
</p>
<p style="font-size: 16px; line-height: 1.315; margin: 0 0 20px 0;">
    Textphone  <strong>0115 934 2778</strong>
</p>
<h3 style="font-size: 19px; line-height: 1.315; font-weight: 700; margin: 28px 0 10px 0;">
    Office of the Public Guardian
</h3>
<p style="font-size: 16px; line-height: 1.315; margin: 0 0 10px 0;">
    PO Box 16185, Birmingham B2 2WH
</p>
<p style="font-size: 16px; line-height: 1.315; margin: 0 0 10px 0;">
    <a style="color: #005ea5" href="www.lastingpowerofattorney.service.gov.uk">www.lastingpowerofattorney.service.gov.uk</a>
</p>