<html>
<head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">
    <title>Page title</title>
</head>
<body style="font-family: Helvetica, Arial, sans-serif; font-size: 16px; margin: 0; color:#0b0c0c">
​
<table width="100%" cellpadding="0" cellspacing="0" border="0">
    <tr>
        <td width="100%" height="53px" bgcolor="#0b0c0c">
            <table width="580" cellpadding="0" cellspacing="0" border="0" align="center">
                <tr>
                    <td width="100%" bgcolor="#0b0c0c" valign="middle">
                        <img src="https://neil-files-tmp.s3-eu-west-1.amazonaws.com/email-images/govuk-logo-v1.png" alt="GOV.UK" border="0">
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>