<div>
    <p>Email <a href='mailto:customerservices@PublicGuardian.gsi.gov.uk'>customerservices@PublicGuardian.gsi.gov.uk</a></p>
    <p>Call <strong>0300 456 0300</strong><br/>Monday to Friday (except Wednesday) 9am to 5pm<br/>Wednesday 10am to 5pm</p>
    <p>Textphone  <strong>0115 934 2778</strong></p>
</div>

<br/><br/>

<p><strong style="font-size:1.2em">Office of the Public Guardian</strong></p>
<p>PO Box 16185, Birmingham B2 2WH</p>
<p><a href="www.lastingpowerofattorney.service.gov.uk">www.lastingpowerofattorney.service.gov.uk</a></p>
