<?php
$messages = array_map(
        fn($v) => is_array($v) ? $v : [$v],
        ($messages ?? [])
);
foreach ($messages as $messageKey => $messageValues) { ?>
    <?php if ($messageKey === 'info') { ?>

        <div class="govuk-notification-banner" role="region" aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
            <div class="govuk-notification-banner__header">
                <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
                    Success
                </h2>
            </div>
            <div class="govuk-notification-banner__content">
                <?php foreach ($messageValues as $messageValue) { ?>
                    <p class="govuk-notification-banner__heading">
                        <?= $this->e($messageValue) ?>
                    </p>
                <?php } ?>
            </div>
        </div>

    <?php } ?>
<?php } ?>
