<?php
/*
Without error
Mandatory: formLabel
Optional: formHint (default: no span.form-hint outputted)
Optional: formLabelBold true|false (default: no wrapper span.form-label-bold outputted)
Optional: formType (default: text)
Optional: formSizeClass
*/

/**
 * @var \Laminas\Form\ElementInterface $formElement
 * @var string $formLabel
 * @var string $formType
 * @var array $attrs
 */

$formId = "id-{$formElement->getName()}";
$formName = $formElement->getName();

$formValue = $formElement->getValue();
if (is_null($formValue)) {
    $formValue = '';
}

$attrsString = '';
if(isset($attrs)) {
    $attrsString .= ' ';
    foreach ($attrs as $attrName => $attrValue) {
        $attrsString .= "$attrName=$attrValue ";
    }
}

if(isset($formSet)){
    $formId = "{$formId}-{$formSet}";
    $formName = "{$formSet}[{$formName}]";
}

$hasErrors = !empty($formElement->getMessages());
$hasParentErrors = isset($hasParentErrors) && $hasParentErrors;

$formGroup = 'govuk-form-group';
$formGroup .= ($hasErrors && !$hasParentErrors) ? ' govuk-form-group--error' : '';
$formGroup .= (isset($additionalFormGroupClasses)) ? " {$additionalFormGroupClasses}" : '';

$formControlClasses = $formType === 'textarea' ? 'govuk-textarea' : 'govuk-input';
$formControlClasses .= ($hasErrors) ? " govuk-input--error" : '';
?>

<div class="<?= $this->e($formGroup) ?>">
    <label class="govuk-label govuk-label--m" for="<?= $formId ?>">
        <?= $this->e($formLabel) ?>

        <?php if (!$hasParentErrors): ?>
            <?php foreach($formElement->getMessages() as $message): ?>
                <span class="govuk-error-message"><?=$this->e($this->fieldError($formElement->getName(), $message))?></span>
            <?php endforeach ?>
        <?php endif ?>
    </label>

    <?php if ($formType === 'textarea') { ?>
        <textarea <?= $this->e($attrsString) ?>class="<?= $this->e($formControlClasses) ?>" name="<?=$this->e($formName)?>" type="<?= $this->e($formType) ?>" id="<?= $formId ?>" rows="5"><?= $this->e($formValue) ?></textarea>
    <?php } else { ?>
        <input <?= $this->e($attrsString) ?>class="<?= $this->e($formControlClasses) ?>" name="<?=$this->e($formName)?>" type="<?= $this->e($formType) ?>" id="<?= $formId ?>" value="<?= (strtolower($formType) == 'password' ? '' : $this->e($formValue)) ?>">
    <?php } ?>
</div>
