<?php

$form = $this->formErrorTextExchange($this->form, []);

$form->setAttribute('class', 'form');

$email              = $form->get('email');
$password           = $form->get('password');

$email->setAttributes([
    'id' => 'email',
    'autocomplete' => 'off'
])->setOptions( ['label' => 'Email address'] );

$password->setAttributes([
    'id' => 'password_current',
    'autocomplete' => 'off'
])->setOptions( ['label' => 'Password'] );

$form->prepare();

//---

$formLabel = $this->plugin('formLabel');

?>
<p>Sign in or <a href="<?= $this->url('register') ?>">create an account</a> to get started.</p>

<div class="account form">

    <?= $this->form()->openTag( $form->setAttribute( 'class', 'form' ) ); ?>

        <?= $this->formElement($form->get('secret')) ?>
	
        <?php if ( $this->isTimeout ) : ?>
            <div class="validation-summary group" role="alert" aria-labelledby="error-heading" tabindex="-1">
              <h1 id="error-heading">Session timed out</h1>
              <p>Sorry, your session has timed out either due to inactivity or because you have signed in on another browser. Please log in again.</p>
            </div>
        <?php endif; // timed out ?>
        
        <? if ( !empty($authError)){  ?>
            <div class="validation-summary group" role="alert" aria-labelledby="error-heading" tabindex="-1">
              <h1 id="error-heading">There's been a problem logging in</h1>
                <? switch($authError){
                    case 'not-activated':
                        ?><p>Your account has not been activated. Click on the link in the email sent to you when you created the account.
                        If you haven't received an email, check your spam, bulk or junk email folder.</p><?
                        break;
                    case 'incorrect-4':
                        ?><p>Email and password combination not recognised. Did you click the link in the email we sent you to activate your account?</p>
                        <p>You can make 1 more attempt to sign in. If you enter the wrong details you won't be able to try again for 15 minutes. Forgotten your password? <a href="<?= $this->url('forgot-password'); ?>">Reset your password now</a>.</p><?
                        break;
                    case 'locked':
                        ?><p>This user account has been locked. Please go <a href="<?= $this->url('forgot-password'); ?>">here</a> to reset your password OR you can attempt again in 15 minutes.</p><?
                        break;
                    default:
                        ?><p><p>Email and password combination not recognised. Did you click the link in the email we sent you to activate your account? If so, please try logging in again below.</p></p><?
                        break;
                } ?>
            </div>
        <? } // error ?>

        <? if ( count($form->getMessages()) > 0) { ?>
            <div class="validation-summary group" role="alert" aria-labelledby="error-heading" tabindex="-1">
                <h1 id="error-heading">There was a problem submitting the form</h1>
                <p>Because of the following problems:</p>
                <ol>
                    <?php
                    $this->formLinkedErrorList($form);
                    ?>
                </ol>
            </div>
        <? } ?>

        <? $element = $email; ?>
        <div class="group">
            <?= $formLabel->openTag() . $element->getOption('label') . $formLabel->closeTag(); ?>
            <?= $this->formElement($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>


        <? $element = $password; ?>
        <div class="group">
            <?= $formLabel->openTag() . $element->getOption('label') . $formLabel->closeTag(); ?>
            <?= $this->formElement($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>

    	<p class="action group">
    	  <p class="action group">
             <input type="submit" name="submit" id="signin-form-submit" value="Sign in" class="button">
          </p>
        </p>

    <?= $this->form()->closeTag(); ?>

	<p class="action group">
        <a href="<?php echo $this->url('forgot-password'); ?>" type="submit" name="forgotpw" id="forgotpw-submit" class="link-style">Forgotten your password?</a>
    </p>
</div>
