<!DOCTYPE html>
<!--[if lt IE 9]><html class="lte-ie8" lang="en"><![endif]-->
<!--[if gt IE 8]><!-->

<html lang="en">
<!--<![endif]-->

    <?php echo $this->partial('partials/document/document-head.phtml'); ?>

    <?php echo $this->partial('partials/document/body/body-open.phtml'); ?>

            <?php echo $this->partial('partials/document/body/gov.uk/gov-uk-header.phtml'); ?>
            
            <?php echo $this->partial('partials/document/body/gov.uk/wrapper/gov-uk-wrapper-top.phtml'); ?>
			
            <?php echo $this->partial('partials/document/body/gov.uk/wrapper/gov-uk-section-header.phtml'); ?>

           
            <?= $this->accountInfo() ?>

	
                        
