<?php
    $routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getMatchedRouteName();
    $isHomepage = ($routeName == 'home');
?>

  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />

    <title><?= $isHomepage?'Make a lasting power of attorney':$this->pageTitle() ?> | GOV.UK</title>

    <script type="text/javascript">
  (function(){if(navigator.userAgent.match(/IEMobile\/10\.0/)){var d=document,c="appendChild",a=d.createElement("style");a[c](d.createTextNode("@-ms-viewport{width:auto!important}"));d.getElementsByTagName("head")[0][c](a);}})();
</script>

<!--[if gt IE 8]><!--><link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/application-a82ba1f455ff45927664ef45062f9cf7.css" media="screen" rel="stylesheet" type="text/css" /><!--<![endif]-->
<!--[if IE 6]><link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/application-ie6-4026ead82285bf16a3e06874a252876e.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
<!--[if IE 7]><link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/application-ie7-8b614a81fdb6afed53f5b2acc5351a9c.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
<!--[if IE 8]><link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/application-ie8-4bdfe7c675d5196a0236095948106fd6.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->


<link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/print-a250641f33ac06dba78975b0c65f8ac9.css" media="print" rel="stylesheet" type="text/css" />


    <!--[if IE 8]>
<script type="text/javascript">
  (function(){if(window.opera){return;}
  setTimeout(function(){var a=document,g,b={families:(g=
  ["nta"]),urls:["/assets/v1/assets-digital-cabinet-office-gov-uk-static/fonts-ie8-beb10cbc00c9b7dcdbdee824962bc5f6.css"]},
  c="/assets/v1/assets-digital-cabinet-office-gov-uk-static/libs/goog/webfont-debug-96870cf9f159ed811fd43c39bdf4656b.js",d="script",
  e=a.createElement(d),f=a.getElementsByTagName(d)[0],h=g.length;WebFontConfig
  ={custom:b},e.src=c,f.parentNode.insertBefore(e,f);for(;h=h-1;a.documentElement
  .className+=' wf-'+g[h].replace(/\s/g,'').toLowerCase()+'-n4-loading');},0)
  })()
</script>
<![endif]-->
<!--[if gte IE 9]><!-->
  <link href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/fonts-0fb6b917e34e45c93a44eec72dcc21de.css" media="all" rel="stylesheet" type="text/css" />
<!--<![endif]-->


    <!--[if lt IE 9]>
      <script src="/assets/v1/assets-digital-cabinet-office-gov-uk-static/ie-27ccded64045ab36dbfb67c2f47c362b.js" type="text/javascript"></script>
    <![endif]-->

    <link rel="shortcut icon" href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/favicon-447e4ac1ab790342660eacfe3dcce264.ico" type="image/x-icon" />

<!-- For third-generation iPad with high-resolution Retina display: -->
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/apple-touch-icon-144x144-4e306e01c31e237722b82b7aa7130082.png">
<!-- For iPhone with high-resolution Retina display: -->
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/apple-touch-icon-114x114-f1d7ccdc7b86d923386b373a9ba5e3db.png">
<!-- For first- and second-generation iPad: -->
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/apple-touch-icon-72x72-2ddbe540853e3ba0d30fbad2a95eab3c.png">
<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<link rel="apple-touch-icon-precomposed" href="/assets/v1/assets-digital-cabinet-office-gov-uk-static/apple-touch-icon-57x57-37527434942ed8407b091aae5feff3f3.png">

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="og:image" content="/assets/v1/assets-digital-cabinet-office-gov-uk-static/opengraph-image-4e469785ca4cc8f8dd18d0627bc43d19.png">
<meta name="description" content="Make a lasting power of attorney">
<meta content="Family" name="x-section-name">
<meta content="/browse/family" name="x-section-link">
<meta content="local_transaction" name="x-section-format">

<?php  echo $this->headMeta() ?>

<!--[if gt IE 8]><!--><link href="<?= $this->staticAssetPath('/assets/v1/css/styles.css') ?>" media="screen" rel="stylesheet" type="text/css" /><!--<![endif]-->
<!--[if IE 6]><link href="<?= $this->staticAssetPath('/assets/v1/css/ie6.css') ?>" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
<!--[if IE 7]><link href="<?= $this->staticAssetPath('/assets/v1/css/ie7.css') ?>" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
<!--[if IE 8]><link href="<?= $this->staticAssetPath('/assets/v1/css/ie8.css') ?>" media="screen" rel="stylesheet" type="text/css" /><![endif]-->

<!-- LPA Print styles -->
<link href="<?= $this->staticAssetPath('/assets/v1/css/print.css') ?>" media="print" rel="stylesheet" type="text/css" />

<?php echo $this->headLink()?>
</head>
