<?php
    /**
     * Switcher form
     */
    $switcherForm   = $this->switcherForm;
    $switcherForm->setAttribute('class', 'form');
    $sCsrf = $switcherForm->get($switcherForm->csrfName());
    $sCsrf->setAttributes(['id'=>'secret']);
    $switchTo = $switcherForm->get('switch-to-type');
    $switchTo->setAttributes(['id'=>'switch-to-type', 'class'=>'js-reusable']);
    $switchTo->setOptions([
            'label' => 'Use these details',
            'empty_option' => 'Choose a person',
    ]);
    
    $switchSubmit     = $switcherForm->get('submit');
    $switchSubmit->setAttributes(['value'=>'switch']);
    $switchFormLabel  = $this->plugin('formLabel');
    $switcherForm->prepare();
    
    /**
     * Correspondent form
     */
    $form       = $this->correspondentForm;
    $form->setAttribute('class', 'form js-PersonForm js-PostcodeLookup');
    
    $csrf       = $form->get($form->csrfName());
    $who        = $form->get('who');
    $title      = $form->get('name-title');
    $firstname  = $form->get('name-first');
    $lastname   = $form->get('name-last');
    $company    = $form->get('company');
    $address1   = $form->get('address-address1');
    $address2   = $form->get('address-address2');
    $address3   = $form->get('address-address3');
    $postcode   = $form->get('address-postcode');
    $email      = $form->get('email-address');
    $phone      = $form->get('phone-number');
    
    $who->setOptions(['label' => 'Role']);
    
    $title->setOptions( ['label' => 'Title'] );
    $title->setAttributes(['id'=>'name-title']);
    $firstname->setOptions( ['label' => 'First names'] );
    $lastname->setOptions( ['label' => 'Last name'] );
    $company->setOptions( ['label' => 'Company name'] );
    $address1->setOptions( ['label' => 'Address line 1'] );
    $address1->setAttributes(['id'=>'address-address1']);
    $address2->setOptions( ['label' => 'Address line 2'] );
    $address3->setOptions( ['label' => 'Address line 3'] );
    $postcode->setOptions( ['label' => 'Postcode'] );
    $email->setOptions( ['label' => "Email"] );
    $phone->setOptions( ['label' => "Daytime phone No."] );
    
    $submit     = $form->get('submit');
    $submit->setAttributes(['value'=>'Save and continue']);
    
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>
<h2 class="header">Edit the correspondent details</h2>

<?php ############################ switcher form ############################ ?>

<?= $this->form()->openTag($switcherForm); ?>

<?= $this->formElement($sCsrf) ?>
<?= $this->formErrorList($switcherForm); ?>

<div class="role-select group">
    <label for="switch-to-type" class="optional">Use these details</label>
    <?= $this->formSelect($switchTo) ?>
    <?= $this->formElementErrors($switchTo) ?>
    <input type="submit" name="switcher-submit" value="Switch" class="button details-picker"> 
</div>

<?= $this->form()->closeTag(); ?>

<?php ############################ corespondent form ############################ ?>

<?= $this->form()->openTag($form); ?>

<div class="<?= $this->elementGroupClass($csrf) ?>">
    <?= $this->formElement($csrf) ?>
    <?= $this->formElementErrors($csrf) ?>
</div>

<fieldset>

    <div class="form_element">
    
        <?= $formLabel->openTag() . $who->getOption('label') . $formLabel->closeTag(); ?>
        
        <?= $this->formElement($who) ?>
        
        <?= $this->formElementErrors($who) ?>
    
    </div>
    
    <div class="form_element">
    
        <?= $formLabel->openTag() . $title->getOption('label') . $formLabel->closeTag(); ?>
        
        <?= $this->formElement($title) ?>
        
        <?= $this->formElementErrors($title) ?>
    
    </div>
    
    
    <div class="form_element">
    
        <?= $formLabel->openTag() . $firstname->getOption('label') . $formLabel->closeTag(); ?>
        
         
        <?= $this->formElement($firstname) ?>
        
        <?= $this->formElementErrors($firstname) ?>
        
    </div>
    
    
    <div class="form_element">
    
        <?= $formLabel->openTag() . $lastname->getOption('label') . $formLabel->closeTag(); ?>
        
        <?= $this->formElement($lastname) ?>
        
        <?= $this->formElementErrors($lastname) ?>
    
    </div>

    <div class="form_element">
    
        <?= $formLabel->openTag() . $company->getOption('label') . $formLabel->closeTag(); ?>
        
        <?= $this->formElement($company) ?>
        
        <?= $this->formElementErrors($company) ?>
    
    </div>

</fieldset>

<fieldset class="js-PostcodeLookup__postal-add">

    <div class="form_element">
    
        <?= $formLabel->openTag() . $address1->getOption('label') . $formLabel->closeTag(); ?>
        
        <?= $this->formElement($address1) ?>
        
        <?= $this->formElementErrors($address1) ?>
        
    </div>
    
    
    <div class="form_element">
    
        <?= $formLabel->openTag() . $address2->getOption('label') . $formLabel->closeTag(); ?>
        
        <?= $this->formElement($address2) ?>
        
        <?= $this->formElementErrors($address2) ?>
        
    </div>
    
    
    <div class="form_element">
    
        <?= $formLabel->openTag() . $address3->getOption('label') . $formLabel->closeTag(); ?>
        
        <?= $this->formElement($address3) ?>
        
        <?= $this->formElementErrors($address3) ?>
    
    </div>
    
    
    <div class="form_element">
    
        <?= $formLabel->openTag() . $postcode->getOption('label') . $formLabel->closeTag(); ?>
        
        <?= $this->formElement($postcode) ?>
        
        <?= $this->formElementErrors($postcode) ?>
        
    </div>

</fieldset>

<fieldset>

    <div class="form_element">
    
        <?= $formLabel->openTag() . $email->getOption('label') . $formLabel->closeTag(); ?>
        
        <?= $this->formElement($email) ?>
        
        <?= $this->formElementErrors($email) ?>
    
    </div>
    
    <div class="form_element">
    
        <?= $formLabel->openTag() . $phone->getOption('label') . $formLabel->closeTag(); ?>
        
        <?= $this->formElement($phone) ?>
        
        <?= $this->formElementErrors($phone) ?>
    
    </div>

</fieldset>

<p class="action group">
<input type="submit" name="submit" id="form-save" value="Save details" class="button"> 
<button name="cancel" type="button" class="button-secondary">Cancel</button>
</p>

<?= $this->form()->closeTag(); ?>