<?php
    /**
     * Switcher form
     */
    $switcherForm   = $this->switcherForm;
    $switcherForm->setAttribute('class', 'form js-PostcodeLookup');
    $sCsrf          = $switcherForm->get('secret');
    $switchTo = $switcherForm->get('switch-to-type');
    $switchTo->setOptions([
            'label' => 'Use these details',
            'empty_option' => 'Choose a person',
    ]);
    
    $switchSubmit     = $switcherForm->get('submit');
    $switchSubmit->setAttributes(['value'=>'switch']);
    $switchFormLabel  = $this->plugin('formLabel');
    $switcherForm->prepare();
    
    /**
     * Correspondent form
     */
    $form       = $this->correspondentForm;
    $form->setAttribute('class', 'form js-PersonForm js-PostcodeLookup');
    
    $csrf       = $form->get('secret');
    $who        = $form->get('who');
    $title      = $form->get('name-title');
    $firstname  = $form->get('name-first');
    $lastname   = $form->get('name-last');
    $company    = $form->get('company');
    $address1   = $form->get('address-address1');
    $address2   = $form->get('address-address2');
    $address3   = $form->get('address-address3');
    $postcode   = $form->get('address-postcode');
    $email      = $form->get('email-address');
    $phone      = $form->get('phone-number');
    $contactByPost = $form->get('contactByPost');
    $contactInWelsh = $form->get('contactInWelsh');
    
    $title->setOptions( ['label' => 'Title'] );
    $firstname->setOptions( ['label' => 'First names'] );
    $lastname->setOptions( ['label' => 'Last names'] );
    $company->setOptions( ['label' => 'Company name'] );
    $address1->setOptions( ['label' => 'Address line 1'] );
    $address2->setOptions( ['label' => 'Address line 2'] );
    $address3->setOptions( ['label' => 'Address line 3'] );
    $postcode->setOptions( ['label' => 'Postcode'] );
    $email->setOptions( ['label' => "Email (optional)"] );
    $phone->setOptions( ['label' => "Daytime phone No."] );
    $contactByPost->setOptions( ['label' => "I prefer to be contacted by post", 'use_hidden_element' => false] );
    $contactByPost->setAttributes( ['id' => 'contactByPost'] );
    $contactInWelsh->setOptions( ['label' => "I prefer to be contacted in Welsh", 'use_hidden_element' => false,] );
    $contactInWelsh->setAttributes( ['id' => 'contactInWelsh'] );
    
    $submit     = $form->get('submit');
    $submit->setAttributes(['value'=>'Save and continue']);
    
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>
<h2 class="header">Edit the correspondent details</h2>

<?php ############################ switcher form ############################ ?>

<?= $this->form()->openTag($switcherForm); ?>

<?= $this->formElement($sCsrf) ?>
<?php if (count($switcherForm->getMessages()) > 0) $this->formElementErrors($sCsrf); ?>

<?= $this->formErrorList($switcherForm); ?>

<div class="role-select group">
    <label for="switch-to-type" class="optional">Use these details</label>
    <?= $this->formSelect($switchTo) ?>
    <?= $this->formElementErrors($switchTo) ?>
    <input type="submit" name="switcher-submit" value="Switch" class="button"> 
</div>

<?= $this->form()->closeTag(); ?>

<?php ############################ corespondent form ############################ ?>

<?= $this->form()->openTag($form); ?>

<div class="<?= $this->elementGroupClass($csrf) ?>">
    <?= $this->formElement($csrf) ?>
    <?= $this->formElementErrors($csrf) ?>
</div>

<fieldset>

<div class="form_element">

    <?= $formLabel->openTag() . $title->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formElement($title) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($title) ?>
    </p>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $firstname->getOption('label') . $formLabel->closeTag(); ?>
    
     
    <?= $this->formElement($firstname) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($firstname) ?>
    </p>
    
</div>


<div class="form_element">

    <?= $formLabel->openTag() . $lastname->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formElement($lastname) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($lastname) ?>
    </p>

</div>

</fieldset>

<div class="form_element">

    <?= $formLabel->openTag() . $company->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formElement($company) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($company) ?>
    </p>

</div>

<div class="form_element">

    <?= $formLabel->openTag() . $address1->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formElement($address1) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address1) ?>
    </p>
    
</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address2->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formElement($address2) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address2) ?>
    </p>
    
</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address3->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formElement($address3) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address3) ?>
    </p>
    
</div>


<div class="form_element">

    <?= $formLabel->openTag() . $postcode->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formElement($postcode) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($postcode) ?>
    </p>
    
</div>

<div class="form_element">

    <?= $formLabel->openTag() . $email->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formElement($email) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($email) ?>
    </p>

</div>

<div class="form_element">

    <?= $formLabel->openTag() . $phone->getOption('label') . $formLabel->closeTag(); ?>
    
    <?= $this->formElement($phone) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($phone) ?>
    </p>

</div>

<div class="form_element">
    
    <?= $formLabel->openTag($contactByPost) . $this->formElement($contactByPost) . $contactByPost->getOption('label') . $formLabel->closeTag(); ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($contactByPost) ?>
    </p>

</div>

<div class="form_element">

    <?= $formLabel->openTag($contactInWelsh) . $this->formElement($contactInWelsh) . $contactInWelsh->getOption('label') . $formLabel->closeTag(); ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($contactInWelsh) ?>
    </p>

</div>

<p class="action group">
<input type="submit" name="submit" id="form-save" value="Save details" class="button"> 
<button name="cancel" id="form-cancel" type="button" class="button-secondary">Cancel</button>
</p>

<?= $this->formhidden($who) ?>

<?= $this->form()->closeTag(); ?>