<?php 
$form = $this->formErrorTextExchange($this->form, []);

$csrf = $form->get('secret');
$form->prepare();

?>

<section id="correspondent" class="section current">
	
	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. Where should we send the LPA and any correspondence?</h2>

    <div class="accordion-content">
    
		<div class="section-intro">

			<p>We’ll normally write to the applicant if we have any questions and send them the LPA once we’ve registered it.</p>

            <p>However, you might prefer to choose someone else, such as a legal professional, to take care of these things.</p> 
            
            <p>If you want someone who isn't the applicant to receive the LPA and any related correspondence, enter their details below.</p>
            
            <p><a href="/help/#topic-correspondence-address" class="js-guidance" data-journey-click="stageprompt.lpa:help:correspondence-address">Find out more about the correspondence address</a></p>

    		<h3>Correspondence address</h3>
    		
		</div>

		<div class="person-summary group">
			<div class="person">
				<h3><?= $this->correspondent['name'] ?></h3>
				<p><?= $this->correspondent['address'] ?></p>
			</div>

			<ul class="actions">
				<li><a href="<?= $this->editRoute ?>" class="js-form-popup">Change this</a></li>
			</ul>
		</div>
        
        <?= $this->form()->openTag($form); ?>
        <?= $this->formElement($csrf) ?>
        <?= $this->formElementErrors($csrf) ?>
        
        <div class="accordion-actions">
			<p>
                <input type="submit" name="save" value="Save and continue" class="button gotonextpart">
            </p>
        </div>
        
        <?= $this->form()->closeTag(); ?>
            
    
    </div>
    
</section>