<?php
$form = $this->formErrorTextExchange($this->form, []);

$csrf = $form->get($form->csrfName());

$correspondence = $form->get('correspondence');

$contactByEmail = $correspondence->get('contactByEmail');
$contactByPhone = $correspondence->get('contactByPhone');
$contactByPost  = $correspondence->get('contactByPost');
$contactInWelsh = $correspondence->get('contactInWelsh');

$contactByPost->setOptions( ['label' => "Post", 'use_hidden_element' => true] );
$contactByPost->setAttributes( ['id' => 'contactByPost'] );

$contactByPhone->setOptions( ['label' => "Phone ".(($this->correspondent['contactPhone'])?'('.$this->correspondent['contactPhone'].')':'<a href="'.$this->editRoute.'" class="js-form-popup">Add phone number</a>'), 'use_hidden_element' => true] );
$contactByPost->setAttributes( ['id' => 'contactByPhone'] );

$contactByEmail->setOptions( ['label' => "Email ".(($this->correspondent['contactEmail'])?'('.$this->correspondent['contactEmail'].')':'<a href="'.$this->editRoute.'" class="js-form-popup">Add email address</a>'), 'use_hidden_element' => true] );
$contactByPost->setAttributes( ['id' => 'contactByEmail'] );

$contactInWelsh->setOptions( ['label' => "Welsh", 'use_hidden_element' => true] );
$contactInWelsh->setAttributes( ['id' => 'contactInWelsh'] );

$submit     = $form->get('submit');
$submit->setAttributes(['class'=>'button gotonextpart', 'value'=>'Save and continue']);

$formLabel  = $this->plugin('formLabel');
$form->prepare();

?>

<section id="correspondent-section" class="section current">

	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. Where should we send the LPA and any correspondence?</h2>

    <div class="accordion-content">

		<div class="section-intro">

			<p>We’ll normally write to the applicant if we have any questions and send them the LPA once we’ve registered it.</p>

            <p>However, you might prefer to choose someone else, such as a legal professional, to take care of these things.</p>

            <p>If you want someone who isn't the applicant to receive the LPA and any related correspondence, enter their details below.</p>

            <p><a href="/help/#topic-correspondence-address" class="js-guidance" data-journey-click="stageprompt.lpa:help:correspondence-address">Find out more about the correspondence address</a></p>

		</div>

		<h3>The Correspondent</h3>

		<div class="person-summary group">

		    <div class="person">
				<h3><?= $this->correspondent['name'] ?></h3>
				<p><?= $this->correspondent['address'] ?></p>
			</div>

			<ul class="actions">
				<li><a href="<?= $this->editRoute ?>" class="js-form-popup">Change this</a></li>
			</ul>
		</div>

        <h3>How would the person above prefer to be contacted?</h3>

        <?= $this->form()->openTag($form); ?>

        <?= $this->formElement($csrf) ?>
        <?= $this->formElementErrors($csrf) ?>

        <?= $this->formElementErrors($correspondence) ?>

        <fieldset style="clear:both;">

            <p>You can choose more than one.</p>

            <div class="option group">

                <?= $formLabel->openTag($contactByPost) . $this->formElement($contactByPost) . $contactByPost->getOption('label') . $formLabel->closeTag(); ?>

                <p class='form-element-errors'>
                    <?= $this->formElementErrors($contactByPost) ?>
                </p>

            </div>

            <div class="form_element">

                <?= $formLabel->openTag($contactByPhone) . $this->formElement($contactByPhone) . $contactByPhone->getOption('label') . $formLabel->closeTag(); ?>

                <p class='form-element-errors'>
                    <?= $this->formElementErrors($contactByPhone) ?>
                </p>

            </div>

            <div class="form_element">

                <?= $formLabel->openTag($contactByEmail) . $this->formElement($contactByEmail) . $contactByEmail->getOption('label') . $formLabel->closeTag(); ?>

                <p class='form-element-errors'>
                    <?= $this->formElementErrors($contactByEmail) ?>
                </p>

            </div>

            <div class="option group">

                <?= $formLabel->openTag($contactInWelsh) . $this->formElement($contactInWelsh) . $contactInWelsh->getOption('label') . $formLabel->closeTag(); ?>

                <p class='form-element-errors'>
                    <?= $this->formElementErrors($contactInWelsh) ?>
                </p>

            </div>

        </fieldset>

        <div class="accordion-actions">
			<p>
                <?= $this->formElement($submit) ?>
            </p>
        </div>

        <?= $this->form()->closeTag(); ?>


    </div>

</section>
