@startuml
title System Landscape

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  PackageBorderColor<<group>> #cccccc
  PackageFontColor<<group>> #cccccc
}

hide stereotype

skinparam person<<2>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<5>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
}
skinparam rectangle<<3>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
}
skinparam rectangle<<6>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
}
skinparam rectangle<<8>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam rectangle<<7>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
}
skinparam person<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<4>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
}

person "==User\n<size:10>[Person]</size>" <<1>> as 1
person "==Admin\n<size:10>[Person]</size>" <<2>> as 2
rectangle "==Digital take-up system/manual process\n<size:10>[Software System]</size>" <<3>> as 3
rectangle "==data.gov.uk website\n<size:10>[Software System]</size>" <<4>> as 4
rectangle "==Admin\n<size:10>[Software System]</size>" <<5>> as 5
rectangle "==Google Analytics\n<size:10>[Software System]</size>" <<6>> as 6
rectangle "==Make an LPA front-end\n<size:10>[Software System]</size>" <<7>> as 7
rectangle "==Make an LPA API with embedded Performance Platform\n<size:10>[Software System]</size>" <<8>> as 8

1 .[#707070,thickness=2].> 7 : "<color:#707070>Posts user satisfaction form"
7 .[#707070,thickness=2].> 8 : "<color:#707070>Posts user satisfaction data"
2 .[#707070,thickness=2].> 5 : "<color:#707070>Triggers generation of perf data"
4 .[#707070,thickness=2].> 8 : "<color:#707070>Gets perf data"
5 .[#707070,thickness=2].> 8 : "<color:#707070>Initiates generation of perf data"
8 .[#707070,thickness=2].> 3 : "<color:#707070>Gets digital take-up data"
8 .[#707070,thickness=2].> 6 : "<color:#707070>Gets completion rate data"
@enduml
