<?php if ($this->identity()) : ?>

<div class="js-toggle-nav" id="global-nav">

  <div class="inner">
    <nav role="navigation" class="content">
      <ul id="navigation">
        <?php if ( isset($this->name) && trim($this->name) != '') : ?>
          <li class="user"><?php echo $this->escapeHtml($this->name) ?>: </li>
        <?php endif; ?>
        <?php foreach ($this->links as $link) : ?> 
          <li><a href="<?php echo $link['url'] ?>"><?php echo $link['text'] ?></a></li>
        <?php endforeach; ?>
      </ul>
    </nav>
  </div>

</div>

<?php endif; ?>