#!/bin/bash

cd /app

while : ; do

    bin/lock acquire --table $OPG_LPA_COMMON_CRONLOCK_DYNAMODB_TABLE \
    --name db-migrate --ttl 60 \
    --endpoint $OPG_LPA_COMMON_DYNAMODB_ENDPOINT

    retval=$?

    if [ $retval -eq 0 ]; then
        # Acquired lock
        vendor/robmorgan/phinx/bin/phinx migrate
        break
    elif [ $retval -eq 1 ]; then
        # Lock not acquired
        break
    else
        echo "Error with lock system; will re-try"
        sleep 2
    fi

done

exit 0
