<?php if ($this->lastLogin) : ?>
<div style="float:right;">You were last signed in on <?= $this->lastLogin ?></div>
<?php endif; ?>

<?php if($this->message):?>
<h3><?php echo $this->message?></h3>
<?php else:?>
    <?php if( $this->lpas->getTotalItemCount() == 0 ): ?>
    <p>You haven't created any LPAs yet.</p>
    <?php else: ?>
    <p>These are all the LPAs that you've created.</p>
    <?php endif;?>
<?php endif;?>

  <div style="margin: 5px;" >
    <a class="add button" href='<?php echo $this->url('user/dashboard/create-lpa') ?>' role="button">Create a new LPA</a>
    <div style="float:right;">
        <form action="/user/dashboard" method="POST" >
             <input type="text" name="freeText" style="width: 215px; " placeholder="LPA no, donor first or last name" value="<?php echo isset($this->freeText) ? $this->freeText: ''; ?>" />
             <input class = "add button" type="submit" value="Search" name="search"/>
             <a class="add button" id="clear" href="<?php echo $this->url('user/dashboard'); ?>"> Clear </a>
        </form>
    </div>
  </div>
  
  <?php if ( $this->lpas->getTotalItemCount() > 0 ) : ?>
  <table id="savedforms" class="lpa-list">
  <thead>
  <tr>
    <th>ID</th>
    <th>Donor</th>
    <th>Type</th>
    <th>Progress</th>
    <th>Last saved on</th>
    <th>&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <?php foreach($this->lpas as $lpa): ?>
      <tr>
      <td><?= ( $lpa->version == 2 )? \Opg\Lpa\DataModel\Lpa\Formatter::id($lpa->id) : $lpa->id #v1Code ?></td>
      <td><?= $lpa->donor; ?></td>
      <td><?= ($lpa->type == 'property-and-financial') ? 'PF' : (($lpa->type == 'health-and-welfare')?'HW':'') ?></td>
      <td><?= ( $lpa->version == 2 )?$lpa->progress:$lpa->status ?></td>
      <td><?= $lpa->updatedAt->format('d/m/y'); ?></td>
      <td>
        <div class="lpa-actions">
        <a class="button" href="<?= ($lpa->version == 2)?("/lpa/".$lpa->id):("/forward/lpa/".sprintf("%010d", $lpa->id)) #v1Code ?>">Continue</a>
        <?= ($lpa->version == 2) ? '<a class="button" href="/lpa/' . $lpa->id . '/date-check">Dates</a>' : '' #v1Code ?>
        <?= ($lpa->version == 2) ? '<a class="button" href="'.$this->url( 'user/dashboard/create-lpa', [ 'lpa-id'=>$lpa->id ] ).'">Clone</a>' : '' #v1Code ?>
        <a class="button-warning delete-lpa" href="<?= ($lpa->version == 2)?("/user/dashboard/delete-lpa/".$lpa->id):("/service/delete/".sprintf("%010d", $lpa->id)) #v1Code ?>">Delete</a>
        </div>
      </td>
      </tr>
  <?php endforeach;?>
  
  </tbody>
  </table>

  <? /* Pagination HTML is in pagination.phtml */ ?>
  <?= $this->paginationControl($this->lpas, 'Sliding',  'pagination', ['route' => 'user/dashboard'] ); ?>

  <p>
<?php endif; ?>
  
  