<?php if ($this->lastLogin) : ?>
<div style="float:right;">You were last signed in on <?= $this->lastLogin ?></div>
<?php endif; ?>

<?php if($this->message):?>
<h3><?php echo $this->message?></h3>
<?php else:?>
    <?php if(empty($this->lpas)): ?>
    <p>You haven't created any LPAs yet.</p>
    <?php else: ?>
    <p>These are all the LPAs that you've created.</p>
    <?php endif;?>
<?php endif;?>

  <div style="margin: 5px;" >
    <a class="add button" href='<?php echo $this->url('user/dashboard/create-lpa') ?>' role="button">Create a new LPA</a>
    <div style="float:right;">
        <form action="/user/dashboard" method="POST" >
             <input type="text" name="freeText" style="width: 215px; " placeholder="LPA no, donor first or last name" value="<?php echo isset($this->freeText) ? $this->freeText: ''; ?>" />
             <input class = "add button" type="submit" value="Search" name="search"/>
             <a class="add button" id="clear" href="<?php echo $this->url('user/dashboard'); ?>"> Clear </a>
        </form>
    </div>
  </div>
  