
<?php if ($this->pageCount && $this->pageCount > 1): ?>
    <div class="pager">

        <div class="pager-controls">

        <?php if (isset($this->previous)): ?>
            <a class="pager-prev" href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">Prev</a>
        <?php endif; ?>

        <ul class="pager-items">
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('page' => $page)); ?>">
                        <?php echo $page; ?>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <?php echo $page; ?>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>

        <?php if (isset($this->next)): ?>
            <a class="pager-next" href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">Next</a>
        <?php endif; ?>

        </div>

        <div class="pager-summary">Showing <?php echo $this->current ?> – 50 of 146 LPAs</div>

    </div>

<?php endif; ?>
