<?php 
$form = $this->formErrorTextExchange($this->form, []);
$csrf = $form->get($form->csrfName());
$form->prepare();

?>

<section id="people-to-notify-section" class="section current">
	
	<h2 class="accordion-header"><?= $this->accordionIdx($this->lpa); ?>. Who should be told before your LPA is registered?</h2>

    <div class="accordion-content">
    
		<div class="section-intro">
			<p>It's a good idea to let people know when you apply to register your LPA. You can add up to 5 ‘people to notify’. Many donors just add 1 or 2.</p>
			<p>These people have a chance to raise any concerns before your LPA is registered, as a safeguard for you.</p>
			<p>However, you don't have to include any 'people to notify' for your LPA to be valid.</p>
			
			<p><a class="js-guidance" href="/help/#topic-people-to-be-told" data-journey-click="stageprompt.lpa:help:people-to-be-told">Find out more about 'people to notify'</a></p>
		</div>
		
        <?php if(count($this->peopleToNotify) > 0):?>
            
            <?= $this->partialloop('application/people-to-notify/partials/people-to-notify.phtml', $this->peopleToNotify)?>
            
            <?php if(isset($this->addRoute)):?>
                <p><a class="add button js-form-popup" data-form="notifiedperson1" href="<?= $this->addRoute ?>" role="button">Add another 'person to be told'</a></p>
            <?php endif;?>
            
        <?php else: ?>
        
		    <p><a class="add button js-form-popup" data-form="notifiedperson1" href="<?= $this->addRoute ?>" role="button">Add a 'person to be told'</a></p>
		    
        <?php endif;?>
        
    
        <?= $this->form()->openTag($form); ?>
        <?= $this->formElement($csrf) ?>
        <?= $this->formElementErrors($csrf) ?>
        
        <div class="accordion-actions">
			<p>
                <input type="submit" name="save" value="Save and continue" class="button gotonextpart">
            </p>
        </div>
        
        <?= $this->form()->closeTag(); ?>
            
    </div>
    
</section>
