<?php
    $csrf       = $form->get('secret');
    $form       = $this->form;
    $name       = $form->get('name');
    $companyNumber   = $form->get('number');
    $email      = $form->get('email-address');
    $address1   = $form->get('address-address1');
    $address2   = $form->get('address-address2');
    $address3   = $form->get('address-address3');
    $postcode   = $form->get('address-postcode');
    $submit     = $form->get('submit');
    
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>

<p>
    <a href="<?= $this->addAttorneyRoute ?>">Using an individual?</a>
</p>

<?= $this->form()->openTag($form); ?>

<div class="<?= $this->elementGroupClass($csrf) ?>">
    <?= $this->formElement($csrf) ?>
    <?= $this->formElementErrors($csrf) ?>
</div>

<div class="form_element">

    <?= $formLabel->openTag() . $name->getOption('label'); ?>
    
    <?= $this->formInput($name) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($name) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $companyNumber->getOption('label'); ?>
    
    <?= $this->formInput($companyNumber) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($companyNumber) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $email->getOption('label'); ?>
    
    <?= $this->formInput($email) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($email) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address1->getOption('label'); ?>
    
    <?= $this->formInput($address1) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address1) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address2->getOption('label'); ?>
    
    <?= $this->formInput($address2) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address2) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address3->getOption('label'); ?>
    
    <?= $this->formInput($address3) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address3) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $postcode->getOption('label'); ?>
    
    <?= $this->formInput($postcode) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($postcode) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $this->formInput($submit) ?>

</div>

<?= $this->form()->closeTag(); ?>