<?php
    $form       = $this->form;
    $csrf       = $form->get('secret');
    $name       = $form->get('name');
    $companyNumber   = $form->get('number');
    $email      = $form->get('email-address');
    $address1   = $form->get('address-address1');
    $address2   = $form->get('address-address2');
    $address3   = $form->get('address-address3');
    $postcode   = $form->get('address-postcode');

    $name->setOptions( ['label' => 'Company name'] );
    $companyNumber->setOptions( ['label' => 'Registration No.'] );
    $email->setOptions( ['label' => 'Email address'] );
    $address1->setOptions( ['label' => 'Address line 1'] );
    $address2->setOptions( ['label' => 'Address line 2'] );
    $address3->setOptions( ['label' => 'Address line 3'] );
    $postcode->setOptions( ['label' => 'Postcode'] );
    
    $submit     = $form->get('submit');
    $submit->setAttributes(['value'=>'Save and continue']);
        
    $formLabel  = $this->plugin('formLabel');
    $form->prepare();
?>

<p>
    <a href="<?= $this->addAttorneyRoute ?>">Using an individual?</a>
</p>

<?= $this->form()->openTag($form); ?>

<div class="<?= $this->elementGroupClass($csrf) ?>">
    <?= $this->formElement($csrf) ?>
    <?= $this->formElementErrors($csrf) ?>
</div>

<div class="form_element">

    <?= $formLabel->openTag() . $name->getOption('label'); ?>
    
    <?= $this->formElement($name) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($name) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $companyNumber->getOption('label'); ?>
    
    <?= $this->formElement($companyNumber) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($companyNumber) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $email->getOption('label'); ?>
    
    <?= $this->formElement($email) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($email) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address1->getOption('label'); ?>
    
    <?= $this->formElement($address1) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address1) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address2->getOption('label'); ?>
    
    <?= $this->formElement($address2) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address2) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $address3->getOption('label'); ?>
    
    <?= $this->formElement($address3) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($address3) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $formLabel->openTag() . $postcode->getOption('label'); ?>
    
    <?= $this->formElement($postcode) ?>
    
    <p class='form-element-errors'>
        <?= $this->formElementErrors($postcode) ?>
    </p>
    
    <?= $formLabel->closeTag() ?>

</div>


<div class="form_element">

    <?= $this->formElement($submit) ?>

</div>

<?= $this->form()->closeTag(); ?>