name: "[Workflow] Run Smoke Tests"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    outputs:
      smoke_test_status:
        description: "The status of the smoke tests"
        value: ${{ steps.run_smoke_tests.outputs.smoke_test_status }}

permissions:
  contents: read
  security-events: read
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  run_smoke_tests:
    runs-on: ubuntu-latest
    outputs:
      smoke_test_status: ${{ steps.smoke_tests.outputs.smoke_test_status }}
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0

      - name: Download Terraform Task definition
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # pin@v3.0.1
        with:
          name: terraform-artifact
          path: /tmp/

      - name: Setup Python
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # pin@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/pipeline/requirements.txt

      - name: Run smoke tests
        id: smoke_tests
        run: |
          if python scripts/pipeline/healthcheck_test/healthcheck_test.py; then
            echo "smoke_test_status=passed" >> $GITHUB_OUTPUT
          else
            echo "smoke_test_status=failed" >> $GITHUB_OUTPUT
          fi
