name: "[Analysis] TFSec PR feedback"

on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.tf"

permissions:
  actions: read
  checks: read
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  tfsec_pr_commenter:
    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-infrastructure-tfsec-pr-feedback.yml@361d19a6d7b291dab5d46f04765239341a4ca86b # v3.16.0
    with:
      terraform_path: "['terraform/account', 'terraform/region', 'terraform/environment']"
    secrets:
      source_github_token: "${{ secrets.GITHUB_TOKEN }}"
