name: phpcs analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  security-events: write
  checks: write

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run phpcs
        id: phpcs
        run: make dc-phpcs-check
      - name: Publish PHPCS as PR annotations
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: docker compose run --rm --no-deps --entrypoint=vendor/bin/cs2pr phpcs /app/output/phpcs-report.xml
