name: phpcs analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  security-events: write
  checks: write

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Run phpcs
        id: phpcs
        run: make dc-phpcs-check
      - name: Publish PHPCS as PR annotations
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: docker compose run --rm --no-deps --entrypoint=vendor/bin/cs2pr phpcs /app/output/phpcs-report.xml
