name: Psalm analysis

on: workflow_call

permissions:
  security-events: write

jobs:
  psalm:
    name: psalm-scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scan:
          - name: service-admin
            service: admin-app-test
          - name: service-front
            service: front-app-test
          - name: service-api
            service: api-app-test
          - name: shared
            service: shared-test
          - name: service-pdf
            service: pdf-app-test
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: ${{ matrix.scan.service }}
          path: /tmp/images
      - name: Load Images
        run: |
          docker load -i /tmp/images/image.tar

      - name: Run Psalm
        run: |
          mkdir -m 0777 ./output
          docker compose run --rm \
            --volume ./output:/tmp/output \
            ${{ matrix.scan.service }} \
            vendor/bin/psalm --report=/tmp/output/psalm-results.sarif --no-cache
      - name: Add prefix to Psalm paths
        if: always()
        run: |
          sed -i 's|"uri":"|"uri":"${{ matrix.scan.name }}\/|g' ./output/psalm-results.sarif
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@014f16e7ab1402f30e7c3329d33797e7948572db # v4.31.3
        if: always()
        with:
          sarif_file: ./output/psalm-results.sarif
          category: psalm-${{ matrix.scan.name }}
