name: "[Workflow] Cypress Tests"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      account_id:
        description: "AWS account ID containing the role to assume for boto commands"
        required: true
        type: string
      admin_url:
        description: "URL of the admin frontend"
        required: true
        type: string
      front_url:
        description: "URL of the frontend"
        required: true
        type: string
      cypress_tags:
        description: "Cypress tags to run"
        required: true
        type: string
      visual_regression_enabled:
        description: "Toggle visual regression testing"
        required: false
        type: string
        default: "0"
      oidc_ingress_management_role:
        description: "OIDC role to assume for ingress management permissions"
        required: true
        type: string

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Configure AWS Credentials - Ingress Management
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_ingress_management_role }}
          role-duration-seconds: 900
          role-session-name: OPGLPACypressTestsSecurityGroupStart

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          version: "0.11.21"
          python-version: "3.14.5"
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        working-directory: scripts/pipeline/ci_ingress
        run: uv sync --locked

      - name: Download Terraform Task definition
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: terraform-artifact
          path: /tmp/

      - name: Add GitHub Actions runner Ingress Rule
        run: |
          uv run --directory scripts/pipeline/ci_ingress python ci_ingress.py /tmp/environment_pipeline_tasks_config.json --add

      - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: node-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: ".nvmrc"

      - name: Run Cypress Tests - ${{ inputs.cypress_tags }}
        env:
          CYPRESS_adminUrl: ${{ inputs.admin_url }}
          CYPRESS_baseUrl: ${{ inputs.front_url }}
          CYPRESS_visualRegressionEnabled: ${{ inputs.visual_regression_enabled }}
          CYPRESS_TAGS: ${{ inputs.cypress_tags }}
        run: |
          pushd cypress ; python3 stitch.py ; popd
          sed -i -e "s|https://front-ssl|${CYPRESS_baseUrl}|g" docker-compose.yml
          sed -i -e "s|https://admin-ssl|${CYPRESS_adminUrl}|g" docker-compose.yml
          CYPRESS_userNumber=`python3 cypress/user_number.py`
          docker compose run --rm -e CYPRESS_userNumber=$CYPRESS_userNumber -e CYPRESS_NO_COMMAND_LOG=1 -e CYPRESS_numTestsKeptInMemory=1 cypress --headless --config video=false --expose visualRegressionEnabled="${CYPRESS_visualRegressionEnabled}" -e stepDefinitions="/app/cypress/e2e/common/*.js",filterSpecs="true",GLOB="cypress/e2e/**/*.feature",CI="True",TAGS="@Signup"
          docker compose run --rm -e CYPRESS_userNumber=$CYPRESS_userNumber -e CYPRESS_NO_COMMAND_LOG=1 -e CYPRESS_numTestsKeptInMemory=1 cypress --headless --config video=false --expose visualRegressionEnabled="${CYPRESS_visualRegressionEnabled}" -e stepDefinitions="/app/cypress/e2e/common/*.js",filterSpecs="true",GLOB="cypress/e2e/**/*.feature",CI="True",TAGS="${CYPRESS_TAGS}"

      - name: Upload Screenshot Artifact
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cypress-screenshots (${{ inputs.cypress_tags }})
          path: cypress/screenshots/

      - name: Upload Diff Artifact
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cypress-diffs (${{ inputs.cypress_tags }})
          path: cypress/regressions/diff

      - name: Configure AWS Credentials - Ingress Management
        if: always()
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_ingress_management_role }}
          role-duration-seconds: 900
          role-session-name: OPGLPACypressTestsSecurityGroupEnd

      - name: Remove GitHub Actions runner Ingress Rule
        if: always()
        run: |
          uv run --directory scripts/pipeline/ci_ingress python ci_ingress.py /tmp/environment_pipeline_tasks_config.json
