name: "[Docker] Build and Push Images"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag for docker images"
        required: true
        type: string
      oidc_docker_role:
        description: "OIDC role to assume for ECR permissions"
        required: true
        type: string
      otel_scan_required:
        description: "Fail workflow when OTEL Snyk scan fails"
        required: false
        type: boolean
        default: false
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      SNYK_OPG_ORG_TOKEN:
        required: true

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  docker_build_scan_push:
    name: "Build and scan ${{ matrix.image_name }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: online-lpa/front_app
            snyk_policy_path: service-front/docker/app/.snyk
            build_options: "--file ./service-front/docker/app/Dockerfile"
            scan_id: front_app

          - image_name: online-lpa/front_web
            snyk_policy_path: service-front/docker/web/.snyk
            build_options: "--file ./service-front/docker/web/Dockerfile"
            cli_commands: "docker compose run --rm npm-front ci --ignore-scripts && docker compose run --rm npm-front run build"
            scan_id: front_web

          - image_name: online-lpa/api_app
            snyk_policy_path: service-api/docker/app/.snyk
            build_options: "--file ./service-api/docker/app/Dockerfile"
            scan_id: api_app

          - image_name: online-lpa/api_web
            snyk_policy_path: service-api/docker/web/.snyk
            build_options: "--file ./service-api/docker/web/Dockerfile"
            scan_id: api_web

          - image_name: online-lpa/admin_app
            snyk_policy_path: service-admin/docker/app/.snyk
            build_options: "--file ./service-admin/docker/app/Dockerfile"
            scan_id: admin_app

          - image_name: online-lpa/admin_web
            snyk_policy_path: service-admin/docker/web/.snyk
            build_options: "--file ./service-admin/docker/web/Dockerfile"
            scan_id: admin_web

          - image_name: online-lpa/pdf_app
            snyk_policy_path: service-pdf/docker/app/.snyk
            build_options: "--file ./service-pdf/docker/app/Dockerfile"
            scan_id: pdf_app

          - image_name: online-lpa/seeding_app
            snyk_policy_path: service-seeding/docker/app/.snyk
            build_options: "--file ./service-seeding/docker/app/Dockerfile"
            scan_id: seeding_app

          - image_name: lambda-aurora_scheduler
            snyk_policy_path: aurora-scheduler/docker/.snyk
            build_options: "--file ./aurora-scheduler/docker/Dockerfile"
            image_tag: latest
            scan_id: aurora_scheduler

          - image_name: lpa-admin-app-test
            snyk_policy_path: service-admin/docker/app/.snyk
            build_options: "--file ./service-admin/docker/app/Dockerfile --build-arg ENABLE_XDEBUG=1"
            build_target: test-runner
            artifact_name: admin-app-test
            build_targets: '[{"actions_runner":"ubuntu-latest","platform":"linux/amd64","tag":"AMD64"}]'
            scan_id: admin_app_test

          - image_name: lpa-api-app-test
            snyk_policy_path: service-api/docker/app/.snyk
            build_options: "--file ./service-api/docker/app/Dockerfile --build-arg ENABLE_XDEBUG=1"
            build_target: test-runner
            artifact_name: api-app-test
            build_targets: '[{"actions_runner":"ubuntu-latest","platform":"linux/amd64","tag":"AMD64"}]'
            scan_id: api_app_test

          - image_name: lpa-front-app-test
            snyk_policy_path: service-front/docker/app/.snyk
            build_options: "--file ./service-front/docker/app/Dockerfile --build-arg ENABLE_XDEBUG=1"
            build_target: test-runner
            artifact_name: front-app-test
            build_targets: '[{"actions_runner":"ubuntu-latest","platform":"linux/amd64","tag":"AMD64"}]'
            scan_id: front_app_test

          - image_name: lpa-pdf-app-test
            snyk_policy_path: service-pdf/docker/app/.snyk
            build_options: "--file ./service-pdf/docker/app/Dockerfile --build-arg ENABLE_XDEBUG=1 --build-arg VISUAL_TESTS=true"
            build_target: test-runner
            artifact_name: pdf-app-test
            build_targets: '[{"actions_runner":"ubuntu-latest","platform":"linux/amd64","tag":"AMD64"}]'
            scan_id: pdf_app_test

          - image_name: lpa-shared-test
            snyk_policy_path: shared/docker/test-runner/.snyk
            build_options: "--file ./shared/docker/test-runner/Dockerfile"
            build_target: test-runner
            artifact_name: shared-test
            build_targets: '[{"actions_runner":"ubuntu-latest","platform":"linux/amd64","tag":"AMD64"}]'
            scan_id: shared_test
    uses: ministryofjustice/opg-github-workflows/.github/workflows/test-multi-build-scan-push-workflow.yml@07d14074522cb423c2879b92ac5ca9b17ce69a88 # PR 167
    with:
      image_name: ${{ format('311462405659.dkr.ecr.eu-west-1.amazonaws.com/{0}', matrix.image_name) }}
      image_tag: ${{ matrix.image_tag || inputs.tag }}
      artifact_name: ${{ matrix.artifact_name || '' }}
      build_targets: ${{ matrix.build_targets || '[{"actions_runner":"ubuntu-latest","platform":"linux/amd64","tag":"AMD64"}]' }}
      build_target: ${{ matrix.build_target || '' }}
      build_options: ${{ matrix.build_options }}
      cli_commands: ${{ matrix.cli_commands || '' }}
      enable_snyk_scanning: true
      image_display_name: ${{ matrix.image_name }}
      snyk_policy_path: ${{ matrix.snyk_policy_path || '' }}
      snyk_container_options: "--severity-threshold=high"
      aws_region: eu-west-1
      oidc_role_to_assume_build: ${{ inputs.oidc_docker_role }}
      oidc_role_to_assume_push: ${{ inputs.oidc_docker_role }}
      snyk_ecr_registry_id: "311462405659"
      snyk_image: "shared/snyk:main-cli-1.1303.2-v0.3.0"
      job_name: "Docker build, scan and push"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}


# name: "[Docker] Build and Push Images"
#
# defaults:
#   run:
#     shell: bash
#
# on:
#   workflow_call:
#     inputs:
#       tag:
#         description: "Tag for docker image"
#         required: true
#         type: string
#       oidc_docker_role:
#         description: "OIDC role to assume for ecr permissions"
#         required: true
#         type: string
#       otel_scan_required:
#         description: "Fail workflow when OTEL Snyk scan fails"
#         required: false
#         type: boolean
#         default: false
#     secrets:
#       SLACK_BOT_TOKEN:
#         required: true
#       SNYK_OPG_ORG_TOKEN:
#         required: true
#
# permissions:
#   actions: none
#   checks: none
#   contents: write
#   deployments: none
#   id-token: write
#   issues: none
#   packages: none
#   pull-requests: read
#   repository-projects: none
#   security-events: write
#   statuses: none
#
# jobs:
#   otel_image_pull_and_scan:
#     name: "OTEL_Image_Pull_and_Scan"
#     runs-on: ubuntu-latest
#     env:
#       otel_image_version: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/aws-otel-collector-public-ecr/aws-observability/aws-otel-collector:v0.48.0
#     steps:
#       - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
#         with:
#           persist-credentials: false
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
#         with:
#           aws-region: eu-west-1
#           role-to-assume: ${{ inputs.oidc_docker_role }}
#           role-duration-seconds: 3600
#           role-session-name: OPGMakeaLPAECRGithubAction
#       - name: ECR Login
#         uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
#         with:
#           registries: 311462405659
#       - name: Pull OTEL image into ECR cache
#         run: docker pull $otel_image_version
#       - name: Scan OTEL image with SNYK
#         uses: ministryofjustice/opg-github-actions/actions/snyk-scan@722a5f955424aaba01e9ca43d68390cd4048d6e1 # v4.10.2
#         with:
#           SNYK_TEST_IMAGE: ${{ env.otel_image_version }}
#           SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
#           sarif_filepath: ./test-results
#           sarif_filename: otel_snyk.sarif
#           snyk_test_args: --severity-threshold=high
#
#   docker_build_scan_push:
#     name: "docker build"
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         include:
#           - image_name: online-lpa/front_app
#             dockerfile_path: ./service-front/docker/app
#             snyk_policy_path: service-front/docker/app/.snyk
#             scan_id: front_app

#           - image_name: online-lpa/front_web
#             dockerfile_path: ./service-front/docker/web
#             snyk_policy_path: service-front/docker/web/.snyk
#             scan_id: front_web

#           - image_name: online-lpa/api_app
#             dockerfile_path: ./service-api/docker/app
#             snyk_policy_path: service-api/docker/app/.snyk
#             scan_id: api_app

#           - image_name: online-lpa/api_web
#             dockerfile_path: ./service-api/docker/web
#             snyk_policy_path: service-api/docker/web/.snyk
#             scan_id: api_web

#           - image_name: online-lpa/admin_app
#             dockerfile_path: ./service-admin/docker/app
#             snyk_policy_path: service-admin/docker/app/.snyk
#             scan_id: admin_app

#           - image_name: online-lpa/admin_web
#             dockerfile_path: ./service-admin/docker/web
#             snyk_policy_path: service-admin/docker/web/.snyk
#             scan_id: admin_web

#           - image_name: online-lpa/pdf_app
#             dockerfile_path: ./service-pdf/docker/app
#             snyk_policy_path: service-pdf/docker/app/.snyk
#             scan_id: pdf_app

#           - image_name: online-lpa/seeding_app
#             dockerfile_path: ./service-seeding/docker/app
#             snyk_policy_path: service-seeding/docker/app/.snyk
#             scan_id: seeding_app

#           - image_name: lambda-aurora_scheduler
#             dockerfile_path: ./aurora-scheduler/docker
#             snyk_policy_path: aurora-scheduler/docker/.snyk
#             scan_id: aurora_scheduler
#             override_tag: latest

#           - image_name: lpa-admin-app-test
#             dockerfile_path: ./service-admin/docker/app
#             dockerfile_target: test-runner
#             snyk_policy_path: service-admin/docker/app/.snyk
#             scan_id: admin_app_test
#             archive_name: admin-app-test
#             with_xdebug: true

#           - image_name: lpa-api-app-test
#             dockerfile_path: ./service-api/docker/app
#             dockerfile_target: test-runner
#             snyk_policy_path: service-api/docker/app/.snyk
#             scan_id: api_app_test
#             archive_name: api-app-test
#             with_xdebug: true

#           - image_name: lpa-front-app-test
#             dockerfile_path: ./service-front/docker/app
#             dockerfile_target: test-runner
#             snyk_policy_path: service-front/docker/app/.snyk
#             scan_id: front_app_test
#             archive_name: front-app-test
#             with_xdebug: true

#           - image_name: lpa-pdf-app-test
#             dockerfile_path: ./service-pdf/docker/app
#             dockerfile_target: test-runner
#             snyk_policy_path: service-pdf/docker/app/.snyk
#             scan_id: pdf_app_test
#             archive_name: pdf-app-test
#             with_xdebug: true
#             with_visual_tests: true

#           - image_name: lpa-shared-test
#             dockerfile_path: ./shared/docker/test-runner
#             dockerfile_target: test-runner
#             snyk_policy_path: shared/docker/test-runner/.snyk
#             scan_id: shared_test
#             archive_name: shared-test
#     steps:
#       - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
#         with:
#           persist-credentials: false
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
#         with:
#           aws-region: eu-west-1
#           role-to-assume: ${{ inputs.oidc_docker_role }}
#       - name: Install Dependencies
#         if: matrix.image_name == 'online-lpa/front_web'
#         run: |
#           docker compose run --rm npm-front ci --ignore-scripts
#           docker compose run --rm npm-front run build
#       - name: Setup Docker Buildx
#         uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
#       - name: ECR Login
#         uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
#         with:
#           registries: 311462405659
#       - name: Build Image
#         uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
#         with:
#           context: .
#           load: true
#           tags: ${{ matrix.image_name }}:latest
#           push: false
#           file: ${{ matrix.dockerfile_path }}/Dockerfile
#           target: ${{ matrix.dockerfile_target }}
#           build-args: |
#             OPG_LPA_COMMON_APP_VERSION=${{ github.sha }}
#             ENABLE_XDEBUG=${{ matrix.with_xdebug && '1' || '0' }}
#             VISUAL_TESTS=${{ matrix.with_visual_tests && 'true' || 'false' }}
#       - name: Run SNYK vulnerability scan for ${{ matrix.scan_id }}
#         uses: ministryofjustice/opg-github-actions/actions/snyk-scan@722a5f955424aaba01e9ca43d68390cd4048d6e1 # v4.10.2
#         with:
#           SNYK_TEST_IMAGE: ${{ matrix.image_name }}:latest
#           SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
#           sarif_filepath: ./test-results
#           sarif_filename: ${{ matrix.scan_id }}_snyk.sarif
#           snyk_policy_path: ${{ github.workspace }}/${{ matrix.snyk_policy_path }}
#           snyk_test_args: --severity-threshold=high
#       - name: Tag and Push Container
#         if: matrix.archive_name == ''
#         run: |
#           docker tag ${{ matrix.image_name }}:latest 311462405659.dkr.ecr.eu-west-1.amazonaws.com/${{ matrix.image_name }}:${{ inputs.tag }}
#           docker push 311462405659.dkr.ecr.eu-west-1.amazonaws.com/${{ matrix.image_name }}:${{ inputs.tag }}
#       - name: Archive image
#         if: matrix.archive_name != ''
#         run: |
#           mkdir -p /tmp/images
#           docker save -o /tmp/images/image.tar ${{ matrix.image_name }}:latest
#       - name: Upload image archive
#         if: matrix.archive_name != ''
#         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
#         with:
#           name: ${{ matrix.archive_name }}
#           path: /tmp/images/image.tar
