name: "[Docker] Build and Push Images"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag for docker image"
        required: true
        type: string
      oidc_docker_role:
        description: "OIDC role to assume for ecr permissions"
        required: true
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      SNYK_OPG_ORG_TOKEN:
        required: true

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  docker_build_scan_push:
    name: "docker build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: online-lpa/front_app
            dockerfile_path: ./service-front/docker/app
            service_path: ./service-front
            snyk_policy_path: service-front/docker/app/.snyk
            scan_id: front_app

          - image_name: online-lpa/front_web
            dockerfile_path: ./service-front/docker/web
            service_path: ./service-front
            snyk_policy_path: service-front/docker/web/.snyk
            scan_id: front_web

          - image_name: online-lpa/api_app
            dockerfile_path: ./service-api/docker/app
            service_path: ./service-api
            snyk_policy_path: service-api/docker/app/.snyk
            scan_id: api_app

          - image_name: online-lpa/api_web
            dockerfile_path: ./service-api/docker/web
            service_path: ./service-api
            snyk_policy_path: service-api/docker/web/.snyk
            scan_id: api_web

          - image_name: online-lpa/admin_app
            dockerfile_path: ./service-admin/docker/app
            service_path: ./service-admin
            snyk_policy_path: service-admin/docker/app/.snyk
            scan_id: admin_app

          - image_name: online-lpa/admin_web
            dockerfile_path: ./service-admin/docker/web
            service_path: ./service-admin
            snyk_policy_path: service-admin/docker/web/.snyk
            scan_id: admin_web

          - image_name: online-lpa/pdf_app
            dockerfile_path: ./service-pdf/docker/app
            service_path: ./service-pdf
            snyk_policy_path: service-pdf/docker/app/.snyk
            scan_id: pdf_app

          - image_name: online-lpa/seeding_app
            dockerfile_path: ./service-seeding/docker/app
            service_path: ./service-seeding
            snyk_policy_path: service-seeding/docker/app/.snyk
            scan_id: seeding_app

          - image_name: lambda-aurora_scheduler
            dockerfile_path: ./aurora-scheduler/docker
            service_path: ./aurora-scheduler
            snyk_policy_path: aurora-scheduler/docker/.snyk
            scan_id: aurora_scheduler
            override_tag: latest

          - image_name: lpa-admin-app-test
            dockerfile_path: ./service-admin/docker/app
            dockerfile_target: test-runner
            service_path: ./service-admin
            snyk_policy_path: service-admin/docker/app/.snyk
            scan_id: admin_app_test
            archive_name: admin-app-test
            with_xdebug: true

          - image_name: lpa-api-app-test
            dockerfile_path: ./service-api/docker/app
            dockerfile_target: test-runner
            service_path: ./service-api
            snyk_policy_path: service-api/docker/app/.snyk
            scan_id: api_app_test
            archive_name: api-app-test
            with_xdebug: true

          - image_name: lpa-front-app-test
            dockerfile_path: ./service-front/docker/app
            dockerfile_target: test-runner
            service_path: ./service-front
            snyk_policy_path: service-front/docker/app/.snyk
            scan_id: front_app_test
            archive_name: front-app-test
            with_xdebug: true

          - image_name: lpa-pdf-app-test
            dockerfile_path: ./service-pdf/docker/app
            dockerfile_target: test-runner
            service_path: ./service-pdf
            snyk_policy_path: service-pdf/docker/app/.snyk
            scan_id: pdf_app_test
            archive_name: pdf-app-test
            with_xdebug: true
            with_visual_tests: true

          - image_name: lpa-shared-test
            dockerfile_path: ./shared/docker/test-runner
            dockerfile_target: test-runner
            service_path: ./shared
            snyk_policy_path: shared/docker/test-runner/.snyk
            scan_id: shared_test
            archive_name: shared-test

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_docker_role }}
          role-duration-seconds: 3600
          role-session-name: OPGMakeaLPAECRGithubAction

      - name: Apply override tag
        id: set_image_tag
        env:
          IMAGE_TAG: ${{ inputs.tag }}
        run: |
          if [ ${{ matrix.override_tag }} ]; then
            IMAGE_TAG=${{ matrix.override_tag }}
          fi
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        if: ${{ (matrix.image_name == 'online-lpa/front_web') }}
        with:
          node-version-file: ".nvmrc"

      - name: Install Dependencies
        if: ${{ (matrix.image_name == 'online-lpa/front_web') }}
        run: |
          pushd service-front/
          npm ci --ignore-scripts && npm install -g --ignore-scripts sass
          ./build.sh
          popd

      - name: Setup Docker Buildx
        id: docker_buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          install: true

      - name: Setup Docker Layer Cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.image_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.image_name }}-

      - name: ECR Login
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registries: 311462405659

      - name: Build Image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          load: true
          tags: ${{ matrix.image_name }}:latest
          push: false
          file: ${{ matrix.dockerfile_path }}/Dockerfile
          target: ${{ matrix.dockerfile_target }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          build-args: |
            OPG_LPA_COMMON_APP_VERSION=${{ github.sha }}
            ENABLE_XDEBUG=${{ matrix.with_xdebug && '1' || '0' }}
            VISUAL_TESTS=${{ matrix.with_visual_tests && 'true' || 'false' }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      #SNYK SCAN STEPS
      - name: Run SNYK vulnerability scan for ${{ matrix.scan_id }}
        id: snyk_scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@8dea82fc8b8e7ffca431f0fb83848d523147ccd8 # v4.5.0
        with:
          SNYK_TEST_IMAGE: ${{ matrix.image_name }}:latest
          SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
          sarif_filepath: ./test-results
          sarif_filename: ${{ matrix.scan_id }}_snyk.sarif
          snyk_policy_path: ${{ github.workspace }}/${{ matrix.snyk_policy_path }}
          snyk_test_args: --severity-threshold=high

      - name: Format undefined severity values
        if: always() && hashFiles(format('./test-results/{0}_snyk.sarif', matrix.scan_id)) != ''
        run: |
          sed -i 's/"null"/"0"/g; s/"undefined"/"0"/g' ./test-results/${{ matrix.scan_id }}_snyk.sarif

      - name: Inspect SARIF results
        if: always()
        run: |
          echo "=== SNYK SCAN SUMMARY FOR ${{ matrix.scan_id }} ==="
          echo "SARIF file: $file"
          echo "scan outcome: ${{ steps.snyk_scan.outcome }}"

          if [ -f "./test-results/${{ matrix.scan_id }}_snyk.sarif" ]; then
            echo "SARIF file exists, counting runs"
            runs=$(jq '.runs | length' ./test-results/${{ matrix.scan_id }}_snyk.sarif)
            echo "SARIF file has $runs runs"
          else
            echo "SARIF file does not exist, skipping run count"
          fi

      # Split SARIF results if run limit exceeds 20
      - name: Split SARIF results if run limit exceeds 20
        if: always()
        run: |
          file="./test-results/${{ matrix.scan_id }}_snyk.sarif"
          base="./test-results/${{ matrix.scan_id }}_snyk"
          runs=$(jq '.runs | length' $file)
          echo "runs=$runs"

          if [ $runs -gt 20 ]; then
            echo "SARIF file has $runs runs, splitting into 2 files (20 run limit)"
            jq '.runs = .runs[0:20]' $file > ${base}_part_01.sarif
            jq '.runs = .runs[20:]' $file > ${base}_part_02.sarif
          else
            echo "SARIF file has $runs runs, keeping as 1 file"
            mv $file ${base}_part_01.sarif
          fi

      - name: Upload SARIF results part 1
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
        if: always() && hashFiles(format('./test-results/{0}_snyk_part_01.sarif', matrix.scan_id)) != ''
        with:
          sarif_file: ./test-results/${{ matrix.scan_id }}_snyk_part_01.sarif
          category: ${{ matrix.scan_id }}-1

      - name: Upload SARIF results part 2
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
        if: always() && hashFiles(format('./test-results/{0}_snyk_part_02.sarif', matrix.scan_id)) != ''
        with:
          sarif_file: ./test-results/${{ matrix.scan_id }}_snyk_part_02.sarif
          category: ${{ matrix.scan_id }}-2

      - name: Tag and Push Container
        if: matrix.archive_name == ''
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.set_image_tag.outputs.image_tag }}
          IMAGE_NAME: ${{ matrix.image_name }}
        run: |
          docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:main-$IMAGE_TAG
            docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
            docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
          fi
          docker push --all-tags $ECR_REGISTRY/$IMAGE_NAME

      - name: Cache image
        if: matrix.archive_name != ''
        env:
          IMAGE_NAME: ${{ matrix.image_name }}
        run: |
          mkdir -p /tmp/images
          docker save -o /tmp/images/image.tar $IMAGE_NAME:latest

      - name: Archive image
        if: matrix.archive_name != ''
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.archive_name }}
          path: /tmp/images/image.tar
