# minCoverage sets the minimum coverage level for unit tests; if coverage is less than this,
# the build fails. The values for these parameters were set on 2023-03-03 from the coverage
# levels of the phpunit tests at that time, rounded down. See LPAL-1143 for more details.
name: phpunit tests

on: workflow_call

jobs:
  phpunit:
    name: phpunit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scan:
          - service: admin-app-test
            directory: service-admin
            minCoverage: 3
          - service: front-app-test
            directory: service-front
            minCoverage: 85
          - service: api-app-test
            directory: service-api
            minCoverage: 74
          - service: pdf-app-test
            directory: service-pdf
            minCoverage: 84
          - service: shared-test
            directory: shared
            minCoverage: 90
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: ${{ matrix.scan.service }}
          path: /tmp/images
      - name: Load Images
        run: |
          docker load -i /tmp/images/image.tar

      - name: Run phpunit
        id: phpunit
        run: |
          mkdir -m 0777 ./output
          docker compose run --rm \
            --env XDEBUG_MODE=coverage \
            --volume ./output:/tmp/output \
            ${{ matrix.scan.service }} \
            vendor/bin/phpunit --coverage-html /tmp/output/coverage-html --coverage-xml /tmp/output/coverage-xml --log-teamcity /tmp/output/teamcity.log
      - name: Identity problems
        if: ${{ always() && steps.phpunit.outcome == 'failure' }}
        run: |
          echo "::add-matcher::./.github/problem-matchers/phpunit-teamcity.json"
          sed -i 's|/app/|/app/${{ matrix.scan.directory }}/|g' ./output/teamcity.log
          cat ./output/teamcity.log
      - name: Check coverage
        run: |
          docker compose run --rm --volume ./output/coverage-xml:/tmp/output/coverage-xml ${{ matrix.scan.service }} \
          php /shared/src/functions/check_coverage.php /tmp/output/coverage-xml/index.xml ${{ matrix.scan.minCoverage }}
      - name: Upload Coverage Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ matrix.scan.service }}-coverage-html
          path: ./output/coverage-html/
          overwrite: true
