# minCoverage sets the minimum coverage level for unit tests; if coverage is less than this,
# the build fails. The values for these parameters were set on 2023-03-03 from the coverage
# levels of the phpunit tests at that time, rounded down. See LPAL-1143 for more details.
name: phpunit tests

on: workflow_call

jobs:
  phpunit:
    name: phpunit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scan:
          - service: admin-app-test
            minCoverage: 3
          - service: front-app-test
            minCoverage: 85
          - service: api-app-test
            minCoverage: 74
          - service: pdf-app-test
            minCoverage: 84
          - service: shared-test
            minCoverage: 90
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: ${{ matrix.scan.service }}
          path: /tmp/images
      - name: Load Images
        run: |
          docker load -i /tmp/images/image.tar

      - name: Run phpunit
        run: |
          mkdir -m 0777 ./coverage-html ./coverage-xml
          docker compose run --rm \
            --env XDEBUG_MODE=coverage \
            --volume ./coverage-html:/tmp/coverage-html \
            --volume ./coverage-xml:/tmp/coverage-xml \
            ${{ matrix.scan.service }} \
            vendor/bin/phpunit --coverage-html /tmp/coverage-html --coverage-xml /tmp/coverage-xml
      - name: Check coverage
        run: |
          docker compose run --rm --volume ./coverage-xml:/tmp/coverage-xml ${{ matrix.scan.service }} \
          php /shared/src/functions/check_coverage.php /tmp/coverage-xml/index.xml ${{ matrix.scan.minCoverage }}
      - name: Upload Coverage Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ matrix.scan.service }}-coverage-html
          path: ./coverage-html/
          overwrite: true
