# minCoverage sets the minimum coverage level for unit tests; if coverage is less than this,
# the build fails. The values for these parameters were set on 2023-03-03 from the coverage
# levels of the phpunit tests at that time, rounded down. See LPAL-1143 for more details.
name: phpunit tests

on: workflow_call

jobs:
  phpunit:
    name: phpunit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scan:
          - service: admin-app-test
            minCoverage: 3
          - service: front-app-test
            minCoverage: 85
          - service: api-app-test
            minCoverage: 74
          - service: pdf-app-test
            minCoverage: 84
          - service: shared-test
            minCoverage: 90
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ matrix.scan.service }}
          path: /tmp/images
      - name: Load Images
        run: |
          docker load -i /tmp/images/image.tar

      - name: Run phpunit
        run: |
          mkdir -m 0777 ./coverage-html ./coverage-xml
          docker compose run --rm \
            --env XDEBUG_MODE=coverage \
            --volume ./coverage-html:/tmp/coverage-html \
            --volume ./coverage-xml:/tmp/coverage-xml \
            ${{ matrix.scan.service }} \
            vendor/bin/phpunit --coverage-html /tmp/coverage-html --coverage-xml /tmp/coverage-xml
        continue-on-error: ${{ matrix.scan.ignoreFailures == true }}

      - name: Check coverage
        if: ${{ matrix.scan.ignoreFailures != true }}
        run: |
          docker compose run --rm --volume ./coverage-xml:/tmp/coverage-xml ${{ matrix.scan.service }} \
          php /shared/src/functions/check_coverage.php /tmp/coverage-xml/index.xml ${{ matrix.scan.minCoverage }}

      - name: Upload Coverage Artifacts
        if: ${{ matrix.scan.ignoreFailures != true }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.scan.service }}-coverage-html
          path: ./coverage-html/
          overwrite: true
