name: trivy-scan
on:
  schedule:
    # run at 6am on a Monday
    - cron: "0 6 * * 1"

jobs:
  filter-and-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        scan:
          - name: front_app
            image_name: online-lpa/front_app
          - name: front_web
            image_name: online-lpa/front_web
          - name: api_app
            image_name: online-lpa/api_app
          - name: api_web
            image_name: online-lpa/api_web
          - name: admin_app
            image_name: online-lpa/admin_app
          - name: admin_web
            image_name: online-lpa/admin_web
          - name: pdf_app
            image_name: online-lpa/pdf_app
          - name: seeding_app
            image_name: online-lpa/seeding_app
          - name: lambda-aurora_scheduler
            image_name: lambda-aurora_scheduler
    env:
      TRIVY_VERSION: 0.69.2
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Filter paths
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            check: '${{ matrix.scan.path }}/**'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_DOCKER_ROLE }}
          role-duration-seconds: 900
          role-session-name: OPGLPABuildPipeline

      - name: ecr login
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registries: 311462405659

      - name: Trivy Image Vulnerability Scanner
        id: trivy_scan
        run: |
          sleep $((RANDOM % 18));
          mkdir -p -m 0777 .trivy-cache ./test-results/
          docker run \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --volume ./.trivy-cache:/root/.cache \
            --volume ./test-results:/test-results \
            --env TRIVY_DB_REPOSITORY=${{ steps.login_ecr.outputs.registry }}/trivy-db-public-ecr/aquasecurity/trivy-db:2 \
            --env TRIVY_JAVA_DB_REPOSITORY=${{ steps.login_ecr.outputs.registry }}/trivy-db-public-ecr/aquasecurity/trivy-java-db:1 \
            --env TRIVY_USERNAME=${{ steps.login_ecr.outputs.docker_username_311462405659_dkr_ecr_eu_west_1_amazonaws_com }} \
            --env TRIVY_PASSWORD=${{ steps.login_ecr.outputs.docker_password_311462405659_dkr_ecr_eu_west_1_amazonaws_com }} \
            aquasec/trivy:${{ env.TRIVY_VERSION }} image \
            ${{ steps.login_ecr.outputs.registry }}/${{ matrix.image_uri }}:latest \
            --format table \
            --severity HIGH,CRITICAL \
            --exit-code 1
