name: "Snyk IAC scan"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      oidc_role:
        description: "Role to use to fetch Snyk container"
        required: true
        type: string
    secrets:
      snyk_token:
        required: true

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  run_seeding_task:
    name: Run seeding task
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_role }}
          role-duration-seconds: 3600
          role-session-name: OPGLPASnykIACScan

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registries: 311462405659

      - name: Snyk IaC
        id: snyk_iac
        uses: ministryofjustice/opg-github-actions/actions/snyk-iac@9e8b7c2fb29c11e77b12913f74459fa48b11829f # v4.8.2
        with:
          iac_test_directory: "./terraform/environment/"
          SNYK_TOKEN: ${{ secrets.snyk_token }}
          snyk_test_args: "--severity-threshold=high"
      # - name: Upload Snyk IaC results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
      #   if: always()
      #   with:
      #     category: "IaC"
      #     sarif_file: "test-results/snyk.sarif"
