name: "Snyk IAC scan"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      oidc_role:
        description: "Role to use to fetch Snyk container"
        required: true
        type: string
    secrets:
      snyk_token:
        required: true

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  snyk_iac_scan:
    name: Run Snyk IAC scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: region
            terraform_configuration_path: ./terraform/region/
          - name: account
            terraform_configuration_path: ./terraform/account/
          - name: environment
            terraform_configuration_path: ./terraform/environment/

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_role }}
          role-duration-seconds: 3600
          role-session-name: OPGLPASnykIACScan

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
        with:
          registries: 311462405659

      - name: Snyk IaC ${{ matrix.name }}
        id: snyk_iac
        uses: ministryofjustice/opg-github-actions/actions/snyk-iac@77bb12e7fec3bcee9a6a35cb21361195e027a12a # v4.9.0
        with:
          iac_test_directory: "${{ matrix.terraform_configuration_path }}"
          SNYK_TOKEN: ${{ secrets.snyk_token }}
          snyk_test_args: "--severity-threshold=high"
          snyk_policy_path: "${{ matrix.terraform_configuration_path }}.snyk"
      - name: Upload Snyk IaC results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        if: always()
        with:
          category: "IaC-${{matrix.name}}"
          sarif_file: "test-results/snyk.sarif"
