name: "[Workflow] Run Feedback DB Task"

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      task_name:
        description: "Name of the task to run"
        required: true
        type: string
      oidc_role:
        description: "Role to use to start an ECS task"
        required: true
        type: string

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  run_seeding_task:
    name: Run seeding task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Download Terraform Task definition
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: terraform-artifact
          path: /tmp/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_role }}
          role-duration-seconds: 900
          role-session-name: OPGLPABuildPipeline

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          version: "0.11.21"
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install Python dependencies
        working-directory: scripts/pipeline
        run: uv sync --locked

      - name: Start ECS task
        working-directory: scripts/pipeline
        run: uv run python start_task/ecs_start_task.py --task_name ${{ inputs.task_name }}
