name: trivy-scan
on:
  push:
    branches:
      - main
  pull_request:
jobs:

  trivy-scan-config:
    strategy:
      matrix:
        folder:
          - ./service-api
          - ./service-admin
          - ./service-front
          - ./service-pdf
          - ./service-perfplat
          - ./tests
          - ./cypress
          - ./service-perfplat
          - ./terraform/account

    name: trivy-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          scan-ref: ${{ matrix.folder }}
          hide-progress: false
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'

  trivy-scan-filesystem:
    strategy:
      matrix:
        folder:
          - ./service-api
          - ./service-admin
          - ./service-front
          - ./service-pdf
          - ./service-perfplat
          - ./service-perfplat

    name: trivy-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          scan-ref: ${{ matrix.folder }}
          hide-progress: false
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
