name: trivy-scan-config
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'service-api/**'
      - 'service-admin/**'
      - 'service-front/**'
      - 'service-pdf/**'
      - 'tests/**'
      - 'cypress/**'
      - 'terraform/account/**'
      - 'local-ssl/**'
      - 'node-build-assets/**'

jobs:
  filter-changes-config:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        scan:
          - name: service-api
            path: './service-api/**'
            code-scan: true
          - name: service-admin
            path: './service-admin/**'
            code-scan: true
          - name: service-front
            path: './service-front/**'
            code-scan: true
          - name: service-pdf
            path: './service-pdf/**'
            code-scan: true
          - name: tests
            path: './tests/**'
            code-scan: true
          - name: cypress
            path: './cypress/**'
            code-scan: true
          - name: terraform-account
            path: './terraform/account/**'
            code-scan: false
#          - name: terraform-environment
#            path: './terraform/environment/**'
#            code-scan: false
          - name: local-ssl
            path: './local-ssl/**'
            code-scan: false
          - name: node-build-assets
            path: './node-build-assets/**'
            code-scan: false

    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters:  |
          check: ${{ matrix.scan.path }}
    - name: Checkout code
      if: steps.filter.outputs.check == 'true'
      uses: actions/checkout@v2

    - name: Run Trivy vulnerability scanner for IaC
      if: steps.filter.outputs.check == 'true'
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        ignore-unfixed: true
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: '${{matrix.scan.name}}/trivy-results-config.sarif'
        scan-ref: ./${{ matrix.scan.path }}
        hide-progress: false

    - name: Run Trivy vulnerability scanner for Code
      if: steps.filter.outputs.check == 'true' && matrix.scan.code-scan == true
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'code'
        ignore-unfixed: true
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: '${{matrix.scan.name}}/trivy-results-code.sarif'
        scan-ref: ./${{ matrix.scan.path }}
        hide-progress: false

    - name: Upload Trivy code scan results to GitHub Security tab
      if: steps.filter.outputs.check == 'true' && matrix.scan.code-scan == true
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: '${{ matrix.scan.name }}/trivy-results-code.sarif'

    - name: Upload Trivy IaC scan results to GitHub Security tab
      if: steps.filter.outputs.check == 'true'
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: '${{ matrix.scan.name }}/trivy-results-config.sarif'
