name: "[Workflow] Destroy ephemeral environment"

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  actions: none
  checks: none
  contents: read
  deployments: write
  id-token: write
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  workspace_name:
    runs-on: ubuntu-latest
    outputs:
      safe_branch_name: ${{ steps.safe_branch_name.outputs.safe }}
    steps:
      - name: Set safe branch name
        id: safe_branch_name
        uses: ministryofjustice/opg-github-actions/actions/branch-name@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
    if: github.event.pull_request.merged == true

  cleanup_workspace:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs:
      - workspace_name
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Get terraform version
        id: set-terraform-version
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
        with:
          terraform_directory: "./terraform/environment"

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ steps.set-terraform-version.outputs.version }}
          terraform_wrapper: false

      - uses: ministryofjustice/opg-github-actions/actions/github-deploy-key@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
        with:
          deploy_key: ${{ secrets.OPG_LPA_DEPLOY_KEY_PRIVATE_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-1
          role-duration-seconds: 900
          role-session-name: OPGLPADestroyEphemeralEnvironment
          role-to-assume: ${{ vars.OIDC_TERRAFORM_ROLE_DEVELOPMENT }}

      - name: Run workspace cleanup
        working-directory: ./terraform/environment
        env:
          TF_VAR_pagerduty_token: ${{ secrets.PAGERDUTY_TOKEN }}
        run: |
          ../../scripts/pipeline/workspace_cleanup/destroy_workspace.sh ${{ github.event.number }}${{ needs.workspace_name.outputs.safe_branch_name }}
