name: "[Workflow] PR - No changes"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "service-*/**"
      - "cypress/**"
      - "terraform/**"
      - "scripts/**"
      - ".github/workflows/**"

permissions:
  contents: read
  security-events: none
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  end_of_pr_workflow:
    name: End of PR Workflow
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: End of PR Workflow
        run: |
          echo "No further action required"