<div class="article-container group">
    <article role="article" class="group">
        <div class="inner">
            <div class="LPA-details right">
                <h3>LPA for <?= $this->lpaType ?></h3>
                <ul>
                    <li>For <?= $this->donorName ?>.</li>
                    <li>Created on <?= $this->creationDate ?>.</li>
                </ul>
                <div class="LPA-actions">
                    <a href="<?= $this->editRoute ?>">View or edit this LPA</a> &nbsp;&nbsp; | &nbsp;&nbsp; <a
                        id="delete-lpa" href="<?= $this->deleteRoute ?>">Delete this LPA</a>
                </div>
            </div>

            <div class="paragraph-block">

                <p>That’s all we need for the LPA itself. Now you can review your LPA, pay the registration fee, print
                    and
                    sign the LPA and send it to the Office of the Public Guardian.</p>

            </div>

            <div class="next-step-section">
                <h2>Review you LPA</h2>

                <p>Click below to review your LPA and edit it, if you need to. You can also print your LPA now and
                    register
                    it later. However, we recommend that you move on to paying your registration fee as soon as you are
                    happy with the details of your LPA. That way, the Office of the Public Guardian can deal with any
                    problems with the LPA in good time.</p>

                <a class="button" href="<?= $this->downloadRoute ?>" target="_blank">Review LPA</a>
            </div>

            <div class="next-step-section">
                <h2>Review you LPA</h2>

                <p>Click below to review your LPA and edit it, if you need to. You can also print your LPA now and
                    register
                    it later. However, we recommend that you move on to paying your registration fee as soon as you are
                    happy with the details of your LPA. That way, the Office of the Public Guardian can deal with any
                    problems with the LPA in good time.</p>

                <a class="button" href="<?= $this->nextRoute ?>">Pay your registration fee now</a>
            </div>

        </div>
    </article>
</div>