<div class="article-container group">
    <article role="article" class="group">
        <div class="inner lpa created">
            <div class="paragraph-block">

                <p>That’s all we need for the LPA itself. Now you can review your LPA, pay the registration fee, print
                    and
                    sign the LPA and send it to the Office of the Public Guardian.</p>

            </div>

            <div class="next-step-section">
                <h2>Review your LPA</h2>

                <p>Click below to review your LPA and edit it, if you need to. You can also print your LPA now and register it later. However, we recommend that you move on to completing the registration section as soon as you are happy with the details of your LPA. That way, the Office of the Public Guardian (OPG) can deal with any problems with the LPA in good time.</p>

                <p><strong>Important: don't send your LPA to OPG without paying the registration fee – below – and completing that section of the form. OPG can't register your LPA, and you can't use it, until you have paid the fee and completed that section.</strong></p>

                <a class="button" href="<?= $this->downloadRoute ?>" target="_blank">Review LPA</a>
            </div>

            <div class="next-step-section">
                <h2>Register the LPA</h2>

                <p>When you click the button below, we'll ask you some questions about registering your LPA, 
                    such as whether you're entitled to a fee reduction and who we should send the registered document to. 
                    You'll then be taken to an online payment page - or you can pay the fee by cheque.</p>

                <a class="button" href="<?= $this->nextRoute ?>">Register the LPA now</a>
            </div>

        </div>
    </article>
</div>