<style>
    <!--
    div#stats {outline:none; width:950px; overflow:auto; margin: 0 auto;}
    table.stats {border:0px solid black; width:950px; background:#EEE; border-collapse: collapse; margin: 40px 0; }
    table.stats th {text-align:center; border:1px solid #ddd; padding:8px; background:#333; color:#eee; font-family:tahoma; font-weight:normal;}
    table.stats td {padding:3px; font-size:16pt; height:30px; text-align:center; vertical-align:middle; border:1px solid #ccc;}
    table.stats td a {text-decoration: none; color:black}
    table.stats tbody.app_stats td {width:180px}
    table.stats tbody.app_stats td.app_status {font-size:10pt; vertical-align: middle; font-family:Verdana; width:100px;}
    table.stats tbody.site td {width:180px;}
    table.stats tbody.db td {width:110px; margin:10px;}

    table.stats td.error {height:200px; background:red;}
    table.stats td.warning {height:200px; background:orange;}
    table.stats td.ok {height:200px; background:#88aa88;}

    table.stats img {width:60px;}
    -->
</style>

<div id='stats'>

    <table class='stats' style="">
        <thead>
        <tr><th>Current Progress</th><th>All applications</th><th>Health and Welfare</th><th>Property and Financial Affairs</th></tr>
        </thead>
        <tbody class='app_stats'>
        <tr>
            <td class='app_status'>Started</td>
            <td><?= $this->laps['all']['started'] ?></td>
            <td><?= $this->laps['health-and-welfare']['started'] ?></td>
            <td><?= $this->laps['property-and-finance']['started'] ?></td>
        </tr>
        <tr>
            <td class='app_status'>Created</td>
            <td><?= $this->laps['all']['created'] ?></td>
            <td><?= $this->laps['health-and-welfare']['created'] ?></td>
            <td><?= $this->laps['property-and-finance']['created'] ?></td>
        </tr>
        <tr>
            <td class='app_status'>Completed</td>
            <td><?= $this->laps['all']['completed'] ?></td>
            <td><?= $this->laps['health-and-welfare']['completed'] ?></td>
            <td><?= $this->laps['property-and-finance']['completed'] ?></td>
        </tr>
        <tr>
            <td class='app_status'><strong>Total</strong></td>
            <td><?= $this->laps['all']['started'] + $this->laps['all']['created'] + $this->laps['all']['completed'] ?></td>
            <td><?= $this->laps['health-and-welfare']['started'] + $this->laps['health-and-welfare']['created'] + $this->laps['health-and-welfare']['completed'] ?></td>
            <td><?= $this->laps['property-and-finance']['started'] + $this->laps['property-and-finance']['created'] + $this->laps['property-and-finance']['completed'] ?></td>
        </tr>
        <tr>
            <td class='app_status'>Deleted</td>
            <td><?= $this->laps['all']['deleted'] ?></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        </tbody>
    </table>

    <table class='stats'>
        <thead>
        <tr>
            <th></th>
            <? foreach( $this->laps['by-month'] as $month=>$values ){ ?>
                <th><?= ( $month == date('Y-m') ) ? 'This Month' : date('F Y', strtotime($month)) ?></th>
            <? } ?>
        </tr>
        </thead>
        <tbody class='app_stats'>
        <tr>
            <td class='app_status'>Started LPAs</td>
            <? foreach( $this->laps['by-month'] as $month=>$values ){ ?>
                <td><?= $values['started'] ?></td>
            <? } ?>
        </tr>
        <tr>
            <td class='app_status'>Created LPAs</td>
            <? foreach( $this->laps['by-month'] as $month=>$values ){ ?>
                <td><?= $values['created'] ?></td>
            <? } ?>
        </tr>
        <tr>
            <td class='app_status'>Completed LPAs</td>
            <? foreach( $this->laps['by-month'] as $month=>$values ){ ?>
                <td><?= $values['completed'] ?></td>
            <? } ?>
        </tr>
        </tbody>
    </table>

</div>
