<style>
    <!--
    div#stats {outline:none; width:950px; overflow:auto; margin: 0 auto;}
    table.stats {border:0px solid black; width:950px; background:#EEE; border-collapse: collapse; margin: 40px 0; }
    table.stats th {text-align:center; border:1px solid #ddd; padding:8px; background:#333; color:#eee; font-family:tahoma; font-weight:normal;}
    table.stats td {padding:3px; font-size:16pt; height:30px; text-align:center; vertical-align:middle; border:1px solid #ccc;}
    table.stats td a {text-decoration: none; color:black}
    table.stats tbody.app_stats td {width:180px}
    table.stats tbody.app_stats td.app_status {font-size:10pt; vertical-align: middle; font-family:Verdana; width:100px;}

    table.stats tbody.app_stats tr.border td { border-top-width: 8px; }
    table.stats tbody.app_stats tr.subquestion td {font-size:9pt; vertical-align: middle; font-family:Verdana; width:100px;}
    table.stats tbody.app_stats tr.subquestion td.app_status {font-size:8pt;}

    table.stats tbody.site td {width:180px;}
    table.stats tbody.db td {width:110px; margin:10px;}

    table.stats td.error {height:200px; background:red;}
    table.stats td.warning {height:200px; background:orange;}
    table.stats td.ok {height:200px; background:#88aa88;}

    table.stats img {width:60px;}
    -->
</style>

<div id='stats'>

    <table class='stats'>
        <thead>
        <tr><th>Total no. of registered users</th><th>Total no. of activated users</th><th>No. of activated users this month</th></tr>
        </thead>
        <tbody class='app_stats'>
        <tr><td><?= $this->users['total'] ?></td><td><?= $this->users['activated'] ?></td><td><?= $this->users['activated-this-month'] ?></td></tr>
        </tbody>
    </table>

    <table class='stats'>
        <thead>
        <tr><th>Current Progress</th><th>All applications</th><th>Health and Welfare</th><th>Property and Financial Affairs</th></tr>
        </thead>
        <tbody class='app_stats'>
        <tr>
            <td class='app_status'>Started</td>
            <td><?= $this->lpas['all']['started'] ?></td>
            <td><?= $this->lpas['health-and-welfare']['started'] ?></td>
            <td><?= $this->lpas['property-and-finance']['started'] ?></td>
        </tr>
        <tr>
            <td class='app_status'>Created</td>
            <td><?= $this->lpas['all']['created'] ?></td>
            <td><?= $this->lpas['health-and-welfare']['created'] ?></td>
            <td><?= $this->lpas['property-and-finance']['created'] ?></td>
        </tr>
        <tr>
            <td class='app_status'>Completed</td>
            <td><?= $this->lpas['all']['completed'] ?></td>
            <td><?= $this->lpas['health-and-welfare']['completed'] ?></td>
            <td><?= $this->lpas['property-and-finance']['completed'] ?></td>
        </tr>
        <tr>
            <td class='app_status'><strong>Total</strong></td>
            <td><?= $this->lpas['all']['started'] + $this->lpas['all']['created'] + $this->lpas['all']['completed'] ?></td>
            <td><?= $this->lpas['health-and-welfare']['started'] + $this->lpas['health-and-welfare']['created'] + $this->lpas['health-and-welfare']['completed'] ?></td>
            <td><?= $this->lpas['property-and-finance']['started'] + $this->lpas['property-and-finance']['created'] + $this->lpas['property-and-finance']['completed'] ?></td>
        </tr>
        <tr>
            <td class='app_status'>Deleted</td>
            <td><?= $this->lpas['all']['deleted'] ?></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        </tbody>
    </table>

    <table class='stats'>
        <thead>
        <tr>
            <th></th>
            <? foreach( $this->lpas['by-month'] as $month=>$values ){ ?>
                <th><?= ( $month == date('Y-m') ) ? 'This Month' : date('F Y', strtotime($month)) ?></th>
            <? } ?>
        </tr>
        </thead>
        <tbody class='app_stats'>
        <tr>
            <td class='app_status'>Started LPAs</td>
            <? foreach( $this->lpas['by-month'] as $month=>$values ){ ?>
                <td><?= $values['started'] ?></td>
            <? } ?>
        </tr>
        <tr>
            <td class='app_status'>Created LPAs</td>
            <? foreach( $this->lpas['by-month'] as $month=>$values ){ ?>
                <td><?= $values['created'] ?></td>
            <? } ?>
        </tr>
        <tr>
            <td class='app_status'>Completed LPAs</td>
            <? foreach( $this->lpas['by-month'] as $month=>$values ){ ?>
                <td><?= $values['completed'] ?></td>
            <? } ?>
        </tr>
        </tbody>
    </table>

    <table class="stats whoareyou">
        <thead>
        <tr>
            <th></th>
            <th>All time</th>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <th><?= ( $month == date('Y-m') ) ? 'This Month' : date('F Y', strtotime($month)) ?></th>
            <? } ?>
        </tr>
        </thead>
        <tbody class="app_stats">
        <tr>
            <td class="app_status">Donor</td>
            <td><?= $this->who['all']['donor']['count'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['donor']['count'] ?></td>
            <? } ?>
        </tr>
        <tr class="border">
            <td class="app_status">Friend or family</td>
            <td><?= $this->who['all']['friendOrFamily']['count'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['friendOrFamily']['count'] ?></td>
            <? } ?>
        </tr>
        <tr class="border">
            <td class="app_status">Professional</td>
            <td><?= $this->who['all']['professional']['count'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['professional']['count'] ?></td>
            <? } ?>
        </tr>
        <tr class="subquestion">
            <td class="app_status">Solicitor</td>
            <td><?= $this->who['all']['professional']['subquestions']['solicitor'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['professional']['subquestions']['solicitor'] ?></td>
            <? } ?>
        </tr>
        <tr class="subquestion">
            <td class="app_status">Will-writer</td>
            <td><?= $this->who['all']['professional']['subquestions']['will-writer'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['professional']['subquestions']['will-writer'] ?></td>
            <? } ?>
        </tr>
        <tr class="subquestion">
            <td class="app_status">Other</td>
            <td><?= $this->who['all']['professional']['subquestions']['other'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['professional']['subquestions']['other'] ?></td>
            <? } ?>
        </tr>

        <tr class="border">
            <td class="app_status">Digital Partner</td>
            <td><?= $this->who['all']['digitalPartner']['count'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['digitalPartner']['count'] ?></td>
            <? } ?>
        </tr>
        <tr class="subquestion">
            <td class="app_status">Age UK</td>
            <td><?= $this->who['all']['digitalPartner']['subquestions']['Age-Uk'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['digitalPartner']['subquestions']['Age-Uk'] ?></td>
            <? } ?>
        </tr>
        <tr class="subquestion">
            <td class="app_status">Alzheimer's Society</td>
            <td><?= $this->who['all']['digitalPartner']['subquestions']['Alzheimer-Society'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['digitalPartner']['subquestions']['Alzheimer-Society'] ?></td>
            <? } ?>
        </tr>
        <tr class="subquestion">
            <td class="app_status">Citizens Advice Bureau</td>
            <td><?= $this->who['all']['digitalPartner']['subquestions']['Citizens-Advice-Bureau'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['digitalPartner']['subquestions']['Citizens-Advice-Bureau'] ?></td>
            <? } ?>
        </tr>

        <tr class="border">
            <td class="app_status">Another organisation</td>
            <td><?= $this->who['all']['organisation']['count'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['organisation']['count'] ?></td>
            <? } ?>
        </tr>
        <tr class="border">
            <td class="app_status">Not said</td>
            <td><?= $this->who['all']['notSaid']['count'] ?></td>
            <? foreach( $this->who['by-month'] as $month=>$values ){ ?>
                <td><?= $values['notSaid']['count'] ?></td>
            <? } ?>
        </tr>
        </tbody>
    </table>

</div>
